import { ABTestExperiment } from '../types';

export const SEED_AB_TESTS: ABTestExperiment[] = [
  {
    id: 'ab-test-whatsapp-approach',
    title: 'Abordagem WhatsApp: Pergunta de Diagnóstico vs Proposta Direta',
    description: 'Compara abertura de conversa com foco na dor de carregamento do site versus apresentação direta de serviços com orçamento.',
    channel: 'whatsapp',
    status: 'active',
    serviceId: 'srv-lp',
    niche: 'Saúde e Clínicas',
    variantA: {
      id: 'A',
      label: 'Variante A (Pergunta Aberta + Diagnóstico)',
      content: 'Olá {nome}, tudo bem? Notei que o site da {empresa} demora um pouco para abrir no celular de quem clica nos anúncios. Vocês já chegaram a avaliar se isso pode estar custando leads que desistem antes de falar no WhatsApp?',
      sentCount: 52,
      replyCount: 16,
      positiveReplyCount: 11,
      conversionCount: 4,
      replyRate: 30.8,
      positiveReplyRate: 21.2,
      conversionRate: 7.7,
    },
    variantB: {
      id: 'B',
      label: 'Variante B (Apresentação Direta + Orçamento)',
      content: 'Olá {nome}, tudo bem? Sou especialista em Landing Pages para clínicas e vi que sua empresa pode melhorar a presença digital. Gostaria de agendar uma reunião para apresentar nosso orçamento de reformulação?',
      sentCount: 48,
      replyCount: 6,
      positiveReplyCount: 2,
      conversionCount: 1,
      replyRate: 12.5,
      positiveReplyRate: 4.2,
      conversionRate: 2.1,
    },
    winnerVariant: 'A',
    winnerMetric: 'replyRate',
    insightSummary: 'A Variante A obteve taxa de resposta 2.4x superior à Variante B nos dados registrados.',
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ab-test-email-subject',
    title: 'E-mail B2B: Prova Social de Nicho vs Assunto Institucional',
    description: 'Teste de copy de e-mail frio focando em resultado alcançado por concorrente do mesmo segmento versus apresentação padrão.',
    channel: 'email',
    status: 'completed',
    serviceId: 'srv-website',
    niche: 'B2B e Indústria',
    variantA: {
      id: 'A',
      label: 'Variante A (Estudo de Caso & ROI)',
      content: 'Assunto: Como aumentamos em 38% os pedidos de orçamento na [Empresa Parceira]\n\nOlá {nome},\nIdentificamos uma oportunidade relevante no portal da {empresa} que pode estar travando a captação de clientes B2B no Google...',
      sentCount: 64,
      replyCount: 12,
      positiveReplyCount: 7,
      conversionCount: 2,
      replyRate: 18.8,
      positiveReplyRate: 10.9,
      conversionRate: 3.1,
    },
    variantB: {
      id: 'B',
      label: 'Variante B (Apresentação Institucional Padrão)',
      content: 'Assunto: Apresentação Institucional de Serviços de Tecnologia Web\n\nPrezado(a) {nome},\nEscrevo para apresentar nossa agência de desenvolvimento de software e portais corporativos com mais de 10 anos no mercado...',
      sentCount: 60,
      replyCount: 4,
      positiveReplyCount: 1,
      conversionCount: 0,
      replyRate: 6.7,
      positiveReplyRate: 1.7,
      conversionRate: 0.0,
    },
    winnerVariant: 'A',
    winnerMetric: 'replyRate',
    insightSummary: 'A Variante A registrou 18.8% de resposta contra 6.7% da Variante B nos dados observados.',
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'ab-test-linkedin-followup',
    title: 'Follow-up LinkedIn: Mensagem Curta de 2 Linhas vs Resumo de Benefícios',
    description: 'Compara acompanhamento ágil e informal após 3 dias sem retorno versus recapitulativo completo com lista de diferenciais.',
    channel: 'linkedin',
    status: 'active',
    variantA: {
      id: 'A',
      label: 'Variante A (Check-in Rápido)',
      content: 'Oi {nome}, tudo bem? Imagino que sua semana esteja corrida. Conseguiu ver a mensagem anterior sobre a automação do funil? Abraço!',
      sentCount: 38,
      replyCount: 13,
      positiveReplyCount: 9,
      conversionCount: 3,
      replyRate: 34.2,
      positiveReplyRate: 23.7,
      conversionRate: 7.9,
    },
    variantB: {
      id: 'B',
      label: 'Variante B (Recapitulativo Detalhado)',
      content: 'Olá {nome}, passando para recapitular os 4 pontos que conversamos: 1) Redução do tempo de resposta; 2) Integração do WhatsApp; 3) Relatórios em tempo real; 4) Suporte dedicado. Qual o melhor dia para conversarmos?',
      sentCount: 36,
      replyCount: 6,
      positiveReplyCount: 3,
      conversionCount: 1,
      replyRate: 16.7,
      positiveReplyRate: 8.3,
      conversionRate: 2.8,
    },
    winnerVariant: 'A',
    winnerMetric: 'replyRate',
    insightSummary: 'A Variante A registrou taxa de resposta de 34.2% frente a 16.7% da Variante B.',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
