import { DetailedObjection, FollowUpItem } from '../types/scripts';

function createObjectionFollowUps(prefix: string, contextName: string): FollowUpItem[] {
  return [
    {
      id: `${prefix}_fu_1`,
      stepNumber: 1,
      intervalHours: 6,
      intervalText: '4–8 horas',
      message: `Olá, {{nome}}. Conseguiu refletir sobre a alternativa que te passei para a {{empresa}}?`,
      objective: 'Relembrar de forma curta após o tratamento da objeção.',
      tone: 'Respeitoso e consultivo',
      condition: 'Tratamento de objeção enviado sem resposta inicial.',
      whenNotToUse: 'Fora do horário comercial.',
    },
    {
      id: `${prefix}_fu_2`,
      stepNumber: 2,
      intervalHours: 24,
      intervalText: '1 dia',
      message: `Oi, {{nome}}. Passando para saber se faz sentido mantermos essa conversa sobre {{servico}} na {{empresa}} ou se prefere pausar.`,
      objective: 'Checar timing e intenção sem pressão.',
      tone: 'Direto e profissional',
      condition: '24h sem resposta após objeção.',
      whenNotToUse: 'Se o cliente pediu tempo explícito.',
    },
    {
      id: `${prefix}_fu_3`,
      stepNumber: 3,
      intervalHours: 48,
      intervalText: '2 dias',
      message: `Olá, {{nome}}. Se quiser, posso te mandar um comparativo visual bem objetivo para te ajudar a avaliar esse ponto.`,
      objective: 'Oferecer material de apoio.',
      tone: 'Prestativo',
      condition: '2 dias de silêncio.',
      whenNotToUse: 'Se o cliente for reativo.',
    },
    {
      id: `${prefix}_fu_4`,
      stepNumber: 4,
      intervalHours: 96,
      intervalText: '4 dias',
      message: `Oi, {{nome}}. Tudo bem? Imagino que a rotina esteja corrida. Fico à disposição quando quiser retomar!`,
      objective: 'Reduzir esforço de retorno.',
      tone: 'Empático',
      condition: '4 dias sem retorno.',
      whenNotToUse: 'Se o contato for inválido.',
    },
    {
      id: `${prefix}_fu_5`,
      stepNumber: 5,
      intervalHours: 168,
      intervalText: '7 dias',
      message: `Olá, {{nome}}. Passando apenas para checar se houve alguma mudança de cenário na {{empresa}} em relação a esse ponto.`,
      objective: 'Checagem semanal de cenário.',
      tone: 'Consultivo',
      condition: '7 dias sem avanço.',
      whenNotToUse: 'Se o cliente pediu para não mandar mais mensagens.',
    },
    {
      id: `${prefix}_fu_6`,
      stepNumber: 6,
      intervalHours: 336,
      intervalText: '14 dias',
      message: `Olá, {{nome}}. Para não insistir sem necessidade: vou arquivar nosso contato por aqui. Um grande abraço para a {{empresa}}!`,
      objective: 'Fechamento de loop respeitoso.',
      tone: 'Desapegado',
      condition: '14 dias sem resposta pós-objeção.',
      whenNotToUse: 'Se o cliente responder.',
    },
  ];
}

export const DETAILED_OBJECTIONS: DetailedObjection[] = [
  // 1. Está caro
  {
    id: 'obj_1',
    code: 'ESTA_CARO',
    title: 'Está caro / Preço elevado',
    keywords: ['caro', 'preço alto', 'muito caro', 'valor alto', 'acima'],
    category: 'preco',
    possibleMeaning: 'Falta de percepção de retorno sobre investimento, comparação com ferramentas amadoras ou restrição orçamentária real.',
    whatNotToSay: 'Nunca diga imediatamente: "Posso te dar um desconto!" ou "É caro porque é o melhor".',
    diagnosticQuestion: 'Quando você diz que está caro, é em relação ao orçamento que tinha previsto ou ao que imaginava que o projeto custaria?',
    shortResponse: 'Entendo perfeitamente, {{nome}}. Para eu te orientar melhor: é em relação ao orçamento que você tinha previsto ou ao retorno que imagina ter?',
    consultativeResponse: 'Compreendo a preocupação com investimento, {{nome}}. Mas a questão central não é o custo de implementar, e sim o quanto a {{empresa}} deixa de faturar todo mês com {{problema}}. Uma única conversão a mais já costuma pagar 100% da solução.',
    whatsAppResponse: 'Entendo, {{nome}}! Quando diz que está caro, você compara com o orçamento que tinha separado ou imaginava uma estrutura diferente?',
    callResponse: 'Perfeito, {{nome}}, entendo seu cuidado financeiro. Deixa eu te perguntar: se esse projeto trouxer 3 a 5 novos clientes no primeiro mês, ainda assim seria caro?',
    nextStep: 'Identificar se é falta de caixa, falta de valor ou comparação para apresentar adequação ou contrapartida.',
    followUps: createObjectionFollowUps('obj_1', 'Está caro'),
  },

  // 2. Não tenho orçamento
  {
    id: 'obj_2',
    code: 'NAO_TENHO_ORCAMENTO',
    title: 'Não tenho orçamento / Sem verba agora',
    keywords: ['orçamento', 'sem verba', 'sem grana', 'sem verba no momento'],
    category: 'preco',
    possibleMeaning: 'A empresa não alocou verba para tecnologia neste período ou não enxergou prioridade.',
    whatNotToSay: 'Não insista agressivamente dizendo para ele pegar dinheiro emprestado.',
    diagnosticQuestion: 'Isso é por falta de verba alocada para este trimestre ou porque não era uma prioridade prevista para agora?',
    shortResponse: 'Entendo, {{nome}}. Se verba é o ponto principal, podemos iniciar com uma versão mais enxuta ou programar para o próximo mês?',
    consultativeResponse: 'Entendido, {{nome}}. Muitas empresas organizam o caixa por trimestres. Se fizermos o projeto agora com pagamento programado para quando os primeiros resultados entrarem, te ajudaria?',
    whatsAppResponse: 'Totalmente compreensível, {{nome}}. Vocês costumam rever o orçamento em qual mês para eu me programar por aqui?',
    callResponse: 'Entendo, {{nome}}. Se não for uma prioridade para este mês, tudo bem. Mas se for apenas fluxo de caixa, consigo parcelar para você.',
    nextStep: 'Oferecer condições de parcelamento ou agendar reativação para a data de renovação orçamentária.',
    followUps: createObjectionFollowUps('obj_2', 'Sem orçamento'),
  },

  // 3. Vou pensar
  {
    id: 'obj_3',
    code: 'VOU_PENSAR',
    title: 'Vou pensar / Deixa eu avaliar',
    keywords: ['vou pensar', 'pensar', 'avaliar', 'analisar', 'depois vejo'],
    category: 'timing',
    possibleMeaning: 'Dúvida oculta, medo de errar na contratação, necessidade de consultar alguém ou falta de clareza.',
    whatNotToSay: 'Não diga: "Pensar no que exatamente?" com tom agressivo ou "Não pense, compre agora".',
    diagnosticQuestion: 'Claro! Para eu não ficar insistindo sem necessidade: o que você sente que ainda precisa avaliar com mais calma?',
    shortResponse: 'Com certeza, {{nome}}! Para eu te ajudar nessa reflexão: o ponto a avaliar é preço, prazo ou o modelo da solução?',
    consultativeResponse: 'Geralmente quando alguém precisa pensar, é por um de dois motivos: ou a proposta não fez sentido para a {{empresa}}, ou fez sentido mas faltou algum detalhe de condição ou prazo. Qual é o caso?',
    whatsAppResponse: 'Perfeito, {{nome}}! Pensar é fundamental. Qual ponto específico você gostaria de ponderar para eu já te adiantar os dados certos?',
    callResponse: 'Claro, {{nome}}. Fique super à vontade. Me diz só uma coisa: o que ficou faltando para você se sentir 100% seguro em dar o próximo passo?',
    nextStep: 'Descobrir a objeção real (preço, sócio ou escopo) e saná-la com empatia.',
    followUps: createObjectionFollowUps('obj_3', 'Vou pensar'),
  },

  // 4. Preciso falar com meu sócio
  {
    id: 'obj_4',
    code: 'FALAR_COM_SOCIO',
    title: 'Preciso falar com meu sócio / diretoria',
    keywords: ['sócio', 'socio', 'diretoria', 'meu parceiro', 'comitê'],
    category: 'autoridade',
    possibleMeaning: 'Decisão compartilhada real ou escudo para adiar compromisso.',
    whatNotToSay: 'Não desrespeite a hierarquia interna nem tente forçar o fechamento sem o sócio.',
    diagnosticQuestion: 'Perfeito! Qual é o principal ponto que seu sócio costuma priorizar: prazo, custo ou resultado prático?',
    shortResponse: 'Excelente! Quer que eu te prepare um resumo de 1 página em PDF com o retorno esperado para você apresentar a ele?',
    consultativeResponse: 'Faz total sentido, {{nome}}. Para você não ter o trabalho de explicar tudo, quer que eu participe de uma call de 10 minutos com vocês dois para tirar dúvidas técnicas?',
    whatsAppResponse: 'Perfeito! Quer que eu te mande um áudio ou texto de 3 linhas resumindo a proposta para você só encaminhar para o seu sócio?',
    callResponse: 'Excelente iniciativa. Como vocês tomam essa decisão juntos, qual dia desta semana fica bom para alinharmos em 10 minutos?',
    nextStep: 'Armar o interlocutor com material resumido ou marcar alinhamento conjunto.',
    followUps: createObjectionFollowUps('obj_4', 'Falar com sócio'),
  },

  // 5. Preciso falar com meu marido/esposa
  {
    id: 'obj_5',
    code: 'FALAR_COM_CONJUGE',
    title: 'Preciso falar com meu marido / esposa',
    keywords: ['esposa', 'marido', 'cônjuge', 'família'],
    category: 'autoridade',
    possibleMeaning: 'Empresa familiar onde finanças são compartilhadas.',
    whatNotToSay: 'Não menospreze a decisão conjunta da família.',
    diagnosticQuestion: 'Perfeito! Ele(a) também atua no dia a dia da {{empresa}} ou é para alinhar o investimento familiar?',
    shortResponse: 'Totalmente compreensível, {{nome}}! Fique à vontade para conversar. Se precisar de algum detalhe para mostrar a ele(a), me avise.',
    consultativeResponse: 'Faz todo sentido, decisões familiares são essenciais. Se quiser, te mando um resumo visual bem direto para vocês avaliarem juntos hoje à noite.',
    whatsAppResponse: 'Com certeza, {{nome}}! Quando acha que vocês conseguem conversar sobre isso para eu te mandar uma mensagem amanhã?',
    callResponse: 'Com certeza, {{nome}}. Alinhe com calma. Que dia fica bom para darmos um retorno?',
    nextStep: 'Combinar data exata de retorno respeitando o tempo familiar.',
    followUps: createObjectionFollowUps('obj_5', 'Falar com cônjuge'),
  },

  // 6. Agora não é prioridade
  {
    id: 'obj_6',
    code: 'NAO_E_PRIORIDADE',
    title: 'Agora não é prioridade / Momento inadequado',
    keywords: ['não é prioridade', 'outro momento', 'depois', 'agora não'],
    category: 'timing',
    possibleMeaning: 'Outras demandas consomem a atenção da gestão ou o impacto do problema não foi percebido.',
    whatNotToSay: 'Não tente forçar dizendo que tudo na empresa tem que ser urgente.',
    diagnosticQuestion: 'Entendido. Qual é a principal prioridade da {{empresa}} no momento para eu entender se isso se conecta de alguma forma?',
    shortResponse: 'Entendido, {{nome}}! Qual mês você acredita que seria o momento ideal para retomarmos essa conversa?',
    consultativeResponse: 'Faz total sentido respeitar as prioridades do momento. Se resolver {{problema}} não é urgente agora, prefiro arquivar por aqui e te procurar quando vocês estiverem prontos.',
    whatsAppResponse: 'Perfeito, {{nome}}. Para eu não te incomodar antes da hora: quando esse assunto volta a ser prioridade na {{empresa}}?',
    callResponse: 'Entendido, {{nome}}. Respeito totalmente o seu foco atual. Posso colocar um lembrete para falarmos daqui a 60 dias?',
    nextStep: 'Registrar data futura para reativação respeitosa.',
    followUps: createObjectionFollowUps('obj_6', 'Não é prioridade'),
  },

  // 7. Não tenho interesse
  {
    id: 'obj_7',
    code: 'NAO_TENHO_INTERESSE',
    title: 'Não tenho interesse / Desinteresse direto',
    keywords: ['sem interesse', 'não tenho interesse', 'não quero', 'dispensar'],
    category: 'necessidade',
    possibleMeaning: 'Rejeição a abordagens frias ou falta total de identificação com o serviço.',
    whatNotToSay: 'Não seja insistente ou grosseiro. Aplique os 3 Cs: Concordar, Redirecionar, Conduzir eticamente.',
    diagnosticQuestion: 'Entendo perfeitamente. É porque vocês já têm essa parte 100% resolvida ou porque não acreditam que traria retorno para a {{empresa}}?',
    shortResponse: 'Entendido, {{nome}}! Agradeço pela sinceridade. Vou encerrar os contatos para não tomar seu tempo. Sucesso na {{empresa}}!',
    consultativeResponse: 'Entendo perfeitamente, {{nome}}. Para eu não insistir em algo que não faz sentido: vocês já resolveram essa área internamente ou o momento é que não combina?',
    whatsAppResponse: 'Sem problemas, {{nome}}! Obrigado pelo retorno rápido. Fico à disposição se um dia precisarem de algo em {{servico}}.',
    callResponse: 'Compreendo perfeitamente, {{nome}}. Obrigado pelo tempo e um grande abraço!',
    nextStep: 'Respeitar o não, desativar automações e marcar como Do Not Contact se for recusa definitiva.',
    followUps: createObjectionFollowUps('obj_7', 'Não tenho interesse'),
  },

  // 8. Já tenho alguém que faz isso
  {
    id: 'obj_8',
    code: 'JA_TENHO_ALGUEM',
    title: 'Já tenho alguém que faz isso / Agência parceira',
    keywords: ['já tenho agência', 'tenho quem faz', 'já temos profissional', 'sobrinho', 'parceiro'],
    category: 'concorrencia',
    possibleMeaning: 'Contrato ativo com terceiro ou funcionário interno.',
    whatNotToSay: 'Não fale mal do profissional ou agência atual do cliente.',
    diagnosticQuestion: 'Perfeito! E hoje eles estão cumprindo 100% do que vocês precisam ou existe alguma parte que você gostaria que melhorasse?',
    shortResponse: 'Excelente, {{nome}}! Que bom que já têm apoio. Se houver alguma demanda que eles não consigam atender, fico à disposição!',
    consultativeResponse: 'Perfeito! Não quero substituir nada que esteja funcionando bem. Posso só entender uma coisa: essa pessoa cuida especificamente de {{problema}} ou do marketing geral?',
    whatsAppResponse: 'Ótimo, {{nome}}! Se em algum momento vocês precisarem de uma segunda opinião ou projeto pontual, pode contar comigo.',
    callResponse: 'Excelente saber que já têm parceiro. Eles atendem você com agilidade quando precisa de alterações rápidas?',
    nextStep: 'Posicionar-se como alternativa para projetos específicos ou transbordo sem rivalizar agressivamente.',
    followUps: createObjectionFollowUps('obj_8', 'Já tenho alguém'),
  },

  // 9. Já tenho site
  {
    id: 'obj_9',
    code: 'JA_TENHO_SITE',
    title: 'Já tenho site',
    keywords: ['já tenho site', 'ja tenho site', 'site já existe', 'temos página'],
    category: 'necessidade',
    possibleMeaning: 'O cliente acredita que apenas ter uma URL no ar é suficiente.',
    whatNotToSay: 'Nunca diga: "Seu site é feio/antigo/ruim".',
    diagnosticQuestion: 'Perfeito! Ele está trazendo novos clientes no WhatsApp com a frequência que vocês gostariam hoje?',
    shortResponse: 'Excelente, {{nome}}! E hoje o site de vocês converte bem no celular ou você sente que poderia gerar mais contatos?',
    consultativeResponse: 'Sim, eu vi o site atual da {{empresa}}! A questão não é só ter uma página, mas garantir que quem entra consiga agendar ou chamar no WhatsApp em 2 cliques. Hoje quantos leads vocês recebem por lá?',
    whatsAppResponse: 'Perfeito! Ele está adaptado para o novo formato do Google ou foi feito há mais tempo?',
    callResponse: 'Que ótimo que já têm presença! Deixa eu te perguntar: vocês costumam mensurar quantas vendas vêm direto pelo site todo mês?',
    nextStep: 'Focar em taxa de conversão e velocidade de carregamento em vez de aparência estética.',
    followUps: createObjectionFollowUps('obj_9', 'Já tenho site'),
  },

  // 10. Meu site funciona bem
  {
    id: 'obj_10',
    code: 'SITE_FUNCIONA_BEM',
    title: 'Meu site funciona bem',
    keywords: ['funciona bem', 'está bom assim', 'atende', 'não preciso mudar'],
    category: 'necessidade',
    possibleMeaning: 'Satisfação aparente ou desconhecimento de oportunidades de melhoria.',
    whatNotToSay: 'Não contradiga o cliente dizendo que ele está errado.',
    diagnosticQuestion: 'Excelente! Se você pudesse melhorar um único detalhe nele para acelerar os atendimentos, o que seria?',
    shortResponse: 'Que bom, {{nome}}! Se ele já atende perfeitamente, não mexa no que está dando certo. Se precisar de uma auditoria gratuita no futuro, me avise!',
    consultativeResponse: 'Perfeito! Fico feliz que atenda. Só notei que no celular o botão de agendamento demora alguns segundos para carregar. Se quiser, te mando um print demonstrativo.',
    whatsAppResponse: 'Ótimo, {{nome}}! Parabéns pela estrutura. Fico à disposição caso um dia queiram fazer um teste A/B para comparar resultados.',
    callResponse: 'Excelente. Se a máquina de vendas está rodando, maravilha! Foco em manter o crescimento da {{empresa}}.',
    nextStep: 'Respeitar a satisfação e plantar semente para comparativo futuro.',
    followUps: createObjectionFollowUps('obj_10', 'Site funciona bem'),
  },

  // 11. Não preciso de site
  {
    id: 'obj_11',
    code: 'NAO_PRECISO_SITE',
    title: 'Não preciso de site / Vendo só pelo Instagram/WhatsApp',
    keywords: ['não preciso', 'vendo no instagram', 'só whatsapp', 'boca a boca'],
    category: 'necessidade',
    possibleMeaning: 'Dependência de canais sociais sem perceber o tráfego de busca no Google.',
    whatNotToSay: 'Não diga que quem não tem site vai falir.',
    diagnosticQuestion: 'Vocês hoje vendem mais por indicação ou pelas redes sociais?',
    shortResponse: 'Entendo, {{nome}}! Instagram e WhatsApp são incríveis. O site funciona como a vitrine no Google para quem pesquisa pelo seu serviço na sua cidade.',
    consultativeResponse: 'Muitos negócios no seu nicho vendem muito pelo WhatsApp. A vantagem de uma página rápida é filtrar curiosos e enviar o cliente já pronto para comprar direto no seu chat.',
    whatsAppResponse: 'Faz sentido! Quando alguém procura pelo seu serviço no Google, onde você prefere que eles cliquem para encontrar a {{empresa}}?',
    callResponse: 'Compreendo, {{nome}}. O boca a boca é forte. Mas já pensou em captar quem não te conhece ainda mas procura no Google agora?',
    nextStep: 'Explicar o papel do site como acelerador do próprio WhatsApp/Instagram.',
    followUps: createObjectionFollowUps('obj_11', 'Não preciso de site'),
  },

  // 12. Não acredito que isso vá trazer clientes
  {
    id: 'obj_12',
    code: 'NAO_ACREDITO_EM_RESULTADO',
    title: 'Não acredito que isso traga clientes / Ceticismo',
    keywords: ['não acredito', 'não traz resultado', 'já tentei e não deu', 'ilusão'],
    category: 'confianca',
    possibleMeaning: 'Experiências ruins anteriores com profissionais que prometeram milagres e não entregaram.',
    whatNotToSay: 'Não prometa faturamento garantido ou números mágicos irreais.',
    diagnosticQuestion: 'Você já teve alguma experiência ruim anterior com isso na {{empresa}}?',
    shortResponse: 'Compreendo seu ceticismo, {{nome}}. Ter um site por ter não traz clientes mesmo; o que traz é posicionar a {{empresa}} onde as pessoas já estão buscando.',
    consultativeResponse: 'Faz todo sentido desconfiar, {{nome}}. O mercado está cheio de promessas vazias. Nossa proposta não é mágica: é colocar um botão direto no WhatsApp para quem pesquisa no Google pelo seu serviço.',
    whatsAppResponse: 'Entendo perfeitamente, {{nome}}. Por isso não cobramos valores astronômicos nem prometemos números que não controlamos.',
    callResponse: 'Total razão, {{nome}}. Se alguém te prometeu rios de dinheiro, fez errado. Nosso foco é puramente converter quem já pesquisa pelo seu setor.',
    nextStep: 'Mostrar transparência total e focar no mecanismo prático da conversão.',
    followUps: createObjectionFollowUps('obj_12', 'Ceticismo em resultados'),
  },

  // 13. Manda a proposta
  {
    id: 'obj_13',
    code: 'MANDA_A_PROPOSTA',
    title: 'Manda a proposta / Envia no WhatsApp',
    keywords: ['manda a proposta', 'envia a proposta', 'manda pdf', 'me manda o arquivo'],
    category: 'processo',
    possibleMeaning: 'Forma rápida de encerrar a conversa ou interesse real que precisa de dados para avaliar.',
    whatNotToSay: 'Não envie um arquivo genérico de 30 páginas sem entender a dor do cliente.',
    diagnosticQuestion: 'Consigo sim! Antes, só quero evitar te mandar algo que não tenha relação com o que você precisa: posso confirmar 2 coisas rápidas?',
    shortResponse: 'Com certeza, {{nome}}! Para eu te mandar a proposta exata: o foco principal de vocês é {{problema}} ou tem outro ponto?',
    consultativeResponse: 'Consigo te enviar em minutos, {{nome}}. Para montar com o escopo sob medida da {{empresa}}, só me confirma se o prazo ideal de vocês é para este mês.',
    whatsAppResponse: 'Perfeito, {{nome}}! Já estou estruturando. Só me dá um ok se o objetivo principal for resolver {{problema}}!',
    callResponse: 'Com certeza. Te mando sim. Só me confirma se você prefere um resumo pelo WhatsApp ou em PDF?',
    nextStep: 'Fazer micro-qualificação e enviar proposta concisa e personalizada.',
    followUps: createObjectionFollowUps('obj_13', 'Manda proposta'),
  },

  // 14. Manda o preço / Quanto custa
  {
    id: 'obj_14',
    code: 'MANDA_O_PRECO',
    title: 'Manda o preço / Só quero saber o valor',
    keywords: ['preço', 'preco', 'quanto custa', 'qual o valor', 'tabela de preço'],
    category: 'preco',
    possibleMeaning: 'Curiosidade direta, comparação rápida de preços ou pressa.',
    whatNotToSay: 'Não fique enrolando por 10 mensagens sem responder ou cobrando taxa para falar o preço.',
    diagnosticQuestion: 'Claro! Projetos desse tipo costumam ficar na faixa de {{preco_ancora}}, mas para a {{empresa}} estruturamos em {{preco}}. O que acha desse valor?',
    shortResponse: 'O investimento para a {{empresa}} fica em {{preco}} à vista ou parcelado. Quer ver o que está incluso?',
    consultativeResponse: 'Com certeza, {{nome}}! Dependendo do escopo, varia de {{preco_ancora}} a {{preco}}. Para a estrutura que desenhei para a {{empresa}}, o valor exato fica em {{preco}}.',
    whatsAppResponse: 'O valor fechado para este escopo fica em {{preco}}, {{nome}}. Posso te detalhar os entregáveis?',
    callResponse: 'Sem rodeios, {{nome}}: o investimento é {{preco}}. Cabe no que você tinha em mente?',
    nextStep: 'Informar o valor ancorado e detalhar o escopo na sequência.',
    followUps: createObjectionFollowUps('obj_14', 'Manda preço'),
  },

  // 15. Só quero saber quanto custa
  {
    id: 'obj_15',
    code: 'SO_QUERO_SABER_CUSTO',
    title: 'Só quero saber quanto custa (sem conversa)',
    keywords: ['só o valor', 'apenas preco', 'diz o preco logo'],
    category: 'preco',
    possibleMeaning: 'Pressa ou triagem puramente financeira.',
    whatNotToSay: 'Não seja agressivo nem responda apenas um número seco sem contexto.',
    diagnosticQuestion: 'O valor exato para o modelo da {{empresa}} é {{preco}}. Quer que eu te envie o protótipo correspondente?',
    shortResponse: 'Direto ao ponto, {{nome}}: {{preco}} já com configuração e entrega completa.',
    consultativeResponse: 'O valor é {{preco}}, {{nome}}. Desenvolvemos a estrutura completa com entrega em [PRAZO]. Se quiser ver a prévia, é só avisar!',
    whatsAppResponse: 'Fica exatamente {{preco}}, {{nome}}. Tudo incluso.',
    callResponse: 'O projeto completo fica em {{preco}}. O que você acha desse número?',
    nextStep: 'Responder o preço diretamente e abrir porta para demonstração.',
    followUps: createObjectionFollowUps('obj_15', 'Só quanto custa'),
  },

  // 16. Não quero pagar antes
  {
    id: 'obj_16',
    code: 'NAO_PAGAR_ANTES',
    title: 'Não quero pagar antes / Insegurança no adiantamento',
    keywords: ['pagar antes', 'não pago antes', 'só pago depois', 'adiantado não'],
    category: 'confianca',
    possibleMeaning: 'Medo de golpe ou de receber trabalho incompleto.',
    whatNotToSay: 'Não acuse o cliente de desconfiança injustificada.',
    diagnosticQuestion: 'Compreendo! Se você aprovar o modelo primeiro e pagar apenas após ver a versão final pronta, fica seguro para você?',
    shortResponse: 'Entendo perfeitamente, {{nome}}! Para sua segurança, você avalia e aprova a estrutura antes de liquidar o pagamento.',
    consultativeResponse: 'Faz todo sentido, {{nome}}. O mercado tem muita insegurança. Podemos combinar o seguinte: nós montamos o projeto, você valida tudo no ar e realiza o pagamento após a sua aprovação final.',
    whatsAppResponse: 'Perfeito, {{nome}}! Trabalhamos com aprovação prévia exatamente para você não ter nenhum risco.',
    callResponse: 'Totalmente justo, {{nome}}. Você só paga depois de ver o projeto pronto e aprovado pela sua equipe.',
    nextStep: 'Oferecer modelo comercial de aprovação prévia sem risco para o cliente.',
    followUps: createObjectionFollowUps('obj_16', 'Não pagar antes'),
  },

  // 17. Quero pagar depois
  {
    id: 'obj_17',
    code: 'QUERO_PAGAR_DEPOIS',
    title: 'Quero pagar depois / Pós-entrega',
    keywords: ['pagar depois', 'pago quando terminar', 'depois de pronto'],
    category: 'confianca',
    possibleMeaning: 'Garantia de recebimento do escopo contratado.',
    whatNotToSay: 'Não recuse bruscamente sem propor termos combinados.',
    diagnosticQuestion: 'Combinado! Você aprova a entrega final e faz a liquidação na aprovação. Podemos fechar assim?',
    shortResponse: 'Perfeito, {{nome}}! Fechamos o escopo, você aprova no ar e efetua o pagamento na entrega.',
    consultativeResponse: 'Sem problemas, {{nome}}. Nossa prioridade é você ficar 100% satisfeito com o resultado. Aprovou, liquidou.',
    whatsAppResponse: 'Trato feito, {{nome}}! Vamos começar? Me passe os dados para o cadastro.',
    callResponse: 'Combinadíssimo, {{nome}}. Pagamento na aprovação final do projeto.',
    nextStep: 'Formalizar acordo de pagamento pós-aprovação.',
    followUps: createObjectionFollowUps('obj_17', 'Pagar depois'),
  },

  // 18. Preciso comparar
  {
    id: 'obj_18',
    code: 'PRECISO_COMPARAR',
    title: 'Preciso comparar opções',
    keywords: ['comparar', 'comparando', 'orçamentos', 'avaliando opções'],
    category: 'concorrencia',
    possibleMeaning: 'Pesquisa ativa de mercado e busca pelo melhor custo-benefício.',
    whatNotToSay: 'Não critique concorrentes nem se desespere dando descontos imediatos.',
    diagnosticQuestion: 'Com certeza! Ao comparar, quais critérios são mais importantes para a {{empresa}}: velocidade de entrega, preço ou suporte?',
    shortResponse: 'Excelente, comparar é o melhor caminho! Para te ajudar: o que você mais valoriza na entrega além do preço?',
    consultativeResponse: 'Perfeito, {{nome}}. Ao comparar com outras opções, só atente se eles entregam domínio, SSL e adaptação para celular inclusos, para não ter custos ocultos depois.',
    whatsAppResponse: 'Faz todo sentido! Se quiser, posso te mandar um checklist com os 5 pontos obrigatórios para cobrar de qualquer agência.',
    callResponse: 'Muito prudente, {{nome}}. Quando terminar as comparações, me avise para tirarmos qualquer dúvida.',
    nextStep: 'Enviar checklist de comparação técnica para se posicionar como consultor de confiança.',
    followUps: createObjectionFollowUps('obj_18', 'Preciso comparar'),
  },

  // 19. Vou pesquisar outras empresas
  {
    id: 'obj_19',
    code: 'PESQUISAR_OUTRAS',
    title: 'Vou pesquisar outras empresas',
    keywords: ['pesquisar outras', 'cotar com outros', 'outras empresas'],
    category: 'concorrencia',
    possibleMeaning: 'Necessidade de validar se a oferta está na média do mercado.',
    whatNotToSay: 'Não diga que os outros não prestam.',
    diagnosticQuestion: 'Totalmente compreensível. Quer que eu te envie os pontos-chave de atenção para a sua pesquisa?',
    shortResponse: 'Perfeito, {{nome}}! Pesquise com calma. Fico à disposição para tirar qualquer dúvida comparativa.',
    consultativeResponse: 'Excelente! Uma dica rápida: verifique se as outras empresas cobram mensalidade obrigatória ou se o projeto é 100% seu após a entrega.',
    whatsAppResponse: 'Boa pesquisa, {{nome}}! Se precisar de uma segunda opinião técnica sobre qualquer proposta que receber, pode me chamar sem compromisso.',
    callResponse: 'Muito bem, {{nome}}. Fique à vontade e nos falamos após suas cotações.',
    nextStep: 'Destacar o diferencial de não ter taxas ocultas nem mensalidades abusivas.',
    followUps: createObjectionFollowUps('obj_19', 'Pesquisar outras'),
  },

  // 20. Não tenho tempo agora
  {
    id: 'obj_20',
    code: 'SEM_TEMPO_AGORA',
    title: 'Não tenho tempo agora / Correria',
    keywords: ['sem tempo', 'muito corrido', 'falta de tempo', 'ocupadíssimo'],
    category: 'timing',
    possibleMeaning: 'Sobrecarga de trabalho na gestão.',
    whatNotToSay: 'Não insista em reuniões longas.',
    diagnosticQuestion: 'Entendo perfeitamente! Para você não gastar tempo: nós cuidamos de 100% da criação. Você só precisa de 2 minutos para aprovar. Te ajuda?',
    shortResponse: 'Sei como é, {{nome}}! Por isso fazemos todo o trabalho pesado. Você só precisa dar o ok no final.',
    consultativeResponse: 'Entendo sua rotina, {{nome}}. A vantagem do nosso formato é que você não precisa parar para escrever textos ou configurar nada. Nós entregamos pronto.',
    whatsAppResponse: 'Sem problemas, {{nome}}! Quando você tiver 1 minuto no final do dia, dá uma olhada na prévia.',
    callResponse: 'Compreendo a correria, {{nome}}. Não tomo mais seu tempo agora. Te mando um WhatsApp para você ver quando puder!',
    nextStep: 'Demonstrar que o serviço exige zero esforço de tempo do cliente.',
    followUps: createObjectionFollowUps('obj_20', 'Sem tempo'),
  },

  // 21. Estou ocupado / Me chama outro dia
  {
    id: 'obj_21',
    code: 'ME_CHAMA_OUTRO_DIA',
    title: 'Estou ocupado / Me chama outro dia',
    keywords: ['ocupado', 'chama outro dia', 'chama depois', 'fale comigo na semana que vem'],
    category: 'timing',
    possibleMeaning: 'Interrupção em momento inoportuno.',
    whatNotToSay: 'Não continue digitando mensagens longas imediatamente.',
    diagnosticQuestion: 'Perfeito! Qual dia e horário fica melhor: terça ou quinta-feira?',
    shortResponse: 'Combinado, {{nome}}! Te chamo na [DIA_SUGERIDO]. Bom trabalho por aí!',
    consultativeResponse: 'Entendido! Te procuro na [DIA_SUGERIDO] pela manhã. Um abraço!',
    whatsAppResponse: 'Perfeito! Anotei aqui para te chamar na [DIA_SUGERIDO]. Abraços!',
    callResponse: 'Perfeito, desculpe a interrupção. Te chamo na [DIA_SUGERIDO]. Até lá!',
    nextStep: 'Agendar lembrete exato e entrar em contato no dia combinado.',
    followUps: createObjectionFollowUps('obj_21', 'Me chama outro dia'),
  },

  // 22. Conheço alguém que faz mais barato
  {
    id: 'obj_22',
    code: 'CONHECO_MAIS_BARATO',
    title: 'Conheço alguém que faz mais barato / Sobrinho',
    keywords: ['mais barato', 'conheço quem faz', 'meu amigo faz por', 'muito mais em conta'],
    category: 'preco',
    possibleMeaning: 'Tentativa de barganha ou comparação com amadores.',
    whatNotToSay: 'Não menospreze a pessoa indicada pelo cliente.',
    diagnosticQuestion: 'Entendo! Essa pessoa entrega o projeto com carregamento rápido e otimização para celular pronta ou apenas o layout básico?',
    shortResponse: 'Compreendo, {{nome}}! O mercado tem opções de todos os preços. Nosso diferencial é entregar uma estrutura focada em conversão que não te dê dor de cabeça técnica.',
    consultativeResponse: 'Faz sentido, {{nome}}. Muitas vezes o barato sai caro quando a página fica lenta ou sai do ar e não tem suporte. Nosso foco é segurança e resultado comercial.',
    whatsAppResponse: 'Entendido! Se em algum momento você quiser comparar a velocidade e a conversão das duas opções, estou à disposição.',
    callResponse: 'Perfeito, {{nome}}. Se essa pessoa te atender com segurança, maravilha! Se precisar de padrão profissional, conte comigo.',
    nextStep: 'Destacar confiabilidade, velocidade e suporte sem entrar em leilão de preços.',
    followUps: createObjectionFollowUps('obj_22', 'Mais barato'),
  },

  // 23. Vou fazer sozinho
  {
    id: 'obj_23',
    code: 'VOU_FAZER_SOZINHO',
    title: 'Vou fazer sozinho',
    keywords: ['fazer sozinho', 'eu mesmo faco', 'vou montar', 'eu me viro'],
    category: 'processo',
    possibleMeaning: 'Desejo de economizar sem mensurar o custo do próprio tempo.',
    whatNotToSay: 'Não zombe da capacidade técnica do cliente.',
    diagnosticQuestion: 'Muito bacana! Você já tem facilidade com ferramentas de código/design ou vai aprender do zero?',
    shortResponse: 'Excelente iniciativa, {{nome}}! Se precisar de alguma dica de configuração de domínio ou pixel, pode me chamar.',
    consultativeResponse: 'Entendo, {{nome}}! Fazer sozinho é possível, mas costuma consumir de 20 a 40 horas do seu tempo de gestão. Nós entregamos pronto em poucos dias para você focar nas suas vendas.',
    whatsAppResponse: 'Boa sorte na montagem, {{nome}}! Se em algum momento travar em alguma configuração técnica, é só dar um toque.',
    callResponse: 'Bacana, {{nome}}! Se você tiver tempo para se dedicar, vai em frente. Se faltar tempo, nós resolvemos para você.',
    nextStep: 'Valorizar o tempo do gestor e deixar porta aberta.',
    followUps: createObjectionFollowUps('obj_23', 'Vou fazer sozinho'),
  },

  // 24. Vou usar IA / Canva / Wix / WordPress
  {
    id: 'obj_24',
    code: 'VOU_USAR_IA_WIX',
    title: 'Vou usar IA / Canva / Wix / WordPress',
    keywords: ['ia', 'inteligencia artificial', 'canva', 'wix', 'wordpress'],
    category: 'processo',
    possibleMeaning: 'Acredita que plataformas prontas resolvem a estratégia comercial sozinhas.',
    whatNotToSay: 'Não diga que essas ferramentas são lixo.',
    diagnosticQuestion: 'São ótimas ferramentas! A sua ideia é usar para fazer algo simples ou precisa de integração direta com seu WhatsApp e conversão rápida?',
    shortResponse: 'Ferramentas de IA são ótimas para rascunhos, {{nome}}. Nosso papel é transformar isso em uma máquina de conversão rápida e profissional.',
    consultativeResponse: 'O Wix e a IA ajudam muito, mas costumam criar páginas pesadas que demoram para abrir no 4G. Nós construímos código otimizado que carrega em menos de 1 segundo.',
    whatsAppResponse: 'São ferramentas práticas! O segredo está na copy e na velocidade de resposta. Se quiser comparar a velocidade depois, me avise!',
    callResponse: 'Com certeza, {{nome}}. A tecnologia ajuda, mas a estratégia de vendas é humana. Conte conosco se quiser acelerar.',
    nextStep: 'Focar em velocidade de carregamento no 4G e copy persuasiva.',
    followUps: createObjectionFollowUps('obj_24', 'Vou usar IA/Wix'),
  },

  // 25. Não confio em contratar pela internet
  {
    id: 'obj_25',
    code: 'NAO_CONFIO_INTERNET',
    title: 'Não confio em contratar alguém pela internet / Insegurança',
    keywords: ['não confio', 'medo de golpe', 'pela internet', 'desconfiado'],
    category: 'confianca',
    possibleMeaning: 'Trauma de compras digitais ou falta de referências físicas.',
    whatNotToSay: 'Não fique ofendido.',
    diagnosticQuestion: 'Total razão, {{nome}}! Com tantos golpes hoje, todo cuidado é pouco. Se fizermos uma chamada de vídeo rápida e você só pagar após ver o projeto funcionando, te deixaria tranquilo(a)?',
    shortResponse: 'Compreendo perfeitamente seu cuidado, {{nome}}! Podemos fazer uma chamada de vídeo e você só paga após aprovar a entrega.',
    consultativeResponse: 'Você está coberto de razão em ter cuidado, {{nome}}. Para sua total tranquilidade: emitimos contrato, você fala comigo em vídeo e só realiza qualquer pagamento após o projeto estar no ar e aprovado.',
    whatsAppResponse: 'Totalmente compreensível, {{nome}}! Vamos marcar 5 minutos de chamada de vídeo para você me conhecer pessoalmente?',
    callResponse: 'Eu faria o mesmo no seu lugar, {{nome}}. Transparência total: você só paga depois de ver o resultado.',
    nextStep: 'Oferecer chamada de vídeo e pagamento 100% pós-aprovação.',
    followUps: createObjectionFollowUps('obj_25', 'Não confio internet'),
  },

  // 26. Preciso de garantia
  {
    id: 'obj_26',
    code: 'PRECISO_DE_GARANTIA',
    title: 'Preciso de garantia / Risco zero',
    keywords: ['garantia', 'qual a garantia', 'risco', 'segurança'],
    category: 'confianca',
    possibleMeaning: 'Necessidade de salvaguarda contratual de funcionamento.',
    whatNotToSay: 'Não dê garantias falsas de faturamento que você não controla.',
    diagnosticQuestion: 'Qual tipo de garantia te traria total tranquilidade: garantia de funcionamento técnico ou garantia de satisfação no layout?',
    shortResponse: 'Nossa garantia é incondicional: se a versão final não ficar do seu agrado, você não tem obrigação de aprovar nem pagar.',
    consultativeResponse: 'Garantimos 100% de funcionamento técnico, velocidade e ajustes ilimitados no layout até ficar exatamente como você quer para a {{empresa}}.',
    whatsAppResponse: 'Garantia total de entrega e funcionamento, {{nome}}. Você só aprova quando estiver 100% satisfeito.',
    callResponse: 'Risco zero para você, {{nome}}: ajustes até aprovação total.',
    nextStep: 'Formalizar garantia de ajustes e aprovação prévia.',
    followUps: createObjectionFollowUps('obj_26', 'Preciso de garantia'),
  },

  // 27. Quanto tempo demora?
  {
    id: 'obj_27',
    code: 'QUANTO_TEMPO_DEMORA',
    title: 'Quanto tempo demora? / Prazos',
    keywords: ['tempo demora', 'prazo', 'quando entrega', 'quantos dias'],
    category: 'processo',
    possibleMeaning: 'Urgência ou planejamento de cronograma.',
    whatNotToSay: 'Não prometa prazos impossíveis de cumprir.',
    diagnosticQuestion: 'Entregamos a versão preliminar em [PRAZO_DIAS] dias. Qual é a data limite ideal para a {{empresa}}?',
    shortResponse: 'Entregamos a primeira versão em até [PRAZO_DIAS] dias úteis após o envio dos dados básicos.',
    consultativeResponse: 'Nosso processo é muito ágil: em [PRAZO_DIAS] dias você já tem a demonstração completa rodando no link de testes.',
    whatsAppResponse: 'Em média [PRAZO_DIAS] dias, {{nome}}! Rápido e sem burocracia.',
    callResponse: 'Prazo padrão de [PRAZO_DIAS] dias. Se tiver urgência, conseguimos priorizar para você.',
    nextStep: 'Confirmar prazo e acordar cronograma.',
    followUps: createObjectionFollowUps('obj_27', 'Quanto tempo demora'),
  },

  // 28. Você já fez isso para quem? / Sem cases
  {
    id: 'obj_28',
    code: 'QUERO_VER_TRABALHOS',
    title: 'Você já fez isso para quem? / Quero ver trabalhos anteriores',
    keywords: ['para quem fez', 'cases', 'trabalhos anteriores', 'portfólio', 'clientes atendidos'],
    category: 'autoridade',
    possibleMeaning: 'Busca por prova social para reduzir incerteza.',
    whatNotToSay: 'NUNCA invente clientes, logos ou depoimentos falsos.',
    diagnosticQuestion: 'Como estamos abrindo uma condição especial de lançamento para o seu setor, prefiro te mostrar um projeto demonstrativo real feito sob medida para a {{empresa}}. Posso te enviar?',
    shortResponse: 'Em vez de te mostrar projetos genéricos de outros segmentos, montei um protótipo específico para a {{empresa}}. Posso te mandar?',
    consultativeResponse: 'Trabalho com transparência total: em vez de promessas de terceiros, preparei uma prévia personalizada para a sua empresa avaliar a qualidade técnica diretamente.',
    whatsAppResponse: 'Preparei um conceito exclusivo pensando na {{empresa}}, {{nome}}. Prefere ver algo genérico ou a solução da sua empresa na prática?',
    callResponse: 'Transparência em primeiro lugar, {{nome}}. Dá uma olhada no projeto demonstrativo que preparei para você e julgue pela qualidade.',
    nextStep: 'Enviar projeto demonstrativo sob medida como prova de competência.',
    followUps: createObjectionFollowUps('obj_28', 'Ver trabalhos anteriores'),
  },

  // 29. Pode fazer desconto?
  {
    id: 'obj_29',
    code: 'PODE_FAZER_DESCONTO',
    title: 'Pode fazer desconto? / Choro no preço',
    keywords: ['desconto', 'faz um desconto', 'tem desconto', 'melhora o preço'],
    category: 'preco',
    possibleMeaning: 'Hábito de negociar ou teste de flexibilidade comercial.',
    whatNotToSay: 'Não reduza o preço instantaneamente sem pedir nada em troca.',
    diagnosticQuestion: 'Para viabilizarmos um valor menor hoje, se fecharmos com pagamento à vista ou reduzirmos um módulo do escopo, te atenderia?',
    shortResponse: 'O valor de {{preco}} já está com a condição especial de lançamento aplicada. Para mexer no preço, precisaríamos enxugar o escopo.',
    consultativeResponse: 'Consigo manter {{preco}} e incluir [BONUS_OU_FACILIDADE] se formalizarmos ainda hoje. O que acha?',
    whatsAppResponse: 'Esse valor de {{preco}} já está no nosso melhor pacote promocional, {{nome}}! Consigo facilitar o parcelamento para você.',
    callResponse: 'Se eu conseguir um ajuste pontual de 10% para fechamento hoje, fechamos agora?',
    nextStep: 'Trocar concessão de preço por fechamento imediato ou ajuste de escopo.',
    followUps: createObjectionFollowUps('obj_29', 'Pode fazer desconto'),
  },

  // 30. Posso pagar parcelado?
  {
    id: 'obj_30',
    code: 'PAGAR_PARCELADO',
    title: 'Posso pagar parcelado? / Condições de prazo',
    keywords: ['parcelado', 'parcelar', 'em quantas vezes', 'cartão', 'vezes'],
    category: 'preco',
    possibleMeaning: 'Necessidade de fluxo de caixa diluído.',
    whatNotToSay: 'Não dificulte o parcelamento sem necessidade.',
    diagnosticQuestion: 'Com certeza! Você prefere parcelar em quantas vezes: 2x, 3x ou até 12x no cartão?',
    shortResponse: 'Sim, parcelamos em até 12x no cartão ou entrada + saldo na entrega.',
    consultativeResponse: 'Totalmente viável, {{nome}}! Conseguimos fazer em [CONDICAO_PARCELAMENTO] para ficar leve no fluxo de caixa.',
    whatsAppResponse: 'Sim, {{nome}}! Parcelamos no cartão em até 12x ou fazemos 50% de entrada e 50% na aprovação.',
    callResponse: 'Sim, facilitamos o parcelamento. Quantas parcelas ficam confortáveis para você?',
    nextStep: 'Apresentar tabela de parcelas e fechar.',
    followUps: createObjectionFollowUps('obj_30', 'Pagar parcelado'),
  },

  // 31. Quero começar depois / Próximo mês
  {
    id: 'obj_31',
    code: 'COMECAR_DEPOIS',
    title: 'Quero começar depois / Próximo mês',
    keywords: ['começar depois', 'proximo mes', 'mês que vem', 'depois das férias'],
    category: 'timing',
    possibleMeaning: 'Organização de agenda ou postergação.',
    whatNotToSay: 'Não pressione desesperadamente.',
    diagnosticQuestion: 'Perfeito! Se garantirmos as condições promocionais atuais e agendarmos o início para o dia 1º do próximo mês, fica bom para você?',
    shortResponse: 'Combinado! Podemos reservar a sua vaga na agenda de desenvolvimento para o início do próximo mês.',
    consultativeResponse: 'Faz todo sentido, {{nome}}. Para não perder a condição especial de {{preco}}, podemos formalizar a reserva e iniciamos na data que você preferir.',
    whatsAppResponse: 'Perfeito, {{nome}}! Vou colocar na agenda para o início do próximo mês e te mando um lembrete dias antes.',
    callResponse: 'Fechado, {{nome}}. Reservo sua vaga técnica para o mês que vem.',
    nextStep: 'Agendar data de início e garantir reserva.',
    followUps: createObjectionFollowUps('obj_31', 'Começar depois'),
  },

  // 32. Meu sócio não gostou
  {
    id: 'obj_32',
    code: 'SOCIO_NAO_GOSTOU',
    title: 'Meu sócio não gostou / Rejeição interna',
    keywords: ['sócio não gostou', 'socio reprovou', 'não aprovaram internamente'],
    category: 'autoridade',
    possibleMeaning: 'O sócio viu algo que não combinou ou não entendeu a proposta.',
    whatNotToSay: 'Não ataque o sócio.',
    diagnosticQuestion: 'Entendi! Ele comentou qual parte específica não combinou: visual, custo ou modelo de negócio?',
    shortResponse: 'Compreendo, {{nome}}. O que exatamente não agradou a ele? Conseguimos ajustar 100% da estrutura para alinhar com a visão dele.',
    consultativeResponse: 'Faz parte do processo! Como o projeto é sob medida, podemos reformular as cores, textos e disposições até atender perfeitamente à expectativa dos dois.',
    whatsAppResponse: 'Sem problemas, {{nome}}! Me diga o que ele pontuou que eu faço uma nova versão em minutos para ele avaliar.',
    callResponse: 'Totalmente normal, {{nome}}. O que ele gostaria de ver diferente? Ajustamos sem custo.',
    nextStep: 'Identificar as queixas do sócio e gerar versão alternativa.',
    followUps: createObjectionFollowUps('obj_32', 'Sócio não gostou'),
  },

  // 33. O responsável não está disponível
  {
    id: 'obj_33',
    code: 'RESPONSAVEL_INDISPONIVEL',
    title: 'O responsável não está disponível / Ausente',
    keywords: ['responsavel não está', 'viajou', 'em reuniao', 'indisponivel'],
    category: 'autoridade',
    possibleMeaning: 'Filtro de atendimento ou indisponibilidade temporária.',
    whatNotToSay: 'Não seja agressivo com quem está atendendo.',
    diagnosticQuestion: 'Obrigado por avisar! Ele costuma estar disponível em qual período do dia?',
    shortResponse: 'Obrigado pela informação! Qual é o melhor horário para eu retornar o contato?',
    consultativeResponse: 'Perfeito, agradeço pelo aviso. Posso te enviar um recado resumido para você deixar na mesa dele(a)?',
    whatsAppResponse: 'Obrigado! Vou tentar novamente amanhã pela manhã. Um abraço!',
    callResponse: 'Entendido. Retorno no período da tarde. Obrigado pela atenção!',
    nextStep: 'Registrar melhor horário de contato.',
    followUps: createObjectionFollowUps('obj_33', 'Responsável indisponível'),
  },

  // 34. Não quero mudar o que já funciona
  {
    id: 'obj_34',
    code: 'NAO_MUDAR_O_QUE_FUNCIONA',
    title: 'Não quero mudar o que já funciona',
    keywords: ['já funciona', 'não quero mudar', 'em time que está ganhando'],
    category: 'necessidade',
    possibleMeaning: 'Aversão ao risco de quebrar processos existentes.',
    whatNotToSay: 'Não force a ideia de que o que eles têm é obsoleto.',
    diagnosticQuestion: 'Totalmente de acordo! A ideia não é substituir o que funciona, mas criar um canal adicional de atração. Faz sentido?',
    shortResponse: 'Perfeito, {{nome}}! Time que está ganhando a gente reforça. Nossa solução funciona em paralelo sem interferir no seu fluxo atual.',
    consultativeResponse: 'Concordo plenamente. Nós não alteramos nada da sua operação atual; apenas colocamos uma porta de entrada extra para novos clientes que buscam no digital.',
    whatsAppResponse: 'Faz todo sentido! Se um dia quiser somar mais um canal sem alterar o que já roda, é só chamar.',
    callResponse: 'Total razão, {{nome}}. Manter o que funciona é regra número um de gestão. Parabéns!',
    nextStep: 'Posicionar o projeto como canal complementar sem risco operacional.',
    followUps: createObjectionFollowUps('obj_34', 'Não mudar o que funciona'),
  },

  // 35. Não quero perder tempo com isso
  {
    id: 'obj_35',
    code: 'NAO_PERDER_TEMPO',
    title: 'Não quero perder tempo com isso',
    keywords: ['perder tempo', 'não tenho paciencia', 'sem saco'],
    category: 'timing',
    possibleMeaning: 'Fadiga de propostas e atendimento.',
    whatNotToSay: 'Não insista de forma cansativa.',
    diagnosticQuestion: 'Entendido, {{nome}}! Vou encerrar as mensagens por aqui para respeitar o seu tempo. Sucesso!',
    shortResponse: 'Sem problemas, {{nome}}! Agradeço pela franqueza. Contato encerrado por aqui.',
    consultativeResponse: 'Compreendo perfeitamente, {{nome}}. Não vou mais tomar seu tempo. Um abraço e bons negócios para a {{empresa}}!',
    whatsAppResponse: 'Tudo bem, {{nome}}! Obrigado pela atenção e sucesso!',
    callResponse: 'Entendido, {{nome}}. Desculpe o incômodo e um ótimo dia.',
    nextStep: 'Encerrar contato imediatamente (Do Not Contact).',
    followUps: createObjectionFollowUps('obj_35', 'Não perder tempo'),
  },

  // 36 a 45 - Objeções Adicionais Completas
  {
    id: 'obj_36',
    code: 'JA_ESTOU_DESENVOLVENDO_INTERNO',
    title: 'Já estou desenvolvendo internamente com minha equipe',
    keywords: ['desenvolvendo internamente', 'time interno', 'minha equipe está fazendo'],
    category: 'processo',
    possibleMeaning: 'Iniciativa interna já em andamento.',
    whatNotToSay: 'Não critique a equipe interna do cliente.',
    diagnosticQuestion: 'Que ótimo! Vocês já têm previsão de lançamento para este projeto interno?',
    shortResponse: 'Excelente, {{nome}}! Ter equipe própria agiliza muito. Se precisarem de apoio pontual em alguma integração, conte conosco.',
    consultativeResponse: 'Muito bacana! Se em algum momento a demanda interna sobrecarregar a equipe, ficamos à disposição para acelerar entregas pontuais.',
    whatsAppResponse: 'Ótimo saber! Bom desenvolvimento para a equipe da {{empresa}}!',
    callResponse: 'Excelente iniciativa, {{nome}}. Muito sucesso no lançamento interno!',
    nextStep: 'Parabenizar e manter canal aberto para transbordo.',
    followUps: createObjectionFollowUps('obj_36', 'Desenvolvimento interno'),
  },
  {
    id: 'obj_37',
    code: 'FAZ_POR_VALOR_X',
    title: 'Faz por R$ X? (Oferta abaixo da tabela)',
    keywords: ['faz por', 'pago tanto', 'te dou x', 'fecho por x'],
    category: 'preco',
    possibleMeaning: 'Tentativa de imposição de preço.',
    whatNotToSay: 'Não aceite de forma humilhante sem justificar o valor.',
    diagnosticQuestion: 'Para chegarmos próximo a esse valor, podemos ajustar o escopo para um modelo simplificado. Fica bom para você?',
    shortResponse: 'Por esse valor exato não conseguimos manter a entrega completa, mas consigo te oferecer a versão básica de entrada.',
    consultativeResponse: 'Entendo sua proposta, {{nome}}. Para viabilizar esse valor, podemos retirar [MODULO_SECUNDARIO] e manter a parte principal funcionando.',
    whatsAppResponse: 'Consigo chegar perto desse valor se fizermos a versão essencial sem os adicionais. O que acha?',
    callResponse: 'Podemos adaptar o escopo para caber nesse orçamento, {{nome}}.',
    nextStep: 'Adequar escopo ao orçamento oferecido.',
    followUps: createObjectionFollowUps('obj_37', 'Faz por X'),
  },
  {
    id: 'obj_38',
    code: 'QUERO_EXPERIMENTAR_PRIMEIRO',
    title: 'Quero experimentar primeiro sem compromisso',
    keywords: ['testar', 'experimentar', 'degustacao', 'sem compromisso'],
    category: 'confianca',
    possibleMeaning: 'Medo de errar na contratação.',
    whatNotToSay: 'Não prometa trabalho gratuito infinito.',
    diagnosticQuestion: 'Você pode testar a demonstração e o protótipo sem pagar nada antes de decidir. Posso te enviar?',
    shortResponse: 'Sim! Você navega e testa no protótipo antes de assinar qualquer contrato.',
    consultativeResponse: 'O teste prático é exatamente o protótipo personalizado que preparamos para você avaliar sem custo.',
    whatsAppResponse: 'Você pode testar o conceito na prática agora mesmo sem compromisso, {{nome}}.',
    callResponse: 'Com certeza. Você avalia o modelo funcionando antes de contratar.',
    nextStep: 'Enviar protótipo interativo para teste.',
    followUps: createObjectionFollowUps('obj_38', 'Testar primeiro'),
  },
  {
    id: 'obj_39',
    code: 'MEU_SETOR_E_DIFERENTE',
    title: 'Meu setor é muito específico / Diferente dos outros',
    keywords: ['setor especifico', 'nicho diferente', 'aqui é diferente', 'não funciona no meu ramo'],
    category: 'necessidade',
    possibleMeaning: 'Sensação de singularidade do nicho.',
    whatNotToSay: 'Não diga que todo negócio é igual.',
    diagnosticQuestion: 'Total razão! Qual é a particularidade mais importante do atendimento no seu setor que devemos respeitar?',
    shortResponse: 'Com certeza, {{nome}}! Por isso não usamos modelos prontos: adaptamos 100% da linguagem para o seu nicho.',
    consultativeResponse: 'Concordo plenamente. Cada segmento tem suas normas e tom de voz. Desenvolvemos o projeto respeitando as particularidades da {{empresa}}.',
    whatsAppResponse: 'Perfeito! Se puder me pontuar essas especificidades, adapto a demonstração agora mesmo.',
    callResponse: 'Total razão, {{nome}}. Por isso a personalização é obrigatória no nosso método.',
    nextStep: 'Colher peculiaridades do nicho e adaptar a copy.',
    followUps: createObjectionFollowUps('obj_39', 'Setor específico'),
  },
  {
    id: 'obj_40',
    code: 'JA_TIVE_PROBLEMA_COM_PRAZO',
    title: 'Já tive problema com agências que atrasaram meses',
    keywords: ['atraso', 'não entregam', 'prometem e somem', 'trauma de prazo'],
    category: 'confianca',
    possibleMeaning: 'Insegurança com prazos de entrega não cumpridos no passado.',
    whatNotToSay: 'Não prometa prazos mágicos sem penalidade contratual.',
    diagnosticQuestion: 'Compreendo perfeitamente o trauma! Se colocarmos prazo fixo em contrato com multa de atraso, te dá segurança?',
    shortResponse: 'Trabalhamos com cronograma rígido de [PRAZO_DIAS] dias documentado em termo de serviço.',
    consultativeResponse: 'Entendo sua frustração, {{nome}}. Nosso fluxo é industrializado exatamente para não depender de semanas de enrolação: [PRAZO_DIAS] dias úteis garantidos.',
    whatsAppResponse: 'Aqui o prazo é levado a sério: entregamos a versão preliminar em [PRAZO_DIAS] dias úteis.',
    callResponse: 'Total razão. Compromisso de prazo assumido em contrato.',
    nextStep: 'Documentar prazo formal com segurança.',
    followUps: createObjectionFollowUps('obj_40', 'Problema com prazo'),
  },
  {
    id: 'obj_41',
    code: 'PRECISO_DE_NOTA_FISCAL_CONTRATO',
    title: 'Preciso de Nota Fiscal e Contrato formal para a empresa',
    keywords: ['nota fiscal', 'nf', 'contrato formal', 'cnpj', 'juridico'],
    category: 'processo',
    possibleMeaning: 'Exigência de governança e compliance contábil.',
    whatNotToSay: 'Não tente fugir de emissão de NF ou formalização.',
    diagnosticQuestion: 'Emitimos Nota Fiscal e contrato formal para todos os projetos. Qual é a razão social para o cadastro?',
    shortResponse: 'Com certeza! Emitimos NF de serviços e contrato digital com validade jurídica.',
    consultativeResponse: '100% formalizado: emitimos Nota Fiscal eletrônica e contrato de prestação de serviços completo.',
    whatsAppResponse: 'Sim, {{nome}}! Tudo regularizado com NF e contrato digital.',
    callResponse: 'Com certeza, emitimos tudo formalmente.',
    nextStep: 'Coletar dados de faturamento e emitir termo.',
    followUps: createObjectionFollowUps('obj_41', 'Nota fiscal e contrato'),
  },
  {
    id: 'obj_42',
    code: 'NAO_TENHO_FOTOS_OU_TEXTOS',
    title: 'Não tenho fotos profissionais nem textos prontos',
    keywords: ['não tenho fotos', 'sem textos', 'sem material', 'sem imagens'],
    category: 'processo',
    possibleMeaning: 'Insegurança por não ter material gráfico profissional preparado.',
    whatNotToSay: 'Não mande o cliente se virar para contratar fotógrafo antes de começar.',
    diagnosticQuestion: 'Não se preocupe! Nós cuidamos da redação persuasiva e do banco de imagens profissionais para a {{empresa}}. Te ajuda?',
    shortResponse: 'Nós cuidamos de toda a redação dos textos e da seleção de imagens profissionais em alta definição.',
    consultativeResponse: 'Você não precisa se preocupar com isso, {{nome}}. Escrevemos a copy inteira e selecionamos imagens de alta qualidade para o seu segmento.',
    whatsAppResponse: 'Deixe isso com a gente! Criamos os textos e tratamos as imagens para você.',
    callResponse: 'Cuidamos de 100% da criação de conteúdo e imagens para a {{empresa}}.',
    nextStep: 'Eliminar atrito de criação de conteúdo.',
    followUps: createObjectionFollowUps('obj_42', 'Sem fotos ou textos'),
  },
  {
    id: 'obj_43',
    code: 'MEU_PUBLICO_NAO_USA_INTERNET',
    title: 'Meu público é mais velho / Não usa internet',
    keywords: ['publico idoso', 'não usa internet', 'clientes antigos', 'telefone fixo'],
    category: 'necessidade',
    possibleMeaning: 'Crença de que clientes mais velhos não utilizam WhatsApp ou buscas no Google.',
    whatNotToSay: 'Não ofenda a clientela do negócio.',
    diagnosticQuestion: 'Eles costumam usar WhatsApp para tirar dúvidas com vocês hoje?',
    shortResponse: 'Hoje quase 90% dos adultos utilizam WhatsApp diariamente. Nossa estrutura é focada em levá-los com 1 clique para o seu WhatsApp.',
    consultativeResponse: 'Muitas vezes os filhos ou parentes pesquisam no Google para eles. Estar fácil de encontrar ajuda toda a família a indicar a {{empresa}}.',
    whatsAppResponse: 'O projeto é simplificado exatamente para quem não tem familiaridade com internet conseguir chamar no WhatsApp em 1 clique.',
    callResponse: 'Perfeito, criamos algo ultra simples para que qualquer pessoa consiga entrar em contato.',
    nextStep: 'Focar na simplicidade extrema do botão de WhatsApp.',
    followUps: createObjectionFollowUps('obj_43', 'Público não usa internet'),
  },
  {
    id: 'obj_44',
    code: 'COMO_SEI_QUE_FUNCIONA',
    title: 'Como sei que vai funcionar para a minha empresa?',
    keywords: ['como sei', 'garantia de funcionamento', 'vai dar certo', 'funciona mesmo'],
    category: 'confianca',
    possibleMeaning: 'Incerteza sobre a aplicabilidade prática no negócio.',
    whatNotToSay: 'Não prometa resultados garantidos sem esforço.',
    diagnosticQuestion: 'Se estruturarmos uma versão simplificada para testar os primeiros contatos deste mês, você topa avaliar?',
    shortResponse: 'Você avalia e testa tudo na prática antes de formalizar qualquer compromisso.',
    consultativeResponse: 'Nosso método é focado em pessoas que já procuram ativamente pelo seu serviço na sua cidade. A demanda já existe; nós apenas direcionamos para você.',
    whatsAppResponse: 'O teste prático elimina qualquer dúvida: você acompanha os acessos e contatos gerados.',
    callResponse: 'Transparência total: você testa e valida no ar.',
    nextStep: 'Apresentar lógica de conversão da demanda existente.',
    followUps: createObjectionFollowUps('obj_44', 'Como sei que funciona'),
  },
  {
    id: 'obj_45',
    code: 'COMO_FUNCIONA_O_SUPORTE',
    title: 'Como funciona o suporte depois que entregar?',
    keywords: ['suporte', 'depois de pronto', 'se der problema', 'manutenção'],
    category: 'processo',
    possibleMeaning: 'Medo de ficar desamparado caso o site caia ou precise de ajustes.',
    whatNotToSay: 'Não diga que não dá suporte ou cobre valores abusivos por pequenas dúvidas.',
    diagnosticQuestion: 'Damos garantia e suporte direto pelo WhatsApp para qualquer dúvida técnica. Quer ver o que está incluso no pós-venda?',
    shortResponse: 'Você tem canal direto de suporte conosco no WhatsApp para qualquer manutenção ou ajuste!',
    consultativeResponse: 'Após o lançamento, você conta com suporte técnico prioritário e garantia contínua para manter tudo seguro e atualizado.',
    whatsAppResponse: 'Suporte humanizado direto no WhatsApp sempre que precisar, {{nome}}!',
    callResponse: 'Você tem nosso canal direto de WhatsApp para qualquer suporte sem intermediários.',
    nextStep: 'Apresentar termos de suporte e garantia contínua.',
    followUps: createObjectionFollowUps('obj_45', 'Como funciona o suporte'),
  },
];
