import { ScriptStepDefinition } from '../types/scripts';

/**
 * 23 ETAPAS COMPLETAS DO FLUXO "PROSPECÇÃO — PROBLEMA IDENTIFICADO"
 * Cada etapa com objetivo, estrutura, scripts e 6 a 8 follow-ups inteligentes.
 */
export const IDENTIFIED_PROBLEM_STEPS: ScriptStepDefinition[] = [
  // ETAPA 1 — Primeira mensagem
  {
    id: 'step_prob_1',
    prospectingType: 'identified_demand',
    stepNumber: 1,
    code: 'ETAPA_1_PRIMEIRA_MENSAGEM',
    stepName: 'Primeira Mensagem (Sem Venda Direta)',
    phase: 'ATENCAO',
    objective: 'Chamar atenção, demonstrar personalização real, criar curiosidade e descobrir se é funcionário ou responsável.',
    structure: 'CONTEXTO + OBSERVAÇÃO ESPECÍFICA + CURIOSIDADE + PERGUNTA SIMPLES',
    requiresClientResponse: true,
    defaultScript: 'Olá, {{nome}}. Encontrei a {{empresa}} e reparei em {{problema}}. Fiquei com uma dúvida rápida: você cuida dessa parte da empresa ou poderia me indicar quem é o responsável?',
    variationsByStyle: {
      consultivo: 'Olá, {{nome}}. Estava analisando a presença digital da {{empresa}} e notei um detalhe sobre {{problema}}. Você que lidera essa área ou me indicaria a pessoa responsável?',
      direto: 'Olá, {{nome}}. Encontrei a {{empresa}} e reparei em {{problema}}. É você quem cuida dessa parte na empresa?',
      casual: 'Oi {{nome}}, tudo bem? Vi o perfil da {{empresa}} e reparei em {{problema}}. Você que cuida dessa parte ou me indica quem trata disso por aí?',
      formal: 'Prezado(a) {{nome}}, encontrei a {{empresa}} e observei {{problema}}. Gostaria de confirmar se o(a) senhor(a) é o responsável por essa área ou se poderia me direcionar.',
    },
    followUps: [
      {
        id: 'fu_p1_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '4–8 horas',
        message: 'Olá, {{nome}}. Conseguiu ver minha mensagem anterior sobre a {{empresa}}?',
        objective: 'Relembrar de forma ultra-curta sem pressionar.',
        tone: 'Casual e respeitoso',
        condition: 'Primeira mensagem enviada sem resposta após 6h em horário comercial.',
        whenNotToUse: 'Se o cliente visualizou e está fora do horário comercial.',
      },
      {
        id: 'fu_p1_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Oi, {{nome}}. Só para confirmar se o WhatsApp da {{empresa}} ainda é o canal principal para falar com a equipe de vocês.',
        objective: 'Confirmar canal e reabrir diálogo de forma natural.',
        tone: 'Consultivo e breve',
        condition: 'Sem resposta após 24h da primeira mensagem.',
        whenNotToUse: 'Se houver resposta negativa anterior.',
      },
      {
        id: 'fu_p1_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas passando para não deixar a dúvida em aberto sobre quem cuida da parte de {{servico}} na {{empresa}}.',
        objective: 'Resgatar o foco no responsável.',
        tone: 'Profissional',
        condition: 'Sem retorno após 2 dias.',
        whenNotToUse: 'Se o contato for sabidamente do financeiro.',
      },
      {
        id: 'fu_p1_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Oi, {{nome}}. Imagino que a rotina na {{empresa}} esteja corrida. Se preferir, pode apenas me passar o e-mail ou nome de quem cuida de {{servico}}.',
        objective: 'Reduzir o esforço do contato para responder.',
        tone: 'Empático e prestativo',
        condition: 'Sem interação após 4 dias.',
        whenNotToUse: 'Se o contato já tiver confirmado que é o decisor.',
      },
      {
        id: 'fu_p1_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Olá, {{nome}}. Deixei uma observação rápida sobre {{problema}} na {{empresa}}. Vale a pena conversar sobre isso essa semana ou o foco de vocês agora é outro?',
        objective: 'Qualificar prioridade com pergunta de bifurcação.',
        tone: 'Consultivo e direto',
        condition: 'Sem retorno após 7 dias.',
        whenNotToUse: 'Se o lead solicitou parada de contato.',
      },
      {
        id: 'fu_p1_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Para não insistir sem necessidade: vocês já resolveram a questão de {{problema}} na {{empresa}} ou posso arquivar por aqui?',
        objective: 'Fechamento de loop respeitoso (quebra de pressão).',
        tone: 'Desapegado e profissional',
        condition: 'Última tentativa de contato antes de arquivar.',
        whenNotToUse: 'Após resposta do cliente.',
      },
    ],
  },

  // ETAPA 2 — Descobrir se é funcionário ou responsável
  {
    id: 'step_prob_2',
    prospectingType: 'identified_demand',
    stepNumber: 2,
    code: 'ETAPA_2_DESCOBRIR_RESPONSAVEL',
    stepName: 'Qualificação de Papel (Decisor vs Funcionário)',
    phase: 'QUALIFICACAO',
    objective: 'Identificar se o interlocutor tem poder de decisão ou atua no atendimento/operação.',
    structure: 'AGRADECIMENTO + PERGUNTA DE DIRECIONAMENTO',
    requiresClientResponse: true,
    defaultScript: 'Perfeito! Para eu te passar a informação da melhor forma: você é responsável pelas decisões da {{empresa}} ou atua na equipe de atendimento?',
    followUps: [
      {
        id: 'fu_p2_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Se for mais fácil, pode me dizer seu cargo na {{empresa}} que adapto o assunto para você.',
        objective: 'Descomplicar a resposta.',
        tone: 'Amigável',
        condition: 'Sem resposta após primeira confirmação de contato.',
        whenNotToUse: 'Se já souber o cargo formal.',
      },
      {
        id: 'fu_p2_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Apenas para garantir que não estou tomando o seu tempo indevidamente: quem costuma avaliar {{servico}} na {{empresa}}?',
        objective: 'Pedir direcionamento de forma respeitosa.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente for o sócio-proprietário.',
      },
      {
        id: 'fu_p2_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Posso te pedir uma ajuda rápida para saber com quem falo sobre a parte digital da {{empresa}}?',
        objective: 'Pedir auxílio simples.',
        tone: 'Humano e consultivo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se houver objeção de interesse.',
      },
      {
        id: 'fu_p2_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Sei que o dia a dia é corrido. Se puder só me indicar quem cuida de {{servico}}, eu falo direto com a pessoa.',
        objective: 'Facilitar encaminhamento.',
        tone: 'Direto e educado',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o interlocutor já se recusou.',
      },
      {
        id: 'fu_p2_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Última checagem rápida: existe alguém na {{empresa}} com quem eu possa alinhar esse ponto de {{problema}}?',
        objective: 'Penúltimo filtro de rota.',
        tone: 'Respeitoso',
        condition: '7 dias sem retorno.',
        whenNotToUse: 'Se o número for pessoal e não corporativo.',
      },
      {
        id: 'fu_p2_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar minhas tentativas por aqui para não te incomodar. Se em algum momento fizer sentido, estamos à disposição!',
        objective: 'Encerramento elegante.',
        tone: 'Cordel e desapegado',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se o cliente tiver pedido tempo.',
      },
    ],
  },

  // ETAPA 3 — Rota Funcionário
  {
    id: 'step_prob_3',
    prospectingType: 'identified_demand',
    stepNumber: 3,
    code: 'ETAPA_3_FUNCIONARIO',
    stepName: 'Rota Funcionário (Agradecimento e Contexto Breve)',
    phase: 'QUALIFICACAO',
    objective: 'Agradecer, explicar brevemente o motivo sem vender e pedir a indicação do responsável.',
    structure: 'AGRADECIMENTO + MOTIVO RESUMIDO + PEDIDO DE INDICAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'Perfeito, obrigado! Estou entrando em contato porque identifiquei {{problema}} na {{empresa}}. Quem normalmente cuida dessa parte por aí?',
    followUps: [
      {
        id: 'fu_p3_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Se for mais fácil, pode me passar apenas o primeiro nome ou o contato dele(a)?',
        objective: 'Obter nome ou WhatsApp do decisor.',
        tone: 'Prático e cortês',
        condition: 'Funcionário respondeu que não é ele mas não passou o contato.',
        whenNotToUse: 'Se o funcionário disser que é proibido passar contatos.',
      },
      {
        id: 'fu_p3_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Tudo bem? Consegue me dar essa força para falar com quem gerencia {{servico}} na {{empresa}}?',
        objective: 'Reforçar solicitação de indicação.',
        tone: 'Amigável',
        condition: '24h sem o contato do decisor.',
        whenNotToUse: 'Se o funcionário tiver informado que passará o recado.',
      },
      {
        id: 'fu_p3_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se preferir, posso te enviar um texto de 2 linhas para você só repassar para o responsável da {{empresa}}.',
        objective: 'Disponibilizar texto pronto para encaminhamento interno.',
        tone: 'Prestativo',
        condition: '48h sem dados do responsável.',
        whenNotToUse: 'Se já estiver em contato com o responsável.',
      },
      {
        id: 'fu_p3_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Chegou a comentar com o responsável sobre {{problema}} ou não teve oportunidade?',
        objective: 'Verificar status do repasse interno.',
        tone: 'Tranquilo',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se não tiver havido promessa de repasse.',
      },
      {
        id: 'fu_p3_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para não deixar pendente: vocês têm alguém dedicado a {{servico}} ou essa parte fica terceirizada?',
        objective: 'Entender estrutura de decisão.',
        tone: 'Consultivo',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se o contato for agressivo.',
      },
      {
        id: 'fu_p3_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Sem problemas! Vou encerrar as mensagens por aqui. Agradeço muito pela sua atenção!',
        objective: 'Fechamento de loop limpo.',
        tone: 'Educado',
        condition: '14 dias sem indicação.',
        whenNotToUse: 'Se houver resposta positiva recente.',
      },
    ],
  },

  // ETAPA 4 — Encaminhamento para responsável
  {
    id: 'step_prob_4',
    prospectingType: 'identified_demand',
    stepNumber: 4,
    code: 'ETAPA_4_ENCAMINHAMENTO',
    stepName: 'Encaminhamento & Facilitação de Ponte',
    phase: 'QUALIFICACAO',
    objective: 'Facilitar a ponte para o responsável com mensagem pronta e profissional.',
    structure: 'PONTE FACILITADA + CONFIRMAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'Muito obrigado, {{nome}}! Se for mais prático para você, pode me passar o número direto dele(a) ou prefere que eu envie um resumo para você repassar internamente?',
    followUps: [
      {
        id: 'fu_p4_1',
        stepNumber: 1,
        intervalHours: 12,
        intervalText: '12 horas',
        message: 'Olá, {{nome}}. Conseguiu verificar o contato do responsável na {{empresa}}?',
        objective: 'Lembrança rápida.',
        tone: 'Cortês',
        condition: 'Após concordar em passar contato.',
        whenNotToUse: 'Se não houve acordo prévio.',
      },
      {
        id: 'fu_p4_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Oi, {{nome}}. Segue o resumo rápido se quiser apenas colar para o gestor: "Olá, um especialista em {{servico}} entrou em contato apontando uma melhoria em {{problema}} para a {{empresa}}."',
        objective: 'Entregar o texto mastigado.',
        tone: 'Prestativo',
        condition: '24h sem resposta.',
        whenNotToUse: 'Se o funcionário já forneceu o número direto.',
      },
      {
        id: 'fu_p4_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se o gestor conseguiu ver a observação.',
        objective: 'Checar follow-up interno.',
        tone: 'Consultivo',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o funcionário pediu para não mandar mais mensagens.',
      },
      {
        id: 'fu_p4_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Oi, {{nome}}. Se achar que esse não é o momento para a {{empresa}} ver isso, pode me avisar com tranquilidade!',
        objective: 'Retirar pressão e obter resposta binária.',
        tone: 'Desapegado',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se já houve resposta.',
      },
      {
        id: 'fu_p4_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Olá, {{nome}}. Tudo bem por aí? Passando só para confirmar se ainda faz sentido o contato com a gestão da {{empresa}}.',
        objective: 'Reativação semanal.',
        tone: 'Profissional',
        condition: '7 dias de espera.',
        whenNotToUse: 'Se o lead estiver desqualificado.',
      },
      {
        id: 'fu_p4_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Obrigado pelo suporte inicial! Estou arquivando o contato por aqui. Um abraço para toda a equipe da {{empresa}}.',
        objective: 'Encerramento definitivo.',
        tone: 'Amigável',
        condition: '14 dias sem desfecho.',
        whenNotToUse: 'Se o responsável tiver entrado em contato.',
      },
    ],
  },

  // ETAPA 5 — Responsável identificado (Microcompromisso)
  {
    id: 'step_prob_5',
    prospectingType: 'identified_demand',
    stepNumber: 5,
    code: 'ETAPA_5_RESPONSAVEL_IDENTIFICADO',
    stepName: 'Responsável Identificado (Microcompromisso)',
    phase: 'INTERACAO',
    objective: 'Criar microcompromisso e abertura sem despejar parede de texto.',
    structure: 'RECONHECIMENTO + MICROCOMPROMISSO + PERGUNTA DE ABERTURA',
    requiresClientResponse: true,
    defaultScript: 'Perfeito, {{nome}}! Posso te fazer uma pergunta rápida antes de te mostrar o motivo do contato?',
    variationsByStyle: {
      consultivo: 'Excelente, {{nome}}. Antes de te apresentar qualquer ponto, posso te fazer uma pergunta bem rápida sobre o momento atual da {{empresa}}?',
      direto: 'Ótimo, {{nome}}. Posso te fazer uma pergunta rápida sobre {{problema}} na {{empresa}}?',
      casual: 'Show, {{nome}}! Posso te mandar uma pergunta rápida sobre como vocês tratam essa parte hoje na {{empresa}}?',
      formal: 'Perfeito, prezado(a) {{nome}}. Gostaria de solicitar permissão para fazer uma breve pergunta sobre as operações da {{empresa}} antes de detalhar o motivo.',
    },
    followUps: [
      {
        id: 'fu_p5_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. Prometo que é super rápida, leva menos de 1 minuto.',
        objective: 'Reafirmar brevidade.',
        tone: 'Descontraído e objetivo',
        condition: 'Responsável visualizou pergunta de microcompromisso e não respondeu.',
        whenNotToUse: 'Fora do horário comercial.',
      },
      {
        id: 'fu_p5_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. A dúvida é simples: vocês já chegaram a planejar alguma melhoria para {{problema}} este ano?',
        objective: 'Adiantar a pergunta de forma objetiva caso ele prefira não responder ao microcompromisso.',
        tone: 'Consultivo',
        condition: '1 dia de silêncio do decisor.',
        whenNotToUse: 'Se o cliente tiver dito que não tem interesse.',
      },
      {
        id: 'fu_p5_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Sei que sua agenda como gestor(a) é apertada. Quando tiver 2 minutos, me avisa!',
        objective: 'Respeito à rotina do decisor.',
        tone: 'Empático',
        condition: '2 dias sem resposta.',
        whenNotToUse: 'Se o contato estiver bloqueado.',
      },
      {
        id: 'fu_p5_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Queria apenas te mostrar um detalhe prático que notei na {{empresa}} em relação a {{problema}}. Faz sentido para você dar uma olhada?',
        objective: 'Despertar curiosidade prática.',
        tone: 'Consultivo',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se houver recusa explícita.',
      },
      {
        id: 'fu_p5_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando apenas para checar se {{problema}} é um ponto que você quer avaliar agora ou prefere deixar para outro momento.',
        objective: 'Checagem de timing.',
        tone: 'Direto e profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se já foi marcado como sem resposta.',
      },
      {
        id: 'fu_p5_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Para não tomar mais seu tempo: vou arquivar o contato por aqui. Se precisar de algo em {{servico}}, é só chamar!',
        objective: 'Break-up message elegante.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta do decisor.',
        whenNotToUse: 'Se houve resposta recente.',
      },
    ],
  },

  // ETAPA 6 — Investigação
  {
    id: 'step_prob_6',
    prospectingType: 'identified_demand',
    stepNumber: 6,
    code: 'ETAPA_6_INVESTIGACAO',
    stepName: 'Investigação do Cenário Atual',
    phase: 'DIAGNOSTICO',
    objective: 'Entender como a empresa opera atualmente e o nível de prioridade.',
    structure: 'PERGUNTA ABERTA DE PROCESSO',
    requiresClientResponse: true,
    defaultScript: 'Como vocês fazem isso atualmente na {{empresa}}? Vocês já possuem alguém cuidando ativamente de {{servico}} ou essa parte fica em segundo plano?',
    diagnosticQuestions: [
      'Como vocês fazem isso atualmente?',
      'O que mais te incomoda no processo atual?',
      'Vocês já pensaram em melhorar essa parte?',
      'Isso acaba gerando alguma dificuldade para vocês?',
      'Se pudesse melhorar uma coisa nessa parte hoje, o que seria?',
      'Isso é uma prioridade agora ou algo que pretendem resolver mais para frente?',
    ],
    followUps: [
      {
        id: 'fu_p6_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Apenas para entender se vocês já têm uma rotina definida para isso ou se é algo mais pontual.',
        objective: 'Esclarecer objetivo da investigação.',
        tone: 'Consultivo',
        condition: 'Sem resposta à pergunta investigativa.',
        whenNotToUse: 'Se a resposta já foi enviada.',
      },
      {
        id: 'fu_p6_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Pergunto porque muitas empresas do setor de {{empresa}} costumam relatar dificuldades com {{problema}}.',
        objective: 'Normalizar o problema e criar identificação.',
        tone: 'Especialista',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente afirmou que não tem problemas.',
      },
      {
        id: 'fu_p6_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se puder resumir em uma frase: hoje essa área está 100% resolvida ou há espaço para melhoria?',
        objective: 'Tornar a resposta simples (opção binária).',
        tone: 'Direto e simpático',
        condition: '2 dias sem resposta.',
        whenNotToUse: 'Se houver irritação do cliente.',
      },
      {
        id: 'fu_p6_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para não perder o fio da meada sobre o cenário da {{empresa}}.',
        objective: 'Retomar conversa.',
        tone: 'Educado',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se já estiver arquivado.',
      },
      {
        id: 'fu_p6_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Imagino que esteja focado em outras demandas. Se quiser retomar essa conversa mês que vem, me avise!',
        objective: 'Oferecer saída honrosa.',
        tone: 'Respeitoso',
        condition: '7 dias sem resposta.',
        whenNotToUse: 'Se houver agendamento pendente.',
      },
      {
        id: 'fu_p6_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não tivemos retorno, vou pausar nossos follow-ups por aqui. Sucesso nos negócios da {{empresa}}!',
        objective: 'Encerramento de ciclo.',
        tone: 'Profissional',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se o lead tiver respondido recentemente.',
      },
    ],
  },

  // ETAPA 7 — Diagnóstico (Ponto A, B, C)
  {
    id: 'step_prob_7',
    prospectingType: 'identified_demand',
    stepNumber: 7,
    code: 'ETAPA_7_DIAGNOSTICO',
    stepName: 'Diagnóstico Estruturado (Ponto A / B / C)',
    phase: 'DIAGNOSTICO',
    objective: 'Identificar a situação atual (A), situação desejada (B) e consequência realista do estado atual (C).',
    structure: 'PONTO A + PONTO B + PONTO C + PERGUNTA DE VALIDAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'Entendi o cenário. Hoje {{problema}} (Ponto A), e o ideal seria {{beneficio}} (Ponto B), para evitar que potenciais clientes deixem de escolher a {{empresa}} (Ponto C). Se pudesse melhorar uma coisa nessa parte hoje, o que seria?',
    diagnosticPoints: {
      pointA: 'Situação atual: site sem agendamento direto, desatualizado ou presença fraca no Google.',
      pointB: 'Situação desejada: clientes encontram a empresa com facilidade e convertem no WhatsApp em segundos.',
      pointC: 'Consequência: clientes procuram outra opção ou desistem por atrito no primeiro contato.',
    },
    followUps: [
      {
        id: 'fu_p7_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Fez sentido esse ponto ou a realidade da {{empresa}} é diferente?',
        objective: 'Validar hipótese diagnóstica.',
        tone: 'Consultivo',
        condition: 'Diagnóstico enviado sem validação.',
        whenNotToUse: 'Se o cliente já tiver validado.',
      },
      {
        id: 'fu_p7_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Apenas para checar se o principal gargalo é realmente {{problema}} ou se há outro ponto mais urgente.',
        objective: 'Refinar prioridade.',
        tone: 'Especialista',
        condition: '24h sem resposta.',
        whenNotToUse: 'Se o lead demonstrou desinteresse.',
      },
      {
        id: 'fu_p7_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se quiser, posso te mandar um exemplo rápido de como outros negócios corrigiram esse ponto de forma simples.',
        objective: 'Oferecer valor prático.',
        tone: 'Prestativo',
        condition: '48h sem resposta.',
        whenNotToUse: 'Se já estiver na etapa de demonstração.',
      },
      {
        id: 'fu_p7_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Conseguimos avançar nessa análise ou prefere manter como está no momento?',
        objective: 'Solicitar decisão.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se o cliente estiver de férias.',
      },
      {
        id: 'fu_p7_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Imagino que esteja avaliando prioridades. Fico à disposição quando quiser destravar esse ponto na {{empresa}}.',
        objective: 'Manter porta aberta.',
        tone: 'Respeitoso',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se o lead foi encerrado.',
      },
      {
        id: 'fu_p7_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou congelar esse diagnóstico por aqui. Um abraço e ótimos resultados na {{empresa}}!',
        objective: 'Encerramento de fluxo.',
        tone: 'Cordial',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se o cliente respondeu.',
      },
    ],
  },

  // ETAPA 8 — Validação do problema
  {
    id: 'step_prob_8',
    prospectingType: 'identified_demand',
    stepNumber: 8,
    code: 'ETAPA_8_VALIDACAO_PROBLEMA',
    stepName: 'Validação do Problema & Prioridade',
    phase: 'VALIDACAO',
    objective: 'Confirmar se o problema identificado é uma dor real e prioritária para o gestor.',
    structure: 'CONFIRMAÇÃO DO IMPACTO + PERGUNTA DE PRIORIDADE',
    requiresClientResponse: true,
    defaultScript: 'Entendido. Isso hoje acaba gerando perda de tempo da equipe ou impacta diretamente nas novas vendas da {{empresa}}? Resolver isso é uma prioridade para este mês?',
    followUps: [
      {
        id: 'fu_p8_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Conseguiu refletir sobre esse impacto na {{empresa}}?',
        objective: 'Checar reflexão.',
        tone: 'Consultivo',
        condition: 'Sem resposta após pergunta de validação.',
        whenNotToUse: 'Se o cliente já validou a prioridade.',
      },
      {
        id: 'fu_p8_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Pergunto porque muitos gestores só percebem o volume de clientes perdidos quando olham o número de visitas que não chamam no WhatsApp.',
        objective: 'Sensibilização com dado realista.',
        tone: 'Especialista',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente for agressivo.',
      },
      {
        id: 'fu_p8_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se isso não for prioridade agora, me avise que eu ajusto o acompanhamento para uma data futura!',
        objective: 'Liberar pressão e qualificar timing.',
        tone: 'Desapegado e profissional',
        condition: '2 dias sem resposta.',
        whenNotToUse: 'Se o cliente tiver demonstrado urgência.',
      },
      {
        id: 'fu_p8_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se faz sentido mantermos essa conversa aberta.',
        objective: 'Checagem direta.',
        tone: 'Direto',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se o lead foi arquivado.',
      },
      {
        id: 'fu_p8_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se houve alguma mudança de cenário na {{empresa}} em relação a {{problema}}.',
        objective: 'Retomada semanal.',
        tone: 'Educado',
        condition: '7 dias de silêncio.',
        whenNotToUse: 'Se o cliente rejeitou.',
      },
      {
        id: 'fu_p8_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o contato para não ser inconveniente. Bons negócios!',
        objective: 'Fechamento elegante.',
        tone: 'Profissional',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se houver interação recente.',
      },
    ],
  },

  // ETAPA 9 — Apresentação da solução
  {
    id: 'step_prob_9',
    prospectingType: 'identified_demand',
    stepNumber: 9,
    code: 'ETAPA_9_APRESENTACAO_SOLUCAO',
    stepName: 'Apresentação Específica da Solução',
    phase: 'DEMONSTRACAO',
    objective: 'Mostrar apenas a solução relacionada ao problema identificado, sem despejar cardápio de serviços.',
    structure: 'RECONHECIMENTO + SOLUÇÃO ESPECÍFICA + BENEFÍCIO REALISTA + PERGUNTA DE SENTIDO',
    requiresClientResponse: true,
    defaultScript: 'Entendi perfeitamente. Pelo que você me explicou, acredito que o principal ponto seja resolver {{problema}}. Minha ideia para a {{empresa}} seria implementar {{servico}}, permitindo {{beneficio}}. Faz sentido para você?',
    followUps: [
      {
        id: 'fu_p9_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. O que achou dessa abordagem para a {{empresa}}?',
        objective: 'Pedir feedback imediato.',
        tone: 'Consultivo',
        condition: 'Solução apresentada sem retorno.',
        whenNotToUse: 'Fora de horário.',
      },
      {
        id: 'fu_p9_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu analisar se essa estrutura de {{servico}} atende o que você estava imaginando?',
        objective: 'Verificar aderência da solução.',
        tone: 'Profissional',
        condition: '24h sem retorno.',
        whenNotToUse: 'Se o cliente fez objeção de preço.',
      },
      {
        id: 'fu_p9_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se quiser, posso te mostrar um exemplo visual de 1 minuto para ficar bem claro como ficaria.',
        objective: 'Ponte para demonstração.',
        tone: 'Prestativo',
        condition: '48h sem resposta.',
        whenNotToUse: 'Se o cliente recusou a solução.',
      },
      {
        id: 'fu_p9_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Ficou alguma dúvida sobre como funcionaria o {{servico}} na prática?',
        objective: 'Sanar eventuais dúvidas ocultas.',
        tone: 'Acessível',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se o contato for inválido.',
      },
      {
        id: 'fu_p9_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para saber se ainda faz sentido falarmos sobre {{servico}} para a {{empresa}}.',
        objective: 'Checar timing.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se já estiver em negociação.',
      },
      {
        id: 'fu_p9_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar por aqui. Se decidir avançar no futuro, minhas portas continuam abertas!',
        objective: 'Fechamento final.',
        tone: 'Cordial',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se houver resposta positiva.',
      },
    ],
  },

  // ETAPA 10 — Pedido de autorização para mostrar exemplo
  {
    id: 'step_prob_10',
    prospectingType: 'identified_demand',
    stepNumber: 10,
    code: 'ETAPA_10_AUTORIZACAO_EXEMPLO',
    stepName: 'Pedido de Autorização para Enviar Exemplo',
    phase: 'DEMONSTRACAO',
    objective: 'Pedir permissão explícita antes de enviar a demonstração, aumentando o valor percebido.',
    structure: 'AVISO DE EXEMPLO PREPARADO + PEDIDO DE PERMISSÃO',
    requiresClientResponse: true,
    defaultScript: 'Eu preparei um exemplo pensando especificamente na {{empresa}} para você ver na prática. Se você quiser, posso te enviar agora e você me diz o que acha. Posso mandar?',
    followUps: [
      {
        id: 'fu_p10_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. É um link rápido para você ver direto no celular. Posso te encaminhar?',
        objective: 'Reforçar facilidade de visualização.',
        tone: 'Ágil',
        condition: 'Sem resposta ao pedido de envio.',
        whenNotToUse: 'Fora do horário.',
      },
      {
        id: 'fu_p10_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Ficou bem visual e objetivo, focado exatamente em {{problema}}. Me confirma se posso te mandar!',
        objective: 'Despertar curiosidade pelo visual.',
        tone: 'Animado e respeitoso',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente pediu para não mandar nada.',
      },
      {
        id: 'fu_p10_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Sem nenhum compromisso comercial, apenas para você ver o conceito aplicado à {{empresa}}. Posso enviar?',
        objective: 'Reduzir risco e compromisso.',
        tone: 'Tranquilo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente for reativo.',
      },
      {
        id: 'fu_p10_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se o momento estiver muito corrido, posso te mandar quando tiver mais tempo.',
        objective: 'Flexibilidade de agenda.',
        tone: 'Empático',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se lead estiver desqualificado.',
      },
      {
        id: 'fu_p10_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. O exemplo está pronto aqui. Ainda quer dar uma olhada esta semana?',
        objective: 'Retomada de oportunidade.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se houver recusa.',
      },
      {
        id: 'fu_p10_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não tive seu retorno, vou guardar o material por aqui. Sucesso à {{empresa}}!',
        objective: 'Encerramento de follow-up.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se o cliente responder.',
      },
    ],
  },

  // ETAPA 11 — Envio da demonstração (Sem cases falsos)
  {
    id: 'step_prob_11',
    prospectingType: 'identified_demand',
    stepNumber: 11,
    code: 'ETAPA_11_ENVIO_DEMONSTRACAO',
    stepName: 'Envio da Demonstração / Protótipo',
    phase: 'DEMONSTRACAO',
    objective: 'Enviar o exemplo personalizado / protótipo / auditoria sem criar cases ou números falsos.',
    structure: 'LINK DA DEMONSTRAÇÃO + DESTAQUE PRINCIPAL + PERGUNTA DE FEEDBACK INICIAL',
    requiresClientResponse: true,
    defaultScript: 'Aqui está o exemplo personalizado que estruturei para a {{empresa}}: [LINK_DA_DEMONSTRACAO]. Foquei especialmente em resolver {{problema}} e facilitar {{beneficio}}. Quando puder dar uma olhada, me diga o que achou!',
    followUps: [
      {
        id: 'fu_p11_1',
        stepNumber: 1,
        intervalHours: 12,
        intervalText: '12 horas',
        message: 'Oi, {{nome}}. Conseguiu abrir o link da demonstração no seu aparelho?',
        objective: 'Checar acesso técnico ao link.',
        tone: 'Prestativo',
        condition: 'Demonstração enviada sem confirmação de leitura.',
        whenNotToUse: 'Se o cliente já confirmou que abriu.',
      },
      {
        id: 'fu_p11_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Teve a oportunidade de ver o exemplo que preparei para a {{empresa}}?',
        objective: 'Cobrar feedback com suavidade.',
        tone: 'Consultivo',
        condition: '24h após envio da demo.',
        whenNotToUse: 'Se o cliente estiver digitando feedback.',
      },
      {
        id: 'fu_p11_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Gostou da disposição dos elementos ou acha que tem algo a ajustar para combinar melhor com a {{empresa}}?',
        objective: 'Conduzir para análise qualitativa.',
        tone: 'Especialista',
        condition: '2 dias sem feedback.',
        whenNotToUse: 'Se o cliente rejeitou o projeto.',
      },
      {
        id: 'fu_p11_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se preferir, posso te gravar um áudio ou vídeo de 30 segundos explicando os pontos principais do projeto.',
        objective: 'Oferecer mídia alternativa de consumo rápido.',
        tone: 'Prestativo',
        condition: '4 dias sem retorno da demo.',
        whenNotToUse: 'Se o cliente não aceita áudio.',
      },
      {
        id: 'fu_p11_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para saber se o conceito fez sentido para a {{empresa}} ou se devemos seguir por outro caminho.',
        objective: 'Qualificar interesse na demonstração.',
        tone: 'Direto e profissional',
        condition: '7 dias sem retorno.',
        whenNotToUse: 'Se o lead já deu feedback.',
      },
      {
        id: 'fu_p11_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou retirar a demonstração do ar para organizar os projetos ativos por aqui. Se quiser reativar no futuro, me avise!',
        objective: 'Escassez real e encerramento elegante.',
        tone: 'Profissional e desapegado',
        condition: '14 dias sem retorno após demo.',
        whenNotToUse: 'Se o cliente pediu mais tempo.',
      },
    ],
  },

  // ETAPA 12 — Perguntar o que gostou
  {
    id: 'step_prob_12',
    prospectingType: 'identified_demand',
    stepNumber: 12,
    code: 'ETAPA_12_PERGUNTAR_GOSTOU',
    stepName: 'Feedback Positivo (O que mais gostou)',
    phase: 'DEMONSTRACAO',
    objective: 'Estimular o cliente a verbalizar os pontos positivos da solução antes de entrar em detalhes técnicos.',
    structure: 'PERGUNTA QUALITATIVA ESPECÍFICA',
    requiresClientResponse: true,
    defaultScript: 'Excelente! Daquilo que você conseguiu ver no exemplo, o que você mais gostou na estrutura pensada para a {{empresa}}?',
    followUps: [
      {
        id: 'fu_p12_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. A parte visual ou a facilidade de contato foi o que mais te chamou atenção?',
        objective: 'Dar opções para facilitar a resposta.',
        tone: 'Consultivo',
        condition: 'Sem resposta à pergunta de feedback.',
        whenNotToUse: 'Se o cliente já respondeu.',
      },
      {
        id: 'fu_p12_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Pergunto para saber se estamos alinhados no posicionamento que você deseja para a {{empresa}}.',
        objective: 'Reforçar alinhamento de posicionamento.',
        tone: 'Profissional',
        condition: '1 dia sem retorno.',
        whenNotToUse: 'Se houver objeções.',
      },
      {
        id: 'fu_p12_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se quiser apenas me dizer se achou no caminho certo, já me ajuda bastante!',
        objective: 'Simplificar a interação.',
        tone: 'Amigável',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente pediu pausa.',
      },
      {
        id: 'fu_p12_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Podemos avançar para os próximos passos ou gostaria de ver alguma alteração antes?',
        objective: 'Provocar decisão de avanço.',
        tone: 'Direto',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se houver recusa.',
      },
      {
        id: 'fu_p12_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se faz sentido dar continuidade a esse projeto para a {{empresa}}.',
        objective: 'Checagem semanal de interesse.',
        tone: 'Respeitoso',
        condition: '7 dias sem retorno.',
        whenNotToUse: 'Se já estiver arquivado.',
      },
      {
        id: 'fu_p12_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar nosso contato por aqui para não te encher de mensagens. Abraços!',
        objective: 'Break-up limpo.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 13 — Perguntar o que gostaria de melhorar
  {
    id: 'step_prob_13',
    prospectingType: 'identified_demand',
    stepNumber: 13,
    code: 'ETAPA_13_PERGUNTAR_MELHORAR',
    stepName: 'Identificação de Ajustes & Alinhamento',
    phase: 'DEMONSTRACAO',
    objective: 'Identificar qualquer ponto de fricção ou detalhe que não combine com a empresa.',
    structure: 'PERGUNTA ABERTA DE AJUSTES',
    requiresClientResponse: true,
    defaultScript: 'E olhando para o que a {{empresa}} precisa hoje: tem alguma parte que você mudaria, alguma informação que gostaria de acrescentar ou algo que não combina tanto?',
    followUps: [
      {
        id: 'fu_p13_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Fique super à vontade para apontar qualquer ajuste de cores, textos ou serviços!',
        objective: 'Dar total liberdade de ajustes.',
        tone: 'Acolhedor',
        condition: 'Aguardando lista de ajustes.',
        whenNotToUse: 'Se o cliente já aprovou sem ajustes.',
      },
      {
        id: 'fu_p13_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Se tiver 100% alinhado, podemos já planejar a implementação oficial. O que acha?',
        objective: 'Ponte para proposta caso não haja ajustes.',
        tone: 'Prático',
        condition: '1 dia sem resposta de ajustes.',
        whenNotToUse: 'Se o cliente apontou dúvidas.',
      },
      {
        id: 'fu_p13_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Conseguiu pensar em alguma alteração ou o modelo atende perfeitamente?',
        objective: 'Confirmação de escopo.',
        tone: 'Consultivo',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o cliente pediu tempo.',
      },
      {
        id: 'fu_p13_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se quiser, podemos fazer os ajustes diretamente na versão final.',
        objective: 'Agilizar o processo.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se o cliente demonstrou insatisfação.',
      },
      {
        id: 'fu_p13_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se avançamos com a proposta comercial para a {{empresa}}.',
        objective: 'Checagem de avanço.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se o lead foi cancelado.',
      },
      {
        id: 'fu_p13_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Estou arquivando o projeto demonstrativo por aqui. Obrigado pela atenção e sucesso!',
        objective: 'Fechamento de loop.',
        tone: 'Cordel',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 14 — Ajustes
  {
    id: 'step_prob_14',
    prospectingType: 'identified_demand',
    stepNumber: 14,
    code: 'ETAPA_14_AJUSTES',
    stepName: 'Confirmação dos Ajustes Realizados',
    phase: 'DEMONSTRACAO',
    objective: 'Confirmar os ajustes solicitados e validar a versão final do conceito.',
    structure: 'CONFIRMAÇÃO DOS PONTOS + VALIDAÇÃO FINAL',
    requiresClientResponse: true,
    defaultScript: 'Perfeito, {{nome}}! Já incorporei os ajustes que você pediu: [LISTA_DE_AJUSTES]. Agora está 100% aderente ao que você imaginava para a {{empresa}}?',
    followUps: [
      {
        id: 'fu_p14_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Conseguiu ver a versão ajustada?',
        objective: 'Checar validação dos ajustes.',
        tone: 'Atencioso',
        condition: 'Ajustes enviados sem confirmação.',
        whenNotToUse: 'Se já validou.',
      },
      {
        id: 'fu_p14_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Ficou exatamente como você queria? Se sim, te passo as condições para colocarmos no ar.',
        objective: 'Conduzir para apresentação de proposta.',
        tone: 'Prático e motivador',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se houver nova solicitação de mudança.',
      },
      {
        id: 'fu_p14_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Falta algum detalhe ou podemos preparar o plano de lançamento oficial?',
        objective: 'Verificar prontidão para proposta.',
        tone: 'Consultivo',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o cliente estiver ausente.',
      },
      {
        id: 'fu_p14_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Podemos agendar a publicação do projeto esta semana?',
        objective: 'Estipular prazo de publicação.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se o projeto foi pausado.',
      },
      {
        id: 'fu_p14_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se reservo a agenda de desenvolvimento da {{empresa}} para os próximos dias.',
        objective: 'Garantir compromisso de cronograma.',
        tone: 'Profissional',
        condition: '7 dias sem retorno.',
        whenNotToUse: 'Se o cliente cancelou.',
      },
      {
        id: 'fu_p14_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o atendimento por enquanto. Qualquer novidade, estou à disposição!',
        objective: 'Fechamento elegante.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 15 — Apresentação da proposta
  {
    id: 'step_prob_15',
    prospectingType: 'identified_demand',
    stepNumber: 15,
    code: 'ETAPA_15_PROPOSTA',
    stepName: 'Apresentação Estruturada da Proposta',
    phase: 'PROPOSTA',
    objective: 'Resumir o problema, a solução e o que será entregue antes de entrar em números.',
    structure: 'RESUMO DO PROBLEMA + RESUMO DA SOLUÇÃO + ESCOPO DE ENTREGA + PERGUNTA DE CONFIRMAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'Excelente, {{nome}}! Para formalizar: nosso foco é eliminar {{problema}} na {{empresa}} e garantir {{beneficio}}. O projeto inclui: [ESCOPO_DO_SERVICO]. Tudo pronto para publicarmos em [PRAZO]. Posso te apresentar os valores e condições?',
    followUps: [
      {
        id: 'fu_p15_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. Posso te passar os valores e a condição especial que estruturei para a {{empresa}}?',
        objective: 'Pedir autorização de envio do valor.',
        tone: 'Objetivo',
        condition: 'Escopo apresentado sem liberação de preço.',
        whenNotToUse: 'Se o cliente já pediu o preço diretamente.',
      },
      {
        id: 'fu_p15_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu avaliar o escopo de entrega? Posso te encaminhar o investimento correspondente?',
        objective: 'Verificar alinhamento do escopo antes do preço.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se houver dúvidas sobre o escopo.',
      },
      {
        id: 'fu_p15_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Ficou alguma dúvida sobre o que está incluso no projeto da {{empresa}}?',
        objective: 'Sanar dúvidas de entregáveis.',
        tone: 'Consultivo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente pediu desconto.',
      },
      {
        id: 'fu_p15_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se quiser, te mando diretamente a tabela resumida com prazos e valores.',
        objective: 'Facilitar decisão.',
        tone: 'Prático',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se o cliente pediu pausa.',
      },
      {
        id: 'fu_p15_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se ainda pretendem rodar esse projeto para a {{empresa}} este mês.',
        objective: 'Checagem mensal de fechamento.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se já foi fechado.',
      },
      {
        id: 'fu_p15_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não tivemos retorno sobre a proposta, vou liberar a vaga de desenvolvimento na agenda. Um abraço!',
        objective: 'Encerramento com escassez real de agenda.',
        tone: 'Respeitoso e desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 16 — Ancoragem e contraste
  {
    id: 'step_prob_16',
    prospectingType: 'identified_demand',
    stepNumber: 16,
    code: 'ETAPA_16_ANCORAGEM_CONTRASTE',
    stepName: 'Ancoragem de Mercado & Contraste',
    phase: 'PROPOSTA',
    objective: 'Apresentar a referência de mercado (com responsabilidade) e contrastar com o valor de oportunidade.',
    structure: 'FAIXA DE MERCADO + JUSTIFICATIVA + VALOR DE OPORTUNIDADE',
    requiresClientResponse: true,
    defaultScript: 'Projetos completos desse nível de desenvolvimento, dependendo do escopo, costumam ficar no mercado na faixa de {{preco_ancora}}. Porém, para este projeto específico da {{empresa}}, estruturamos uma condição promocional de {{preco}}.',
    followUps: [
      {
        id: 'fu_p16_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. O que achou dessa condição que conseguimos viabilizar para a {{empresa}}?',
        objective: 'Verificar percepção do contraste.',
        tone: 'Consultivo',
        condition: 'Âncora enviada sem resposta imediata.',
        whenNotToUse: 'Se o cliente reclamou do preço.',
      },
      {
        id: 'fu_p16_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Essa condição cabe com tranquilidade no planejamento financeiro de vocês para este mês?',
        objective: 'Avaliar adequação orçamentária.',
        tone: 'Compreensivo e profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente fez contraproposta.',
      },
      {
        id: 'fu_p16_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Ficou alguma dúvida em relação ao retorno sobre o investimento para a {{empresa}}?',
        objective: 'Mudar foco para ROI.',
        tone: 'Especialista',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente pediu parcelamento.',
      },
      {
        id: 'fu_p16_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se precisar de alguma facilidade na forma de pagamento, me avise que posso analisar!',
        objective: 'Abrir porta para flexibilidade de pagamento.',
        tone: 'Prestativo',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o cliente aceitou o valor.',
      },
      {
        id: 'fu_p16_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se conseguimos manter essa condição especial ativa para a {{empresa}}.',
        objective: 'Preservar prazo da condição.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se o lead recusou formalmente.',
      },
      {
        id: 'fu_p16_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Estou expirando a condição especial da proposta. Se quiser retomar no futuro pelo valor padrão, é só me chamar!',
        objective: 'Fechamento e perda da condição promocional.',
        tone: 'Firme e educado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se o cliente responder.',
      },
    ],
  },

  // ETAPA 17 — Preço
  {
    id: 'step_prob_17',
    prospectingType: 'identified_demand',
    stepNumber: 17,
    code: 'ETAPA_17_PRECO',
    stepName: 'Apresentação Clara do Preço & Formas',
    phase: 'NEGOCIACAO',
    objective: 'Informar o valor líquido e as opções de pagamento de forma transparente e objetiva.',
    structure: 'VALOR LÍQUIDO + FORMAS DE PAGAMENTO + PERGUNTA DE APROVAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'O investimento total fica em {{preco}} à vista (ou condições parceladas). Podemos formalizar a contratação e iniciar a implementação?',
    followUps: [
      {
        id: 'fu_p17_1',
        stepNumber: 1,
        intervalHours: 12,
        intervalText: '12 horas',
        message: 'Oi, {{nome}}. Qual modalidade de pagamento fica mais conveniente para a {{empresa}}?',
        objective: 'Conduzir para escolha da modalidade.',
        tone: 'Prático',
        condition: 'Preço apresentado sem escolha de modalidade.',
        whenNotToUse: 'Se o cliente manifestou objeção.',
      },
      {
        id: 'fu_p17_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu avaliar com o time/sócio a questão do investimento?',
        objective: 'Checar alinhamento interno.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente for o único sócio.',
      },
      {
        id: 'fu_p17_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Tudo bem? Se o valor estiver pesado para pagamento imediato, posso parcelar para você.',
        objective: 'Oferecer alternativa de parcelamento.',
        tone: 'Flexível',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o cliente já aceitou à vista.',
      },
      {
        id: 'fu_p17_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. O que está impedindo de darmos o pontapé inicial neste projeto hoje?',
        objective: 'Identificar a objeção real que travou.',
        tone: 'Consultivo e direto',
        condition: '4 dias de silêncio pós-preço.',
        whenNotToUse: 'Se o cliente pediu prazo fixo.',
      },
      {
        id: 'fu_p17_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se priorizamos o lançamento da {{empresa}} para a próxima semana.',
        objective: 'Retomar fechamento.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se arquivado.',
      },
      {
        id: 'fu_p17_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o acompanhamento desta proposta. Sucesso nos negócios da {{empresa}}!',
        objective: 'Encerramento de ciclo pós-preço.',
        tone: 'Cordial',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 18 — Negociação
  {
    id: 'step_prob_18',
    prospectingType: 'identified_demand',
    stepNumber: 18,
    code: 'ETAPA_18_NEGOCIACAO',
    stepName: 'Negociação Consultiva & Ajuste de Termos',
    phase: 'NEGOCIACAO',
    objective: 'Tratar solicitações de desconto sem desvalorizar o serviço, ajustando prazos ou escopo.',
    structure: 'COMPREENSÃO + CONTRAPARTIDA + PROPOSTA DE ACORDO',
    requiresClientResponse: true,
    defaultScript: 'Entendo sua colocação, {{nome}}. Para viabilizarmos o fechamento ainda hoje sem comprometer a qualidade da entrega, podemos manter em {{preco}} com a condição especial de aprovação prévia. Fica bom para você?',
    followUps: [
      {
        id: 'fu_p18_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Essa condição atende o que você precisava para darmos o ok?',
        objective: 'Fechar o acordo negociado.',
        tone: 'Direto e seguro',
        condition: 'Proposta negociada aguardando aceite.',
        whenNotToUse: 'Se já aceitou.',
      },
      {
        id: 'fu_p18_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Posso reservar os termos negociados até o final da tarde de hoje?',
        objective: 'Criar limite temporal saudável.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente pediu prazo maior.',
      },
      {
        id: 'fu_p18_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Ficou pendente algum ponto contratual ou técnico para iniciarmos?',
        objective: 'Identificar travas burocráticas.',
        tone: 'Prestativo',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o cliente for pessoa física sem contrato.',
      },
      {
        id: 'fu_p18_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se preferir iniciar com um escopo menor para testar o resultado, também é possível!',
        objective: 'Oferecer MVP reduzido.',
        tone: 'Flexível',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o escopo já for mínimo.',
      },
      {
        id: 'fu_p18_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se cancelamos a negociação ou se retomamos a implementação.',
        objective: 'Pergunta de encerramento ou avanço.',
        tone: 'Firme e educado',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_p18_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Estou cancelando os termos negociados. Desejo sucesso para a {{empresa}}!',
        objective: 'Cancelamento formal da negociação.',
        tone: 'Profissional',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 19 — Fechamento
  {
    id: 'step_prob_19',
    prospectingType: 'identified_demand',
    stepNumber: 19,
    code: 'ETAPA_19_FECHAMENTO',
    stepName: 'Fechamento & Confirmação do Acordo',
    phase: 'FECHAMENTO',
    objective: 'Confirmar a decisão de compra e recolher os dados para formalização do projeto.',
    structure: 'PARABÉNS PELA DECISÃO + DADOS NECESSÁRIOS + PRÓXIMO PASSO',
    requiresClientResponse: true,
    defaultScript: 'Excelente decisão, {{nome}}! Vamos transformar {{problema}} em um canal forte de resultados para a {{empresa}}. Para gerarmos a ordem de serviço, você pode me confirmar: Razão Social/Nome, CNPJ/CPF e o e-mail para envio?',
    followUps: [
      {
        id: 'fu_p19_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. Assim que me passar os dados, já emito o termo e começamos o setup.',
        objective: 'Agilizar coleta de dados cadastrais.',
        tone: 'Ágil',
        condition: 'Fechamento aceito sem envio dos dados cadastrais.',
        whenNotToUse: 'Se os dados já foram enviados.',
      },
      {
        id: 'fu_p19_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Tudo pronto aqui para iniciarmos. Consegue me mandar os dados cadastrais hoje?',
        objective: 'Cobrar dados com brevidade.',
        tone: 'Profissional',
        condition: '1 dia sem os dados cadastrais.',
        whenNotToUse: 'Se o cliente estiver colhendo com a contabilidade.',
      },
      {
        id: 'fu_p19_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se preferir, pode me mandar apenas o CNPJ/CPF que eu puxo os demais dados cadastrais para facilitar!',
        objective: 'Reduzir esforço de cadastro.',
        tone: 'Prestativo',
        condition: '2 dias de silêncio pós-fechamento.',
        whenNotToUse: 'Se o cliente não quiser informar.',
      },
      {
        id: 'fu_p19_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Houve algum imprevisto com o início do projeto da {{empresa}}?',
        objective: 'Checar se surgiu alguma dúvida de última hora.',
        tone: 'Compreensivo',
        condition: '4 dias sem envio de dados.',
        whenNotToUse: 'Se o contrato já foi assinado.',
      },
      {
        id: 'fu_p19_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se mantemos a prioridade de entrega da {{empresa}} para este mês.',
        objective: 'Reafirmar compromisso de cronograma.',
        tone: 'Direto',
        condition: '7 dias sem avanço cadastral.',
        whenNotToUse: 'Se desistiu.',
      },
      {
        id: 'fu_p19_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não recebemos os dados, vou pausar a reserva do projeto. Qualquer coisa estou por aqui!',
        objective: 'Pausar formalização.',
        tone: 'Cordial',
        condition: '14 dias sem dados.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 20 — Pagamento
  {
    id: 'step_prob_20',
    prospectingType: 'identified_demand',
    stepNumber: 20,
    code: 'ETAPA_20_PAGAMENTO',
    stepName: 'Pagamento & Confirmação Financeira',
    phase: 'FECHAMENTO',
    objective: 'Enviar dados de pagamento e instruções de liquidação conforme o acordo comercial (aprovar primeiro, pagar depois se acordado).',
    structure: 'DADOS DE PAGAMENTO + PRAZO DE LIQUIDAÇÃO + INSTRUÇÕES DE INÍCIO',
    requiresClientResponse: true,
    defaultScript: 'Seguem os dados para liquidação do investimento de {{preco}}: [CHAVE_PIX_OU_DADOS_BANCARIOS]. Conforme combinamos, assim que confirmar o pagamento (ou aprovar o layout final), damos início ao cronograma oficial!',
    followUps: [
      {
        id: 'fu_p20_1',
        stepNumber: 1,
        intervalHours: 12,
        intervalText: '12 horas',
        message: 'Oi, {{nome}}. Conseguiu receber os dados de pagamento com sucesso?',
        objective: 'Confirmar recebimento das informações financeiras.',
        tone: 'Profissional',
        condition: 'Dados enviados sem confirmação.',
        whenNotToUse: 'Se comprovante já enviado.',
      },
      {
        id: 'fu_p20_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Assim que fizer o envio do comprovante, nosso time já inicia a configuração do ambiente!',
        objective: 'Estimular envio do comprovante.',
        tone: 'Motivador',
        condition: '1 dia após envio de dados.',
        whenNotToUse: 'Se o pagamento for pós-aprovação.',
      },
      {
        id: 'fu_p20_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Teve alguma dificuldade técnica com o pagamento ou prefere outro meio (cartão/boleto)?',
        objective: 'Oferecer meios alternativos de pagamento.',
        tone: 'Prestativo',
        condition: '2 dias sem liquidação.',
        whenNotToUse: 'Se o cliente avisou data de pagamento específica.',
      },
      {
        id: 'fu_p20_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para alinhar com o setor financeiro sobre a previsão de quitação do projeto.',
        objective: 'Alinhar previsão financeira.',
        tone: 'Cortês',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_p20_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para confirmar se mantemos o faturamento da {{empresa}} ativo para esta semana.',
        objective: 'Checagem semanal de quitação.',
        tone: 'Profissional',
        condition: '7 dias sem quitação.',
        whenNotToUse: 'Se liquidado.',
      },
      {
        id: 'fu_p20_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou cancelar a cobrança pendente para não gerar pendências financeiras. Um abraço!',
        objective: 'Cancelamento formal de cobrança.',
        tone: 'Tranquilo',
        condition: '14 dias sem quitação.',
        whenNotToUse: 'Se pago.',
      },
    ],
  },

  // ETAPA 21 — Início do projeto
  {
    id: 'step_prob_21',
    prospectingType: 'identified_demand',
    stepNumber: 21,
    code: 'ETAPA_21_INICIO_PROJETO',
    stepName: 'Onboarding & Início do Projeto',
    phase: 'POS_VENDA',
    objective: 'Alinhar prazos, recolher materiais necessários e iniciar a produção com excelência.',
    structure: 'BOAS-VINDAS + CRONOGRAMA DE ENTREGA + COLETA DE MATERIAIS',
    requiresClientResponse: true,
    defaultScript: 'Pagamento e cadastro confirmados com sucesso! Seja muito bem-vindo(a), {{nome}}. Nosso prazo de entrega da versão final é [DATA_DE_ENTREGA]. Para acelerarmos, você pode me enviar o logo em alta resolução e o número oficial de WhatsApp da {{empresa}}?',
    followUps: [
      {
        id: 'fu_p21_1',
        stepNumber: 1,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Oi, {{nome}}. Conseguiu separar o logo e os materiais da {{empresa}}?',
        objective: 'Cobrar materiais de produção.',
        tone: 'Prestativo',
        condition: 'Materiais pendentes de envio pelo cliente.',
        whenNotToUse: 'Se todos os materiais já foram recebidos.',
      },
      {
        id: 'fu_p21_2',
        stepNumber: 2,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Olá, {{nome}}. Se não tiver os arquivos em alta qualidade, pode me mandar as fotos que tiver que nós tratamos por aqui!',
        objective: 'Eliminar bloqueio por falta de fotos profissionais.',
        tone: 'Solícito',
        condition: '2 dias sem envio de materiais.',
        whenNotToUse: 'Se o cliente contratou sessão de fotos.',
      },
      {
        id: 'fu_p21_3',
        stepNumber: 3,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Oi, {{nome}}. Tudo bem? Apenas para não atrasarmos o cronograma de entrega da {{empresa}}.',
        objective: 'Garantir cumprimento do prazo de lançamento.',
        tone: 'Profissional',
        condition: '4 dias sem envio de materiais.',
        whenNotToUse: 'Se o cliente avisou que está viajando.',
      },
      {
        id: 'fu_p21_4',
        stepNumber: 4,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Olá, {{nome}}. Já avançamos com a estrutura base! Precisamos apenas do seu WhatsApp oficial para conectar as mensagens.',
        objective: 'Avisar progresso e pedir dado faltante.',
        tone: 'Animado',
        condition: '7 dias pós-onboarding.',
        whenNotToUse: 'Se já configurado.',
      },
      {
        id: 'fu_p21_5',
        stepNumber: 5,
        intervalHours: 240,
        intervalText: '10 dias',
        message: 'Oi, {{nome}}. Segue prévia do ambiente de desenvolvimento da {{empresa}} para você acompanhar!',
        objective: 'Manter cliente informado do progresso.',
        tone: 'Transparente',
        condition: 'Durante a fase de desenvolvimento.',
        whenNotToUse: 'Se já finalizado.',
      },
      {
        id: 'fu_p21_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Projeto 100% finalizado e publicado com sucesso! Vamos marcar um checklist rápido?',
        objective: 'Conclusão e entrega.',
        tone: 'Comemorativo',
        condition: 'No dia da entrega.',
        whenNotToUse: 'Se houver pendências técnicas.',
      },
    ],
  },

  // ETAPA 22 — Pós-venda
  {
    id: 'step_prob_22',
    prospectingType: 'identified_demand',
    stepNumber: 22,
    code: 'ETAPA_22_POS_VENDA',
    stepName: 'Acompanhamento de Resultados & Suporte',
    phase: 'POS_VENDA',
    objective: 'Acompanhar o funcionamento após o lançamento, garantir satisfação total e oferecer suporte ativo.',
    structure: 'CHECK-IN DE FUNCIONAMENTO + SATISFAÇÃO + SUPORTE',
    requiresClientResponse: true,
    defaultScript: 'Olá, {{nome}}! Passando para checar como estão os primeiros dias com a nova estrutura no ar. Tudo funcionando perfeitamente? Vocês já notaram novos contatos chegando?',
    followUps: [
      {
        id: 'fu_p22_1',
        stepNumber: 1,
        intervalHours: 72,
        intervalText: '3 dias',
        message: 'Oi, {{nome}}. Tudo certo com os botões de contato e o carregamento da página?',
        objective: 'Checagem técnica pós-lançamento.',
        tone: 'Cuidadoso',
        condition: '3 dias após publicação.',
        whenNotToUse: 'Se o cliente já deu feedback positivo.',
      },
      {
        id: 'fu_p22_2',
        stepNumber: 2,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Olá, {{nome}}. Completamos 1 semana no ar! Como a equipe tem sentido o volume de atendimentos?',
        objective: 'Avaliar impacto comercial na 1ª semana.',
        tone: 'Consultivo',
        condition: '7 dias pós-lançamento.',
        whenNotToUse: 'Se houver chamados de suporte abertos.',
      },
      {
        id: 'fu_p22_3',
        stepNumber: 3,
        intervalHours: 360,
        intervalText: '15 dias',
        message: 'Oi, {{nome}}. Passando para saber se precisa de algum ajuste ou atualização de informações nos materiais da {{empresa}}.',
        objective: 'Oferecer pequenos ajustes de manutenção.',
        tone: 'Prestativo',
        condition: '15 dias pós-lançamento.',
        whenNotToUse: 'Se o cliente não responde a contatos.',
      },
      {
        id: 'fu_p22_4',
        stepNumber: 4,
        intervalHours: 720,
        intervalText: '30 dias',
        message: 'Olá, {{nome}}. Fechamos o primeiro mês de operação! Gostaria de te parabenizar pela transformação da presença digital da {{empresa}}.',
        objective: 'Celebrar marco de 30 dias.',
        tone: 'Profissional e caloroso',
        condition: '30 dias pós-lançamento.',
        whenNotToUse: 'Se houve problemas graves não resolvidos.',
      },
      {
        id: 'fu_p22_5',
        stepNumber: 5,
        intervalHours: 1440,
        intervalText: '60 dias',
        message: 'Oi, {{nome}}. Tudo bem? Apenas para manter o canal de suporte aberto para o que a {{empresa}} precisar!',
        objective: 'Manter relacionamento a médio prazo.',
        tone: 'Amigável',
        condition: '60 dias pós-lançamento.',
        whenNotToUse: 'Se desativado.',
      },
      {
        id: 'fu_p22_6',
        stepNumber: 6,
        intervalHours: 2160,
        intervalText: '90 dias',
        message: 'Olá, {{nome}}. Checagem trimestral de saúde da presença digital da {{empresa}}. Tudo rodando 100%?',
        objective: 'Auditoria de 90 dias.',
        tone: 'Especialista',
        condition: '90 dias pós-lançamento.',
        whenNotToUse: 'Se não cliente.',
      },
    ],
  },

  // ETAPA 23 — Pedido de recomendação
  {
    id: 'step_prob_23',
    prospectingType: 'identified_demand',
    stepNumber: 23,
    code: 'ETAPA_23_RECOMENDACAO',
    stepName: 'Pedido Ético de Recomendação & Indicação',
    phase: 'RECOMENDACAO',
    objective: 'Pedir indicação de outros empresários parceiros somente após validar a satisfação real do cliente.',
    structure: 'VALIDAÇÃO DA SATISFAÇÃO + PEDIDO ÉTICO DE INDICAÇÃO + BENEFÍCIO',
    requiresClientResponse: true,
    defaultScript: 'Fico muito feliz que você tenha gostado do resultado na {{empresa}}, {{nome}}! Você conhece algum empresário parceiro ou amigo que também esteja precisando melhorar {{problema}} e que se beneficiaria dessa mesma solução?',
    followUps: [
      {
        id: 'fu_p23_1',
        stepNumber: 1,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Oi, {{nome}}. Se lembrar de alguém do seu círculo, pode apenas me passar o contato ou indicar nosso WhatsApp!',
        objective: 'Facilitar indicação sem pressão.',
        tone: 'Tranquilo',
        condition: 'Pedido de recomendação enviado.',
        whenNotToUse: 'Se o cliente já indicou.',
      },
      {
        id: 'fu_p23_2',
        stepNumber: 2,
        intervalHours: 72,
        intervalText: '3 dias',
        message: 'Olá, {{nome}}. Se for mais confortável, pode apenas mandar uma mensagem para ele(a) nos apresentando em grupo.',
        objective: 'Oferecer opção de introdução em grupo.',
        tone: 'Prestativo',
        condition: '3 dias sem resposta de indicação.',
        whenNotToUse: 'Se o cliente disse que não conhece ninguém.',
      },
      {
        id: 'fu_p23_3',
        stepNumber: 3,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Para indicações fechadas oferecemos uma condição especial de manutenção gratuita para a {{empresa}}!',
        objective: 'Oferecer incentivo de recompensa/crédito.',
        tone: 'Comercial elegante',
        condition: '7 dias pós-pedido.',
        whenNotToUse: 'Se o cliente não tiver interesse em programas de indicação.',
      },
      {
        id: 'fu_p23_4',
        stepNumber: 4,
        intervalHours: 360,
        intervalText: '15 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para agradecer novamente pela parceria e desejar excelentes vendas à {{empresa}}!',
        objective: 'Agradecimento e reforço de parceria.',
        tone: 'Caloroso',
        condition: '15 dias pós-indicação.',
        whenNotToUse: 'Se houver conflito.',
      },
      {
        id: 'fu_p23_5',
        stepNumber: 5,
        intervalHours: 720,
        intervalText: '30 dias',
        message: 'Oi, {{nome}}. Passando para checar se surgiu algum parceiro interessado em reformular a presença digital este mês.',
        objective: 'Checagem mensal de indicações.',
        tone: 'Descontraído',
        condition: '30 dias pós-indicação.',
        whenNotToUse: 'Se o cliente pediu para não tocar no assunto.',
      },
      {
        id: 'fu_p23_6',
        stepNumber: 6,
        intervalHours: 1440,
        intervalText: '60 dias',
        message: 'Olá, {{nome}}. Um abraço e conte sempre conosco para o crescimento contínuo da {{empresa}}!',
        objective: 'Encerramento de ciclo de pós-venda e indicações.',
        tone: 'Cordial',
        condition: '60 dias pós-indicação.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },
];
