import { ScriptStepDefinition } from '../types/scripts';

/**
 * 16 ETAPAS COMPLETAS DO FLUXO "CLIENTE DE ALTO POTENCIAL / OPORTUNIDADE LATENTE"
 * Para negócios que podem precisar de App, SaaS, Automação ou Sistema Personalizado.
 * Princípio: Não afirmar "você precisa de um app", mas sim investigar o processo atual.
 */
export const LATENT_OPPORTUNITY_STEPS: ScriptStepDefinition[] = [
  // ETAPA 1 — Primeira interação
  {
    id: 'lat_step_1',
    prospectingType: 'latent_opportunity',
    stepNumber: 1,
    code: 'LAT_1_PRIMEIRA_INTERACAO',
    stepName: 'Primeira Interação (Curiosidade sobre Processos)',
    phase: 'ATENCAO',
    objective: 'Chamar atenção de forma consultiva sem tentar vender app ou software diretamente.',
    structure: 'OBSERVAÇÃO OPERACIONAL + PERGUNTA DE DIRECIONAMENTO',
    requiresClientResponse: true,
    defaultScript: 'Olá, {{nome}}. Acompanho o crescimento da {{empresa}} no setor de {{niche}} e fiquei com uma dúvida rápida: é você quem cuida da parte de processos e sistemas internos por aí?',
    variationsByStyle: {
      consultivo: 'Olá, {{nome}}. Tenho acompanhado o volume de operações da {{empresa}} e fiquei com uma curiosidade profissional: você que gerencia a parte de tecnologia e processos internos?',
      direto: 'Olá, {{nome}}. Vi a operação da {{empresa}}. Quem é o responsável pela área de sistemas e automações na empresa?',
      casual: 'Oi, {{nome}}! Tudo bem? Vi a estrutura da {{empresa}} e fiquei curioso: você que toca a parte de automações e tecnologia por aí?',
      formal: 'Prezado(a) {{nome}}, acompanho a trajetória da {{empresa}} e gostaria de confirmar se o(a) senhor(a) responde pela gestão de sistemas e processos operacionais.',
    },
    followUps: [
      {
        id: 'fu_lat1_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '4–8 horas',
        message: 'Oi, {{nome}}. Conseguiu receber minha mensagem anterior sobre a {{empresa}}?',
        objective: 'Lembrete curto e respeitoso.',
        tone: 'Casual',
        condition: 'Sem resposta após primeira mensagem.',
        whenNotToUse: 'Fora do horário comercial.',
      },
      {
        id: 'fu_lat1_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Só para checar se este é o canal direto de gestão da {{empresa}}.',
        objective: 'Confirmar canal.',
        tone: 'Profissional',
        condition: '24h sem resposta.',
        whenNotToUse: 'Se número for incorreto.',
      },
      {
        id: 'fu_lat1_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. A pergunta é bem rápida sobre o fluxo de atendimento da {{empresa}}. Vale 1 minuto de conversa?',
        objective: 'Solicitar 1 minuto de atenção.',
        tone: 'Direto',
        condition: '48h sem retorno.',
        whenNotToUse: 'Se o cliente recusou.',
      },
      {
        id: 'fu_lat1_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Imagino a correria na operação da {{empresa}}. Se puder só me indicar com quem falo sobre processos, agradeço!',
        objective: 'Facilitar encaminhamento.',
        tone: 'Empático',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o lead for autônomo.',
      },
      {
        id: 'fu_lat1_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se a automação de fluxos na {{empresa}} é algo no radar de vocês para este trimestre.',
        objective: 'Qualificar timing e radar da empresa.',
        tone: 'Consultivo',
        condition: '7 dias sem interação.',
        whenNotToUse: 'Se desqualificado.',
      },
      {
        id: 'fu_lat1_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Para não insistir sem necessidade, vou arquivar por aqui. Sucesso nos negócios da {{empresa}}!',
        objective: 'Break-up elegante.',
        tone: 'Desapegado',
        condition: '14 dias de silêncio.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 2 — Descobrir responsável
  {
    id: 'lat_step_2',
    prospectingType: 'latent_opportunity',
    stepNumber: 2,
    code: 'LAT_2_DESCOBRIR_RESPONSAVEL',
    stepName: 'Identificação do Decisor de Tecnologia/Operação',
    phase: 'QUALIFICACAO',
    objective: 'Garantir que a conversa seja direcionada para quem tem autonomia de decisão operacional.',
    structure: 'CONFIRMAÇÃO DE PAPEL + PEDIDO DE PONTE',
    requiresClientResponse: true,
    defaultScript: 'Perfeito! Se você cuida da parte estratégica da {{empresa}}, posso te fazer uma pergunta rápida? Ou se houver um sócio/diretor de operações, quem você me indicaria?',
    followUps: [
      {
        id: 'fu_lat2_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Pode me dizer apenas se você lidera a área ou atua na equipe?',
        objective: 'Simplificar a resposta de papel.',
        tone: 'Amigável',
        condition: 'Sem resposta após qualificação de papel.',
        whenNotToUse: 'Se o perfil já tiver cargo evidente.',
      },
      {
        id: 'fu_lat2_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Apenas para direcionar o assunto técnico para a pessoa certa na {{empresa}}.',
        objective: 'Esclarecer motivo do direcionamento.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se houver resposta negativa.',
      },
      {
        id: 'fu_lat2_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se preferir, pode me passar o e-mail da diretoria que envio um resumo por lá.',
        objective: 'Oferecer alternativa por e-mail.',
        tone: 'Prestativo',
        condition: '2 dias sem avanço.',
        whenNotToUse: 'Se já possui e-mail verificado.',
      },
      {
        id: 'fu_lat2_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se consigo contato com a gestão de vocês esta semana.',
        objective: 'Checar viabilidade de contato.',
        tone: 'Direto',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se recusado.',
      },
      {
        id: 'fu_lat2_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Vou fazer uma última tentativa para ver se consigo falar com o responsável de operações da {{empresa}}.',
        objective: 'Última tentativa de ponte.',
        tone: 'Respeitoso',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se arquivado.',
      },
      {
        id: 'fu_lat2_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Sem problemas! Encerro o contato por aqui. Ótimo trabalho por aí!',
        objective: 'Fechamento de loop.',
        tone: 'Cordial',
        condition: '14 dias de espera.',
        whenNotToUse: 'Se houve contato do gestor.',
      },
    ],
  },

  // ETAPA 3 — Contextualização
  {
    id: 'lat_step_3',
    prospectingType: 'latent_opportunity',
    stepNumber: 3,
    code: 'LAT_3_CONTEXTUALIZACAO',
    stepName: 'Contextualização sem Pressão',
    phase: 'INTERACAO',
    objective: 'Contextualizar a área de interesse (automação/sistema) sem empurrar produtos prontos.',
    structure: 'CONTEXTO DE MERCADO + ABERTURA RESPEITOSA',
    requiresClientResponse: true,
    defaultScript: 'O motivo do meu contato é que temos visto muitas empresas em expansão como a {{empresa}} perderem tempo precioso com processos manuais repetitivos no dia a dia. Posso te fazer uma pergunta rápida sobre como vocês organizam isso?',
    followUps: [
      {
        id: 'fu_lat3_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. É uma pergunta bem simples sobre a rotina de controle de vocês.',
        objective: 'Reforçar simplicidade.',
        tone: 'Consultivo',
        condition: 'Sem resposta ao pedido de contextualização.',
        whenNotToUse: 'Se o cliente já fez pergunta.',
      },
      {
        id: 'fu_lat3_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Sem nenhuma intenção de te vender nada de imediato, apenas para entender o modelo operacional da {{empresa}}.',
        objective: 'Eliminar medo de empurro comercial.',
        tone: 'Transparente',
        condition: '1 dia sem retorno.',
        whenNotToUse: 'Se o cliente for agressivo.',
      },
      {
        id: 'fu_lat3_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Vale a pena conversarmos 2 minutos sobre como otimizar essa rotina?',
        objective: 'Pedir 2 minutos de forma objetiva.',
        tone: 'Direto',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente disse não.',
      },
      {
        id: 'fu_lat3_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se o momento não for oportuno, sem problemas!',
        objective: 'Liberar pressão.',
        tone: 'Compreensivo',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se houver agendamento.',
      },
      {
        id: 'fu_lat3_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se essa conversa faz sentido para a {{empresa}} agora.',
        objective: 'Checagem semanal de relevância.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat3_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o contato por aqui. Um abraço!',
        objective: 'Break-up.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 4 — Pergunta sobre processo atual
  {
    id: 'lat_step_4',
    prospectingType: 'latent_opportunity',
    stepNumber: 4,
    code: 'LAT_4_PROCESSO_ATUAL',
    stepName: 'Mapeamento do Processo Atual',
    phase: 'DIAGNOSTICO',
    objective: 'Descobrir se o processo é manual, baseado em planilhas ou sistemas genéricos.',
    structure: 'PERGUNTA ABERTA DE FERRAMENTA E FLUXO',
    requiresClientResponse: true,
    defaultScript: 'Como vocês controlam o fluxo de {{servico}} hoje na {{empresa}}? Esse processo é feito manualmente em planilhas/WhatsApp ou já utilizam algum sistema dedicado?',
    diagnosticQuestions: [
      'Como vocês controlam isso atualmente?',
      'Esse processo é feito manualmente?',
      'Quantas pessoas participam desse processo?',
      'Quanto tempo vocês normalmente gastam com isso?',
      'Existe alguma ferramenta que vocês usam atualmente?',
      'Se pudesse automatizar uma parte desse processo, qual seria?',
      'Já chegaram a pensar em desenvolver uma solução própria?',
      'Qual seria a principal função que você gostaria de ter?',
    ],
    followUps: [
      {
        id: 'fu_lat4_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Planilha de Excel ou anotações diretas no WhatsApp?',
        objective: 'Dar opções de resposta rápida.',
        tone: 'Descontraído',
        condition: 'Sem resposta à pergunta de ferramentas.',
        whenNotToUse: 'Se já respondeu.',
      },
      {
        id: 'fu_lat4_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Pergunto porque a maioria dos negócios perde horas preciosas repassando dados manualmente.',
        objective: 'Explicar relevância da pergunta.',
        tone: 'Consultivo',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente afirmou que é 100% automatizado.',
      },
      {
        id: 'fu_lat4_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. A ferramenta atual de vocês atende com facilidade ou gera travamentos no dia a dia?',
        objective: 'Provocar reflexão de atrito na ferramenta atual.',
        tone: 'Especialista',
        condition: '2 dias sem resposta.',
        whenNotToUse: 'Se satisfeito.',
      },
      {
        id: 'fu_lat4_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para entender se esse é um ponto que vale a pena explorarmos.',
        objective: 'Checagem de relevância.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se sem interesse.',
      },
      {
        id: 'fu_lat4_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Se quiser, posso te mandar um comparativo de tempo gasto entre processo manual vs automatizado.',
        objective: 'Oferecer conteúdo de valor.',
        tone: 'Prestativo',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se o cliente pediu para parar.',
      },
      {
        id: 'fu_lat4_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não tivemos retorno, encerro o contato por aqui. Abraços!',
        objective: 'Fechamento final.',
        tone: 'Cordial',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 5 — Identificação de gargalo
  {
    id: 'lat_step_5',
    prospectingType: 'latent_opportunity',
    stepNumber: 5,
    code: 'LAT_5_GARGALO',
    stepName: 'Identificação do Gargalo Operacional',
    phase: 'DIAGNOSTICO',
    objective: 'Descobrir qual etapa específica mais consome tempo ou gera falhas.',
    structure: 'PERGUNTA ESPECÍFICA DE ATRITO',
    requiresClientResponse: true,
    defaultScript: 'Entendi. E hoje, qual parte desse processo mais consome o tempo da equipe ou gera retrabalho na {{empresa}}?',
    followUps: [
      {
        id: 'fu_lat5_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. É o atendimento inicial, o repasse de informações ou o controle de pedidos/agendamentos?',
        objective: 'Sugerir hipóteses de gargalo para facilitar a resposta.',
        tone: 'Consultivo',
        condition: 'Sem resposta ao gargalo.',
        whenNotToUse: 'Se o cliente já descreveu o problema.',
      },
      {
        id: 'fu_lat5_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu identificar qual dessas etapas gera maior custo de tempo na {{empresa}}?',
        objective: 'Cobrar reflexão de gargalo.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente disse que não tem gargalos.',
      },
      {
        id: 'fu_lat5_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se pudesse resolver um único problema operacional hoje na {{empresa}}, qual seria?',
        objective: 'Pergunta de varinha mágica.',
        tone: 'Direto e empático',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o lead for frio.',
      },
      {
        id: 'fu_lat5_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se identificou onde o processo trava mais.',
        objective: 'Retomar investigação.',
        tone: 'Educado',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se lead arquivado.',
      },
      {
        id: 'fu_lat5_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se ainda pretendem otimizar essa área na {{empresa}}.',
        objective: 'Checagem semanal.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat5_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar minhas mensagens por aqui. Muito sucesso na gestão da {{empresa}}!',
        objective: 'Encerramento de ciclo.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 6 — Exploração
  {
    id: 'lat_step_6',
    prospectingType: 'latent_opportunity',
    stepNumber: 6,
    code: 'LAT_6_EXPLORACAO',
    stepName: 'Exploração de Desejos e Requisitos',
    phase: 'DIAGNOSTICO',
    objective: 'Entender o que a empresa gostaria que acontecesse de forma ideal.',
    structure: 'PROVOCAÇÃO DO ESTADO DESEJADO',
    requiresClientResponse: true,
    defaultScript: 'Se vocês pudessem automatizar ou ter um sistema próprio sob medida para a {{empresa}}, qual seria a principal função que você gostaria de ver funcionando perfeitamente?',
    followUps: [
      {
        id: 'fu_lat6_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Seria um painel de controle, notificações automáticas ou integração direta com WhatsApp?',
        objective: 'Listar ideias de features.',
        tone: 'Inovador',
        condition: 'Sem resposta de exploração.',
        whenNotToUse: 'Se já definido.',
      },
      {
        id: 'fu_lat6_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu imaginar qual funcionalidade traria maior impacto imediato para a equipe da {{empresa}}?',
        objective: 'Estimular visão de valor.',
        tone: 'Consultivo',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente for resistente.',
      },
      {
        id: 'fu_lat6_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Tudo bem? Se quiser, posso desenhar um rascunho de como seria esse fluxo sem custo algum.',
        objective: 'Oferecer rascunho sem compromisso.',
        tone: 'Prestativo',
        condition: '2 dias sem resposta.',
        whenNotToUse: 'Se o cliente rejeitou.',
      },
      {
        id: 'fu_lat6_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Ficou alguma dúvida sobre o que é viável automatizar?',
        objective: 'Tirar dúvidas de viabilidade.',
        tone: 'Acessível',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se lead fechado.',
      },
      {
        id: 'fu_lat6_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se essa exploração faz sentido no planejamento atual.',
        objective: 'Qualificar momento.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se arquivado.',
      },
      {
        id: 'fu_lat6_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar por aqui. Grande abraço!',
        objective: 'Fechamento.',
        tone: 'Cordial',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 7 — Dimensionamento
  {
    id: 'lat_step_7',
    prospectingType: 'latent_opportunity',
    stepNumber: 7,
    code: 'LAT_7_DIMENSIONAMENTO',
    stepName: 'Dimensionamento de Escala & Usuários',
    phase: 'QUALIFICACAO',
    objective: 'Descobrir quantas pessoas utilizariam a solução e o volume de transações/atendimentos.',
    structure: 'PERGUNTAS DE VOLUMETRIA E USUÁRIOS',
    requiresClientResponse: true,
    defaultScript: 'Para eu entender o porte do projeto: quantas pessoas da equipe usariam essa ferramenta diariamente e qual é a média mensal de atendimentos/pedidos na {{empresa}}?',
    followUps: [
      {
        id: 'fu_lat7_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Pode ser um número aproximado apenas para dimensionar a arquitetura!',
        objective: 'Reduzir rigor de exatidão para destravar resposta.',
        tone: 'Descontraído',
        condition: 'Sem resposta ao dimensionamento.',
        whenNotToUse: 'Se já informado.',
      },
      {
        id: 'fu_lat7_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Esse dado nos ajuda a saber se uma solução enxuta atende ou se precisa de algo mais robusto.',
        objective: 'Explicar relevância técnica do dimensionamento.',
        tone: 'Consultivo',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se houver recusa de dados.',
      },
      {
        id: 'fu_lat7_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. É uma operação de 2 a 5 pessoas ou acima de 10?',
        objective: 'Oferecer faixas fáceis de responder.',
        tone: 'Prático',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se o cliente já falou o tamanho da equipe.',
      },
      {
        id: 'fu_lat7_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Conseguimos levantar esse volume para desenhar o conceito?',
        objective: 'Cobrar dado para avançar conceito.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se o cliente pausou.',
      },
      {
        id: 'fu_lat7_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se dimensionamos esse projeto para a {{empresa}} este mês.',
        objective: 'Checagem mensal.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat7_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o acompanhamento. Sucesso nos projetos!',
        objective: 'Encerramento.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 8 — Interesse
  {
    id: 'lat_step_8',
    prospectingType: 'latent_opportunity',
    stepNumber: 8,
    code: 'LAT_8_INTERESSE',
    stepName: 'Validação de Interesse & Prioridade',
    phase: 'VALIDACAO',
    objective: 'Confirmar se existe interesse genuíno e prioridade em avaliar uma solução.',
    structure: 'PERGUNTA DIRETA DE INTERESSE',
    requiresClientResponse: true,
    defaultScript: 'Com base no que conversamos, vejo uma grande oportunidade de economizar tempo e evitar erros na {{empresa}}. Resolver isso é algo que vocês gostariam de ver na prática agora?',
    followUps: [
      {
        id: 'fu_lat8_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Fez sentido para o momento atual da {{empresa}}?',
        objective: 'Checar interesse imediato.',
        tone: 'Consultivo',
        condition: 'Sem resposta sobre interesse.',
        whenNotToUse: 'Se já validou.',
      },
      {
        id: 'fu_lat8_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Se fizer sentido, posso estruturar um conceito visual sem compromisso para você avaliar.',
        objective: 'Oferecer conceito sem risco.',
        tone: 'Prestativo',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente disse não.',
      },
      {
        id: 'fu_lat8_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se for algo para o segundo semestre, pode me avisar que combinamos para frente!',
        objective: 'Alinhar timing futuro sem estresse.',
        tone: 'Compreensivo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente quer urgência.',
      },
      {
        id: 'fu_lat8_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se avançamos para o conceito.',
        objective: 'Solicitar decisão.',
        tone: 'Direto',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se lead arquivado.',
      },
      {
        id: 'fu_lat8_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se esse tema ainda é relevante para a {{empresa}}.',
        objective: 'Checagem semanal de prioridade.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se sem interesse.',
      },
      {
        id: 'fu_lat8_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou pausar nosso contato por aqui. Um abraço para toda a equipe!',
        objective: 'Break-up.',
        tone: 'Cordial',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 9 — Conceito da solução
  {
    id: 'lat_step_9',
    prospectingType: 'latent_opportunity',
    stepNumber: 9,
    code: 'LAT_9_CONCEITO_SOLUCAO',
    stepName: 'Apresentação do Conceito da Solução',
    phase: 'DEMONSTRACAO',
    objective: 'Explicar como a solução personalizada funcionaria passo a passo sem termos técnicos complicados.',
    structure: 'ESTRUTURA DO CONCEITO + BENEFÍCIOS OPERACIONAIS + PEDIDO DE PERMISSÃO PARA MOSTRAR',
    requiresClientResponse: true,
    defaultScript: 'Desenhei a arquitetura conceitual para a {{empresa}}: 1. Entrada automática de dados; 2. Organização centralizada em painel; 3. Disparo de alertas no WhatsApp. Posso te enviar uma demonstração visual de como isso funcionaria?',
    followUps: [
      {
        id: 'fu_lat9_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. É um protótipo bem simples de 1 minuto para você navegar. Posso te mandar?',
        objective: 'Pedir permissão de envio do protótipo.',
        tone: 'Ágil',
        condition: 'Sem resposta ao conceito.',
        whenNotToUse: 'Fora do horário comercial.',
      },
      {
        id: 'fu_lat9_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Ficou bem intuitivo e focado em economizar horas da equipe da {{empresa}}. Me confirma se posso te enviar!',
        objective: 'Destacar facilidade de uso.',
        tone: 'Consultivo',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente pediu para não enviar.',
      },
      {
        id: 'fu_lat9_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Sem nenhum custo ou compromisso, apenas para validar se o desenho técnico faz sentido. Posso mandar?',
        objective: 'Reforçar custo zero do protótipo.',
        tone: 'Tranquilo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se houver rejeição.',
      },
      {
        id: 'fu_lat9_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se o momento estiver corrido, me avise que te mando em outro dia!',
        objective: 'Flexibilidade.',
        tone: 'Empático',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o lead for inválido.',
      },
      {
        id: 'fu_lat9_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. O conceito está pronto. Ainda tem interesse em dar uma olhada esta semana?',
        objective: 'Retomar oportunidade.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se arquivado.',
      },
      {
        id: 'fu_lat9_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou arquivar o protótipo por enquanto. Sucesso à {{empresa}}!',
        objective: 'Encerramento elegante.',
        tone: 'Desapegado',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 10 — Demonstração
  {
    id: 'lat_step_10',
    prospectingType: 'latent_opportunity',
    stepNumber: 10,
    code: 'LAT_10_DEMONSTRACAO',
    stepName: 'Envio da Demonstração / Protótipo Interativo',
    phase: 'DEMONSTRACAO',
    objective: 'Enviar o protótipo/wireframe interativo personalizado para a empresa navegar.',
    structure: 'LINK DO PROTÓTIPO + PONTOS DE DESTAQUE + PEDIDO DE FEEDBACK',
    requiresClientResponse: true,
    defaultScript: 'Aqui está a demonstração conceitual da {{empresa}}: [LINK_DO_PROTOTIPO]. Dê uma olhada no fluxo de automação e me diga o que achou da navegabilidade!',
    followUps: [
      {
        id: 'fu_lat10_1',
        stepNumber: 1,
        intervalHours: 12,
        intervalText: '12 horas',
        message: 'Oi, {{nome}}. Conseguiu abrir o protótipo no computador ou celular?',
        objective: 'Checar acesso técnico ao link.',
        tone: 'Prestativo',
        condition: 'Protótipo enviado sem confirmação de abertura.',
        whenNotToUse: 'Se já confirmou acesso.',
      },
      {
        id: 'fu_lat10_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu navegar pelas telas que desenhei para a {{empresa}}?',
        objective: 'Cobrar feedback com suavidade.',
        tone: 'Consultivo',
        condition: '24h após envio.',
        whenNotToUse: 'Se o cliente estiver testando.',
      },
      {
        id: 'fu_lat10_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. O que achou da lógica do sistema? Atende o dia a dia da equipe?',
        objective: 'Conduzir para validação da lógica.',
        tone: 'Especialista',
        condition: '2 dias sem feedback.',
        whenNotToUse: 'Se o cliente rejeitou.',
      },
      {
        id: 'fu_lat10_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Se quiser, posso gravar um vídeo de 1 minuto demonstrando o fluxo na prática.',
        objective: 'Oferecer vídeo explicativo.',
        tone: 'Prestativo',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se o cliente não assiste vídeos.',
      },
      {
        id: 'fu_lat10_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para saber se o conceito faz sentido ou se devemos ajustar a arquitetura.',
        objective: 'Qualificar continuidade.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se sem interesse.',
      },
      {
        id: 'fu_lat10_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou desativar o link do protótipo temporariamente para liberar o servidor. Um abraço!',
        objective: 'Escassez real e encerramento.',
        tone: 'Profissional e desapegado',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 11 — Feedback
  {
    id: 'lat_step_11',
    prospectingType: 'latent_opportunity',
    stepNumber: 11,
    code: 'LAT_11_FEEDBACK',
    stepName: 'Colheita e Análise de Feedback Técnico',
    phase: 'DEMONSTRACAO',
    objective: 'Colher impressões sobre o que atende perfeitamente e o que precisaria de refinamento.',
    structure: 'PERGUNTAS DIRECIONADAS DE AVALIAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'O que você achou dessa lógica para a {{empresa}}? Teve alguma parte que você achou essencial e alguma que achou desnecessária?',
    followUps: [
      {
        id: 'fu_lat11_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Ficou claro o ganho de tempo que isso traria para a equipe?',
        objective: 'Reforçar ganho de tempo.',
        tone: 'Consultivo',
        condition: 'Sem resposta ao feedback.',
        whenNotToUse: 'Se o cliente já deu feedback.',
      },
      {
        id: 'fu_lat11_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Teve alguma função que você gostaria de adicionar a esse desenho?',
        objective: 'Estimular cocriação de funcionalidades.',
        tone: 'Inovador',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o escopo já estiver fechado.',
      },
      {
        id: 'fu_lat11_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se achar que o modelo atende, podemos já listar os requisitos de desenvolvimento.',
        objective: 'Ponte para etapa de requisitos.',
        tone: 'Prático',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente apontou falhas graves.',
      },
      {
        id: 'fu_lat11_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Conseguimos alinhar esse feedback para avançar?',
        objective: 'Solicitar alinhamento.',
        tone: 'Direto',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat11_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se ainda faz sentido falarmos sobre esse sistema para a {{empresa}}.',
        objective: 'Checagem semanal.',
        tone: 'Profissional',
        condition: '7 dias sem retorno.',
        whenNotToUse: 'Se já arquivado.',
      },
      {
        id: 'fu_lat11_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou encerrar o atendimento. Sucesso nos projetos da {{empresa}}!',
        objective: 'Break-up.',
        tone: 'Cordial',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 12 — Requisitos
  {
    id: 'lat_step_12',
    prospectingType: 'latent_opportunity',
    stepNumber: 12,
    code: 'LAT_12_REQUISITOS',
    stepName: 'Mapeamento Final de Requisitos & Integrações',
    phase: 'PROPOSTA',
    objective: 'Definir integrações obrigatórias (WhatsApp API, gateways, banco de dados, ERPs).',
    structure: 'CHECKLIST DE REQUISITOS + PERGUNTA DE INTEGRAÇÃO',
    requiresClientResponse: true,
    defaultScript: 'Perfeito! Para fecharmos o escopo técnico: existe algum sistema ou banco de dados legado que precisaremos integrar obrigatoriamente, ou podemos rodar de forma 100% independente?',
    followUps: [
      {
        id: 'fu_lat12_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Se puder só me dizer quais ferramentas vocês usam hoje para eu prever os conectores.',
        objective: 'Facilitar mapeamento de APIs.',
        tone: 'Técnico e acessível',
        condition: 'Sem resposta sobre integrações.',
        whenNotToUse: 'Se não houver sistemas legados.',
      },
      {
        id: 'fu_lat12_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Podemos rodar uma versão inicial independente para não gerar dependência técnica de outros softwares.',
        objective: 'Propor MVP independente.',
        tone: 'Prático',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se integração for mandatória.',
      },
      {
        id: 'fu_lat12_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Com esses dados consigo estruturar a proposta de viabilidade técnica e financeira da {{empresa}}.',
        objective: 'Ponte para proposta.',
        tone: 'Profissional',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente pausou o projeto.',
      },
      {
        id: 'fu_lat12_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Conseguimos fechar esse escopo para eu gerar o cronograma?',
        objective: 'Cobrar fechamento de escopo.',
        tone: 'Direto',
        condition: '4 dias sem resposta.',
        whenNotToUse: 'Se o lead desistiu.',
      },
      {
        id: 'fu_lat12_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Apenas para checar se mantemos a previsão de desenvolvimento deste projeto.',
        objective: 'Checagem de cronograma.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat12_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Estou encerrando a análise técnica por aqui. Um abraço!',
        objective: 'Fechamento final.',
        tone: 'Desapegado',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 13 — Viabilidade
  {
    id: 'lat_step_13',
    prospectingType: 'latent_opportunity',
    stepNumber: 13,
    code: 'LAT_13_VIABILIDADE',
    stepName: 'Validação de Viabilidade & Cronograma',
    phase: 'PROPOSTA',
    objective: 'Confirmar viabilidade técnica e estimar tempo de desenvolvimento antes da proposta comercial.',
    structure: 'PARECER DE VIABILIDADE + ESTIMATIVA DE TEMPO + PERMISSIBILIDADE COMERCIAL',
    requiresClientResponse: true,
    defaultScript: 'Fizemos a análise de viabilidade para a {{empresa}} e o projeto é 100% executável em [TEMPO_ESTIMADO] semanas. Posso te apresentar a proposta comercial com as opções de entrega?',
    followUps: [
      {
        id: 'fu_lat13_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. Posso te encaminhar a proposta com o cronograma e investimento?',
        objective: 'Pedir permissão direta de proposta.',
        tone: 'Objetivo',
        condition: 'Sem resposta ao parecer de viabilidade.',
        whenNotToUse: 'Fora de horário.',
      },
      {
        id: 'fu_lat13_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu ver a estimativa de prazo? Me confirma se posso te enviar os valores!',
        objective: 'Cobrar autorização de proposta.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente tiver dúvidas técnicas.',
      },
      {
        id: 'fu_lat13_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Temos condições de entrega rápida para este mês se aprovarmos esta semana.',
        objective: 'Criar tração de calendário.',
        tone: 'Motivador',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se escopo for de meses.',
      },
      {
        id: 'fu_lat13_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se faz sentido avançarmos para os números.',
        objective: 'Checagem direta.',
        tone: 'Direto',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat13_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se mantemos a vaga técnica aberta para a {{empresa}}.',
        objective: 'Preservar vaga técnica.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se sem interesse.',
      },
      {
        id: 'fu_lat13_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Como não tivemos retorno, vou liberar a data de entrega. Um abraço!',
        objective: 'Encerramento de viabilidade.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 14 — Proposta
  {
    id: 'lat_step_14',
    prospectingType: 'latent_opportunity',
    stepNumber: 14,
    code: 'LAT_14_PROPOSTA',
    stepName: 'Apresentação da Proposta Comercial',
    phase: 'PROPOSTA',
    objective: 'Apresentar escopo fechado, modelo de entrega e investimento total com transparência.',
    structure: 'ESCOPO RESUMIDO + CRONOGRAMA + INVESTIMENTO + CONDIÇÕES',
    requiresClientResponse: true,
    defaultScript: 'Segue a proposta técnica e comercial da {{empresa}}: 1. Desenvolvimento do sistema sob medida; 2. Configurações de banco e segurança; 3. Treinamento da equipe. O investimento é {{preco}} com entrega em [PRAZO]. O que você acha dessa estrutura?',
    followUps: [
      {
        id: 'fu_lat14_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Conseguiu analisar os termos da proposta?',
        objective: 'Checar análise inicial da proposta.',
        tone: 'Consultivo',
        condition: 'Proposta enviada sem retorno.',
        whenNotToUse: 'Se o cliente já respondeu.',
      },
      {
        id: 'fu_lat14_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Os valores e prazos ficaram adequados ao planejamento financeiro da {{empresa}}?',
        objective: 'Checar adequação orçamentária.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se houver contraproposta.',
      },
      {
        id: 'fu_lat14_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Ficou alguma dúvida sobre o escopo ou as entregas programadas?',
        objective: 'Sanar dúvidas de escopo.',
        tone: 'Prestativo',
        condition: '2 dias de silêncio.',
        whenNotToUse: 'Se o cliente pediu desconto.',
      },
      {
        id: 'fu_lat14_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Se precisar de alguma adequação de parcelamento para viabilizar, me avise!',
        objective: 'Oferecer flexibilidade de parcelamento.',
        tone: 'Flexível',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se pagamento for à vista confirmado.',
      },
      {
        id: 'fu_lat14_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se aprovamos a proposta para iniciar o desenvolvimento.',
        objective: 'Checagem de aprovação.',
        tone: 'Direto',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat14_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Estou arquivando a proposta por aqui. Se quiser retomar no futuro, estou à disposição!',
        objective: 'Encerramento de proposta.',
        tone: 'Cordial e desapegado',
        condition: '14 dias sem retorno.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 15 — Negociação
  {
    id: 'lat_step_15',
    prospectingType: 'latent_opportunity',
    stepNumber: 15,
    code: 'LAT_15_NEGOCIACAO',
    stepName: 'Negociação Comercial & Ajustes Finais',
    phase: 'NEGOCIACAO',
    objective: 'Alinhar flexibilização de etapas ou parcelamento sem desvalorizar o software.',
    structure: 'FLEXIBILIDADE DE FASES + VALIDAÇÃO DE ACORDO',
    requiresClientResponse: true,
    defaultScript: 'Podemos dividir a implementação em 2 fases: Fase 1 (MVP prioritário) por [VALOR_FASE_1] e Fase 2 após validação dos primeiros resultados. Fica mais confortável para o fluxo de caixa da {{empresa}}?',
    followUps: [
      {
        id: 'fu_lat15_1',
        stepNumber: 1,
        intervalHours: 8,
        intervalText: '8 horas',
        message: 'Oi, {{nome}}. Essa divisão por fases viabiliza darmos o start?',
        objective: 'Validar faseamento.',
        tone: 'Prático',
        condition: 'Sem resposta ao faseamento.',
        whenNotToUse: 'Se já aceitou.',
      },
      {
        id: 'fu_lat15_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Posso formalizar o início com o escopo da Fase 1 hoje?',
        objective: 'Formalizar MVP.',
        tone: 'Profissional',
        condition: '1 dia sem resposta.',
        whenNotToUse: 'Se o cliente quer o escopo completo.',
      },
      {
        id: 'fu_lat15_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Tem algum detalhe que você ainda gostaria de ponderar?',
        objective: 'Identificar objeção oculta.',
        tone: 'Consultivo',
        condition: '2 dias sem retorno.',
        whenNotToUse: 'Se contrato enviado.',
      },
      {
        id: 'fu_lat15_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para saber se priorizamos o desenvolvimento da {{empresa}}.',
        objective: 'Checar prioridade técnica.',
        tone: 'Direto',
        condition: '4 dias de silêncio.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat15_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se mantemos os termos negociados ativos.',
        objective: 'Checagem semanal.',
        tone: 'Profissional',
        condition: '7 dias sem avanço.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat15_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou cancelar a condição negociada por enquanto. Sucesso à {{empresa}}!',
        objective: 'Cancelamento formal da negociação.',
        tone: 'Desapegado',
        condition: '14 dias sem resposta.',
        whenNotToUse: 'Se respondeu.',
      },
    ],
  },

  // ETAPA 16 — Fechamento
  {
    id: 'lat_step_16',
    prospectingType: 'latent_opportunity',
    stepNumber: 16,
    code: 'LAT_16_FECHAMENTO',
    stepName: 'Fechamento & Kick-off do Desenvolvimento',
    phase: 'FECHAMENTO',
    objective: 'Formalizar contrato de desenvolvimento, faturamento e agendamento de kick-off.',
    structure: 'CONFIRMAÇÃO DO PROJETO + CONTRATO + AGENDAMENTO DE KICK-OFF',
    requiresClientResponse: true,
    defaultScript: 'Contrato e termos prontos para assinatura digital, {{nome}}! Assim que assinar, agendamos nossa reunião de kick-off para [DATA_KICKOFF]. Me confirma o e-mail oficial para o envio?',
    followUps: [
      {
        id: 'fu_lat16_1',
        stepNumber: 1,
        intervalHours: 6,
        intervalText: '6 horas',
        message: 'Oi, {{nome}}. Segue o link de assinatura digital. Qualquer dúvida estou por aqui!',
        objective: 'Enviar link de assinatura.',
        tone: 'Ágil',
        condition: 'Contrato emitido aguardando assinatura.',
        whenNotToUse: 'Se já assinado.',
      },
      {
        id: 'fu_lat16_2',
        stepNumber: 2,
        intervalHours: 24,
        intervalText: '1 dia',
        message: 'Olá, {{nome}}. Conseguiu acessar o termo para assinatura?',
        objective: 'Cobrar assinatura.',
        tone: 'Profissional',
        condition: '1 dia sem assinatura.',
        whenNotToUse: 'Se o jurídico estiver avaliando.',
      },
      {
        id: 'fu_lat16_3',
        stepNumber: 3,
        intervalHours: 48,
        intervalText: '2 dias',
        message: 'Oi, {{nome}}. Se precisar de algum ajuste nos dados contratuais, pode me avisar que altero em minutos!',
        objective: 'Facilitar correções cadastrais.',
        tone: 'Prestativo',
        condition: '2 dias sem assinatura.',
        whenNotToUse: 'Se dados corretos.',
      },
      {
        id: 'fu_lat16_4',
        stepNumber: 4,
        intervalHours: 96,
        intervalText: '4 dias',
        message: 'Olá, {{nome}}. Tudo bem? Apenas para confirmar a data do nosso kick-off técnico.',
        objective: 'Preservar data do kick-off.',
        tone: 'Direto',
        condition: '4 dias sem retorno.',
        whenNotToUse: 'Se cancelado.',
      },
      {
        id: 'fu_lat16_5',
        stepNumber: 5,
        intervalHours: 168,
        intervalText: '7 dias',
        message: 'Oi, {{nome}}. Passando para checar se mantemos a sprint de desenvolvimento reservada para a {{empresa}}.',
        objective: 'Checar sprint de desenvolvimento.',
        tone: 'Profissional',
        condition: '7 dias sem assinatura.',
        whenNotToUse: 'Se desistiu.',
      },
      {
        id: 'fu_lat16_6',
        stepNumber: 6,
        intervalHours: 336,
        intervalText: '14 dias',
        message: 'Olá, {{nome}}. Vou pausar a alocação de equipe por enquanto. Um abraço e sucesso!',
        objective: 'Fechamento final.',
        tone: 'Cordial',
        condition: '14 dias sem assinatura.',
        whenNotToUse: 'Se assinado.',
      },
    ],
  },
];
