import {
  AppSettings,
  Campaign,
  Client,
  Company,
  Contact,
  HistoryEvent,
  IdealCustomerProfile,
  Lead,
  MessageTemplate,
  PipelineStage,
  ProspectAction,
  Service,
} from '../types';
import { DEFAULT_PIPELINE_STAGES } from '../utils/constants';
import { DEFAULT_SCORING_WEIGHTS } from '../utils/leadScoring';

export const INITIAL_SETTINGS: AppSettings = {
  theme: 'dark',
  dailyGoal: 15,
  estMinutesPerAction: 2,
  autoAdvanceOnDone: true,
  soundEnabled: false,
  showTips: true,
  dataStorageType: 'indexeddb_local',
  lastBackupDate: undefined,
  scoringWeights: DEFAULT_SCORING_WEIGHTS,
};

export const SEED_SERVICES: Service[] = [
  {
    id: 'srv-lp',
    name: 'Landing Page de Alta Conversão',
    description: 'Páginas de captura de alto impacto, ultra-rápidas e otimizadas para tráfego pago e conversão direta no WhatsApp.',
    basePrice: 2500,
    currency: 'BRL',
    anchorPrice: 4500,
    benefits: [
      'Carregamento ultra-rápido (< 1.2 segundos)',
      'Copywriting persuasivo focado em ação direta',
      'Layout 100% responsivo para mobile',
      'Pixel do Meta, Google Ads e rastreamento de WhatsApp integrados',
    ],
    targetAudience: [
      'Clínicas e Consultórios Médicos/Odonto',
      'Advogados e Escritórios de Advocacia',
      'Infoprodutores e Negócios Locais com Tráfego Pago',
    ],
    problemsSolved: [
      'Anúncios rodando com alto custo por clique e pouca conversão',
      'Site institucional genérico que distrai o visitante',
      'Falta de rastreamento de leads no WhatsApp',
    ],
    commonObjections: [
      {
        objection: 'Já tenho Instagram ativo, não preciso de site.',
        counterArgument: 'O Instagram é terreno alugado com dezenas de distrações. Uma Landing Page isola a atenção do lead e chega a converter 4x mais clientes.',
      },
      {
        objection: 'Achei o valor acima do que pretendia gastar.',
        counterArgument: 'Uma única venda ou cliente conquistado pela Landing Page já cobre 100% do investimento logo no primeiro mês.',
      },
    ],
    arguments: [
      'Design exclusivo alinhado ao posicionamento premium da marca',
      'Entrega ágil em até 7 dias úteis com suporte completo',
      'Garantia de pontuação 90+ no Google PageSpeed',
    ],
    proofs: [
      'Taxa média de conversão de 14.8% em campanhas locais',
      'Mais de 40 páginas entregues com aumento comprovado de ROAS',
    ],
    defaultCta: 'Podemos agendar um bate-papo de 10 minutos para analisar seu funil e desenhar a estrutura da sua nova Landing Page?',
    active: true,
    code: 'SRV-LP',
    category: 'Presença Web',
    ticketValue: 2500,
    valueProposition: 'Multiplicar a conversão dos seus anúncios com páginas rápidas e persuasivas.',
    keyDifferentiators: ['Copywriting persuasivo', 'Ultra-velocidade', 'Rastreamento avançado'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-website',
    name: 'Website Institucional Corporativo',
    description: 'Portal institucional de elite, com páginas institucionais, catálogo de serviços, blog de autoridade e SEO profissional para Google.',
    basePrice: 6000,
    currency: 'BRL',
    anchorPrice: 9500,
    benefits: [
      'Autoridade instantânea para fechar contratos de alto ticket',
      'Estrutura preparada para ranquear nas primeiras posições do Google (SEO)',
      'Painel intuitivo para alteração de textos e imagens',
      'Segurança SSL e infraestrutura de alta disponibilidade',
    ],
    targetAudience: [
      'Empresas B2B e Indústrias',
      'Consultorias, Escritórios e Prestadores de Serviços Premium',
      'Comércios consolidados e Redes em expansão',
    ],
    problemsSolved: [
      'Empresa parecer amadora ou menor do que realmente é',
      'Perda de concorrências para concorrentes com presença digital superior',
      'Invisibilidade nos mecanismos de busca do Google',
    ],
    commonObjections: [
      {
        objection: 'Meus clientes vêm todos por indicação.',
        counterArgument: 'Mesmo indicado, o cliente sempre pesquisa seu site antes de assinar contrato para checar sua solidez e reputação.',
      },
      {
        objection: 'WordPress é muito complicado de manter.',
        counterArgument: 'Entregamos um painel limpo e simplificado com treinamento em vídeo gravado para sua equipe.',
      },
    ],
    arguments: [
      'Arquitetura modular que cresce junto com a empresa',
      'Design construído sob medida, sem templates genéricos saturados',
      'Integração com CRM e formulários inteligentes',
    ],
    proofs: [
      'Cases de empresas que aumentaram o ticket médio em 30% após o novo site',
      'Portfólio com empresas consolidadas',
    ],
    defaultCta: 'Posso te mostrar uma prévia de 3 minutos de como podemos elevar a presença digital da sua empresa?',
    active: true,
    code: 'SRV-WEB',
    category: 'Presença Web',
    ticketValue: 6000,
    valueProposition: 'Construir autoridade inquestionável no mercado com um portal institucional de alto nível.',
    keyDifferentiators: ['SEO Técnico', 'Design Exclusivo', 'Painel Simplificado'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-app',
    name: 'Aplicativo Mobile & Web App (PWA)',
    description: 'Sistemas interativos e aplicativos na palma da mão dos clientes, com notificações push, agendamentos e área exclusiva de membros.',
    basePrice: 18000,
    currency: 'BRL',
    anchorPrice: 28000,
    benefits: [
      'Canal proprietário direto no celular do cliente sem intermediários',
      'Notificações push gratuitas com taxa de abertura superior a 80%',
      'Automação de processos manuais, pedidos e agendamentos',
      'Acesso offline e velocidade nativa de resposta',
    ],
    targetAudience: [
      'Redes de Franquias e Academias',
      'Restaurantes e Mercados com Delivery Próprio',
      'Clínicas com agendamentos recorrentes e Clubes de Assinatura',
    ],
    problemsSolved: [
      'Taxas abusivas de marketplaces e plataformas intermediárias (15% a 30%)',
      'Atendimento manual no WhatsApp sobrecarregando a equipe',
      'Falta de retenção e recompra automática de clientes',
    ],
    commonObjections: [
      {
        objection: 'Desenvolvimento de app é demorado e arriscado.',
        counterArgument: 'Trabalhamos com arquitetura ágil e protótipos funcionais com entregas quinzenais testadas.',
      },
      {
        objection: 'Os clientes não vão querer baixar na App Store.',
        counterArgument: 'Nossa tecnologia PWA permite instalar direto pelo navegador em 1 segundo, sem burocracia de lojas.',
      },
    ],
    arguments: [
      'Redução imediata de custos operacionais e atendimento',
      'Banco de dados próprio e segurança de nível corporativo',
    ],
    proofs: [
      'Economia de mais de R$ 15.000/mês em taxas de intermediação em clientes atendidos',
    ],
    defaultCta: 'Faz sentido fazermos uma sessão de 15 minutos para mapear as funcionalidades chave do seu aplicativo?',
    active: true,
    code: 'SRV-APP',
    category: 'Tecnologia',
    ticketValue: 18000,
    valueProposition: 'Fidelizar clientes e automatizar sua operação com um aplicativo proprietário veloz.',
    keyDifferentiators: ['PWA sem atrito', 'Notificações Push', 'Zero taxas de marketplace'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-google-business',
    name: 'Otimização de Google Business Profile (Local SEO)',
    description: 'Posicionamento estratégico no Top 3 do Google Maps para atrair ligações, rotas e mensagens orgânicas todos os dias.',
    basePrice: 1500,
    currency: 'BRL',
    anchorPrice: 2800,
    benefits: [
      'Aparecer no Top 3 do Google Maps para buscas quentes da sua região',
      'Geração orgânica de contatos no WhatsApp e ligações telefônicas',
      'Estratégia de coleta e gestão profissional de avaliações 5 estrelas',
      'Fotos profissionais geolocalizadas e catálogo de produtos/serviços',
    ],
    targetAudience: [
      'Negócios Locais Físicos (Restaurantes, Clínicas, Oficinas, Lojas)',
      'Prestadores de Serviços com atuação regional (Vidraçarias, Eletricistas, Dedetizadoras)',
    ],
    problemsSolved: [
      'Concorrentes vizinhos recebendo mais clientes no Google Maps',
      'Ficha desatualizada, fotos antigas e horários errados',
      'Avaliações negativas sem resposta estratégica',
    ],
    commonObjections: [
      {
        objection: 'O cadastro no Google é gratuito, por que pagar?',
        counterArgument: 'Criar a conta é grátis, mas alcançar o Top 3 exige SEO local, palavras-chave nas categorias certas e geolocalização de imagens.',
      },
    ],
    arguments: [
      'Maior retorno sobre investimento do marketing local: tráfego 100% orgânico',
      'Resultados visíveis nas métricas do Google em poucas semanas',
    ],
    proofs: [
      'Aumento médio de 240% em solicitações de rotas e chamadas telefônicas nos primeiros 45 dias',
    ],
    defaultCta: 'Quer que eu envie uma auditoria gratuita de 2 minutos sobre o posicionamento do seu negócio no Google Maps hoje?',
    active: true,
    code: 'SRV-GBP',
    category: 'Marketing Local',
    ticketValue: 1500,
    valueProposition: 'Colocar seu negócio nas primeiras posições do Google Maps para atrair clientes locais prontos para comprar.',
    keyDifferentiators: ['SEO Local Georreferenciado', 'Protocolo de Avaliações', 'Auditoria Inicial Gratuita'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-design',
    name: 'Design Estratégico & Identidade Visual',
    description: 'Construção de marcas marcantes, manuais de identidade, apresentações comerciais e materiais gráficos de alto padrão.',
    basePrice: 3500,
    currency: 'BRL',
    anchorPrice: 5500,
    benefits: [
      'Percepção de valor instantânea que autoriza cobrar preços mais altos',
      'Manual de marca completo com tipografia, paleta e aplicações práticas',
      'Templates editáveis para redes sociais e apresentações comerciais',
      'Diferenciação clara em relação à concorrência visualmente genérica',
    ],
    targetAudience: [
      'Empresas em reposicionamento de mercado e lançamento de novas marcas',
      'Profissionais liberais e executivos querendo branding premium',
    ],
    problemsSolved: [
      'Clientes pedindo desconto por julgarem a empresa pela aparência amadora',
      'Comunicação visual desalinhada entre redes, site e propostas',
      'Logotipo antigo ou ilegível em telas de celular',
    ],
    commonObjections: [
      {
        objection: 'Design é perfumaria, o que importa é o produto.',
        counterArgument: 'A embalagem define quanto o cliente aceita pagar antes mesmo de experimentar o produto.',
      },
    ],
    arguments: [
      'Metodologia baseada em arquétipos e psicologia das cores para vendas',
      'Entrega de todos os arquivos vetoriais prontos para impressão e digital',
    ],
    proofs: [
      'Marcas reposicionadas que aumentaram o ticket médio em até 50%',
    ],
    defaultCta: 'Podemos marcar uma conversa de 15 minutos para avaliar o reposicionamento visual da sua marca?',
    active: true,
    code: 'SRV-DSG',
    category: 'Branding',
    ticketValue: 3500,
    valueProposition: 'Elevar a percepção de valor da sua marca para cobrar mais caro e fechar mais contratos.',
    keyDifferentiators: ['Branding focado em conversão', 'Manual Completo', 'Templates Prontos'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-maintenance',
    name: 'Manutenção, Suporte & Hospedagem Contínua',
    description: 'Gestão preventiva de infraestrutura, backups automáticos, atualizações de segurança e suporte técnico sob demanda.',
    basePrice: 800,
    currency: 'BRL',
    anchorPrice: 1400,
    benefits: [
      'Site 99.9% do tempo no ar sem quedas em horários de pico',
      'Backups diários na nuvem e restauração instantânea em caso de falha',
      'Proteção ativa contra malwares, invasões e links quebrados',
      'Banco de horas mensal para pequenos ajustes de conteúdo e banners',
    ],
    targetAudience: [
      'Empresas com sites e e-commerces que dependem de vendas online',
      'Negócios sem departamento interno de TI',
    ],
    problemsSolved: [
      'Site fora do ar gerando prejuízo e perda de vendas',
      'Vírus ou plugins desatualizados quebrando formulários de contato',
      'Falta de suporte técnico ágil para resolver emergências',
    ],
    commonObjections: [
      {
        objection: 'Meu site quase nunca dá problema.',
        counterArgument: 'Falhas de segurança acontecem silenciosamente; a manutenção preventiva custa uma fração do prejuízo de horas fora do ar.',
      },
    ],
    arguments: [
      'SLA de atendimento de até 2 horas para chamados críticos',
      'Relatório mensal de desempenho, visitas e saúde técnica',
    ],
    proofs: [
      'Mais de 80 servidores gerenciados com zero incidentes de perda de dados',
    ],
    defaultCta: 'Podemos assumir a retaguarda técnica do seu site para sua equipe focar 100% nas vendas?',
    active: true,
    code: 'SRV-MNT',
    category: 'Suporte & TI',
    ticketValue: 800,
    valueProposition: 'Garantir estabilidade total, segurança e atualizações constantes para o seu site nunca parar de vender.',
    keyDifferentiators: ['SLA 2h', 'Backups Diários', 'Relatórios Mensais'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'srv-consulting',
    name: 'Consultoria de Estruturação Comercial & Vendas B2B',
    description: 'Diagnóstico profundo, implementação de processos de vendas outbound, qualificação de leads e treinamento de equipe.',
    basePrice: 8500,
    currency: 'BRL',
    anchorPrice: 14000,
    benefits: [
      'Máquina previsível de prospecção e geração de reuniões qualificadas',
      'Playbooks e scripts de vendas validados para WhatsApp, Telefone e LinkedIn',
      'Configuração do CRM com funis claros e automações de cadência',
      'Treinamento prático e simulação de reuniões com sua equipe comercial',
    ],
    targetAudience: [
      'PMEs faturando acima de R$ 50k/mês querendo acelerar vendas',
      'Diretores e Sócios com processos comerciais instáveis',
    ],
    problemsSolved: [
      'Vendas sazonais e imprevisíveis (montanha-russa de receita)',
      'Dependência exclusiva de indicações de conhecidos',
      'Vendedores sem método de prospecção ativa perdendo tempo com leads frios',
    ],
    commonObjections: [
      {
        objection: 'Já tentamos consultorias teóricas que não geraram vendas.',
        counterArgument: 'Nossa metodologia é 100% prática: entramos na operação, ajustamos os scripts e prospectamos juntos nos primeiros 30 dias.',
      },
    ],
    arguments: [
      'Acompanhamento semanal com métricas transparentes de conversão',
      'Geração de reuniões reais já durante o período de consultoria',
    ],
    proofs: [
      'Aumento médio de 45% no volume de reuniões qualificadas em 60 dias',
    ],
    defaultCta: 'Vamos bater um papo de 20 minutos para mapear os 3 principais gargalos do seu funil comercial hoje?',
    active: true,
    code: 'SRV-CSL',
    category: 'Consultoria',
    ticketValue: 8500,
    valueProposition: 'Estruturar um funil de aquisição ativo e previsibilidade de receita em 60 dias.',
    keyDifferentiators: ['Hands-on na prática', 'Playbook completo', 'Acompanhamento semanal'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ICPS: IdealCustomerProfile[] = [
  {
    id: 'icp-1',
    name: 'Clínicas & Negócios Locais de Alto Padrão',
    niches: ['Odontologia', 'Estética Avançada', 'Dermatologia', 'Cirurgia Plástica', 'Oftalmologia'],
    countries: ['Brasil', 'Portugal'],
    cities: ['São Paulo', 'Rio de Janeiro', 'Curitiba', 'Belo Horizonte', 'Porto Alegre', 'Lisboa', 'Porto'],
    size: ['Micro (1-5)', 'Pequena (6-20)'],
    unitsRange: '1 a 3 unidades',
    priceRange: { min: 2500, max: 8000 },
    problems: [
      'Alto custo por lead em anúncios no Meta sem conversão final',
      'Ficha do Google Maps desatualizada perdendo pacientes para concorrentes locais',
      'Sem landing page específica para procedimentos de alto ticket',
    ],
    suitableServiceIds: ['srv-lp', 'srv-google-business', 'srv-design'],
    positiveCriteria: [
      'Possui WhatsApp direto ou celular da recepção/gerente',
      'Possui pelo menos 1 unidade física com endereço comercial fixo',
      'Perfil ativo no Instagram com fotos da clínica ou procedimentos',
      'Ticket médio de procedimento acima de R$ 1.500',
    ],
    negativeCriteria: [
      'Sem telefone ou canal de contato cadastrado',
      'Estabelecimento fechado ou sem responsável identificável',
    ],
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'icp-2',
    name: 'Empresas B2B & Prestadores de Serviços em Expansão',
    niches: ['Logística & Transporte', 'Consultoria & Treinamento', 'Tecnologia & Software', 'Engenharia & Arquitetura', 'Contabilidade Consultiva'],
    countries: ['Brasil', 'Portugal'],
    cities: ['São Paulo', 'Campinas', 'Curitiba', 'Joinville', 'Belo Horizonte', 'Lisboa'],
    size: ['Pequena (6-20)', 'Média (21-50)'],
    unitsRange: '1 a 5 unidades',
    priceRange: { min: 6000, max: 20000 },
    problems: [
      'Vendas imprevisíveis dependendo apenas de indicações',
      'Website institucional antigo que não transmite a solidez atual da empresa',
      'Processo comercial manual sem cadência estruturada',
    ],
    suitableServiceIds: ['srv-website', 'srv-consulting', 'srv-maintenance'],
    positiveCriteria: [
      'Cargo do decisor identificado (Sócio, Diretor, CEO ou Gerente Comercial)',
      'Possui mais de 10 funcionários ou múltiplas unidades',
      'Faturamento estimado superior a R$ 60.000/mês',
      'Presença no LinkedIn e website institucional',
    ],
    negativeCriteria: [
      'Empresa unipessoal sem estrutura de investimento',
      'Mercado com margem excessivamente baixa',
    ],
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'icp-3',
    name: 'Redes & Franquias de Varejo / Alimentação',
    niches: ['Gastronomia & Restaurantes', 'Redes de Franquias', 'Academias & Fitness', 'Lojas Especializadas'],
    countries: ['Brasil'],
    cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Curitiba'],
    size: ['Média (21-50)', 'Grande (50+)'],
    unitsRange: '2 a 15 unidades',
    priceRange: { min: 8000, max: 35000 },
    problems: [
      'Taxas abusivas de marketplaces de delivery (iFood/Rappi)',
      'Falta de canal próprio para retenção e fidelização de clientes',
      'Processos manuais de atendimento e anotação de pedidos',
    ],
    suitableServiceIds: ['srv-app', 'srv-google-business', 'srv-maintenance'],
    positiveCriteria: [
      'Opera com 2 ou mais unidades físicas',
      'Alto volume diário de pedidos e transações',
      'Decisor de marketing ou sócio operacional mapeado',
    ],
    negativeCriteria: [
      'Apenas 1 ponto informal sem registro de marca',
    ],
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];


export const SEED_TEMPLATES: MessageTemplate[] = [
  {
    id: 'tpl-1',
    title: 'Primeiro Contato - Abordagem Direta WhatsApp',
    channel: 'whatsapp',
    type: 'first_contact',
    content: 'Olá, {{primeiro_nome}}, tudo bem?\n\nVi que você lidera a {{empresa}} no segmento. Estamos ajudando empresas do setor a {{proposta_valor}} com o nosso serviço de {{servico}}.\n\nFaz sentido eu te enviar um resumo de 2 minutos sobre como fizemos isso recentemente?',
    variables: ['primeiro_nome', 'empresa', 'proposta_valor', 'servico'],
    notes: 'Ideal para abordagem rápida e objetiva no WhatsApp.',
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-2',
    title: 'Follow-up 1 (48h após sem resposta)',
    channel: 'whatsapp',
    type: 'follow_up',
    content: 'Oi {{primeiro_nome}}, imaginei que sua semana estivesse corrida na {{empresa}}.\n\nSó para confirmar: otimizar {{servico}} é uma prioridade atual para vocês ou prefere que eu retorne no próximo mês?',
    variables: ['primeiro_nome', 'empresa', 'servico'],
    notes: 'Mensagem curta com baixo atrito de resposta.',
    isDefault: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-3',
    title: 'Conexão LinkedIn - Relevância Executiva',
    channel: 'linkedin',
    type: 'first_contact',
    content: 'Olá {{primeiro_nome}}, acompanho os avanços da {{empresa}} e notei sua atuação como {{cargo}}.\n\nTenho compartilhado insights sobre {{servico}} com outros líderes da área. Será um prazer conectar por aqui!',
    variables: ['primeiro_nome', 'empresa', 'cargo', 'servico'],
    notes: 'Convite ou InMail para LinkedIn.',
    isDefault: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tpl-4',
    title: 'Break-up (Última tentativa amigável)',
    channel: 'email',
    type: 'break_up',
    content: 'Olá {{primeiro_nome}},\n\nComo não tive retorno, assumo que {{servico}} não é um foco para a {{empresa}} neste momento — e está tudo bem!\n\nNão vou mais insistir para não poluir sua caixa de entrada. Se a necessidade surgir no futuro, estarei à disposição.',
    variables: ['primeiro_nome', 'empresa', 'servico'],
    notes: 'Gera alta taxa de resposta por encerramento de cadência.',
    isDefault: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp-1',
    name: 'Prospecção Q3 - Diretores de Operações B2B',
    description: 'Campanha ativa de prospecção fria focada em consultoria comercial e tecnologia.',
    targetAudience: 'Diretores e Sócios de empresas de serviços e logística',
    status: 'active',
    serviceId: 'srv-1',
    defaultTemplateId: 'tpl-1',
    channel: 'whatsapp',
    dailyGoal: 10,
    totalTarget: 50,
    startDate: new Date().toISOString().slice(0, 10),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const todayStr = new Date().toISOString().slice(0, 10);
const yesterdayStr = new Date(Date.now() - 86400000).toISOString().slice(0, 10);

export const SEED_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Logística Drummond & Co',
    tradeName: 'Drummond Logística',
    category: 'Serviços B2B',
    niche: 'Logística & Transporte',
    country: 'Brasil',
    city: 'São Paulo',
    address: 'Av. Paulista, 1578 - Bela Vista',
    website: 'https://drummondlog.com.br',
    instagram: '@drummondlog',
    facebook: 'facebook.com/drummondlog',
    linkedin: 'linkedin.com/company/drummond-log',
    googleBusiness: 'g.page/drummond-logistica',
    unitsCount: 4,
    notes: 'Empresa sólida com frota própria em expansão. Decisor direto com interesse em processos.',
    status: 'lead',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Silveira Tech Solutions LTDA',
    tradeName: 'Silveira Tech',
    category: 'Tecnologia',
    niche: 'Tecnologia & SaaS',
    country: 'Brasil',
    city: 'Rio de Janeiro',
    address: 'Rua do Ouvidor, 100 - Centro',
    website: 'https://silveiratech.io',
    instagram: '@silveiratech',
    linkedin: 'linkedin.com/company/silveira-tech',
    googleBusiness: 'g.page/silveiratech',
    unitsCount: 1,
    notes: 'Startup B2B em tração. Buscam modernizar sistemas internos e portais de clientes.',
    status: 'lead',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Albuquerque & Associados Advocacia',
    tradeName: 'Albuquerque Advogados',
    category: 'Jurídico',
    niche: 'Advocacia & Jurídico',
    country: 'Brasil',
    city: 'Belo Horizonte',
    address: 'Av. Afonso Pena, 3000 - Funcionários',
    website: 'https://albuquerqueadv.com.br',
    linkedin: 'linkedin.com/company/albuquerque-adv',
    googleBusiness: 'g.page/albuquerque-advocacia',
    unitsCount: 2,
    notes: 'Escritório corporativo focado em direito tributário e empresarial.',
    status: 'lead',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Grupo Horizonte Varejo S/A',
    tradeName: 'Horizonte Varejo',
    category: 'Varejo & Distribuição',
    niche: 'E-commerce & Varejo',
    country: 'Brasil',
    city: 'Curitiba',
    address: 'Rua XV de Novembro, 450 - Centro',
    website: 'https://grupo-horizonte.com.br',
    instagram: '@horizontevarejo',
    facebook: 'facebook.com/horizontevarejo',
    linkedin: 'linkedin.com/company/grupo-horizonte',
    googleBusiness: 'g.page/horizonte-varejo',
    unitsCount: 12,
    notes: 'Grande rede com forte operação omnichannel. Excelente potencial de LTV.',
    status: 'client',
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    companyId: 'comp-1',
    name: 'Carlos Drummond',
    role: 'Diretor Comercial & Operações',
    phone: '(11) 98765-4321',
    whatsapp: '11987654321',
    email: 'carlos@drummondlog.com.br',
    notes: 'Prefere receber mensagens diretas pelo WhatsApp no início da manhã.',
    isPrimary: true,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cnt-2',
    companyId: 'comp-2',
    name: 'Mariana Silveira',
    role: 'CEO & Co-fundadora',
    phone: '(21) 99876-5432',
    whatsapp: '21998765432',
    email: 'mariana@silveiratech.io',
    notes: 'Muito receptiva, focada em métricas de conversão e velocidade de entrega.',
    isPrimary: true,
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cnt-3',
    companyId: 'comp-3',
    name: 'Rodrigo Albuquerque',
    role: 'Sócio Gestor',
    phone: '(31) 97654-3210',
    whatsapp: '31976543210',
    email: 'rodrigo@albuquerqueadv.com.br',
    notes: 'Abordagem precisa ser consultiva e executiva.',
    isPrimary: true,
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cnt-4',
    companyId: 'comp-4',
    name: 'Fernanda Montenegro Santos',
    role: 'Head de Inovação & Digital',
    phone: '(11) 97123-4567',
    whatsapp: '11971234567',
    email: 'fernanda@grupo-horizonte.com.br',
    notes: 'Lidera a transformação digital e contratação de parceiros de tecnologia.',
    isPrimary: true,
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cnt-5',
    companyId: 'comp-4',
    name: 'Lucas Brandão',
    role: 'Gerente de TI',
    phone: '(11) 97890-1234',
    whatsapp: '11978901234',
    email: 'lucas.ti@grupo-horizonte.com.br',
    notes: 'Responsável pela validação técnica de arquitetura e segurança.',
    isPrimary: false,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead-1',
    companyId: 'comp-1',
    contactId: 'cnt-1',
    serviceId: 'srv-1',
    serviceName: 'Consultoria de Estruturação Comercial',
    source: 'Outbound Direto',
    score: 85,
    priority: 'alta',
    temperature: 'quente',
    stage: 'NOVO',
    status: 'active',
    entryDate: new Date(Date.now() - 86400000 * 5).toISOString().slice(0, 10),
    lastContactDate: undefined,
    nextActionTitle: 'Enviar WhatsApp de primeiro contato',
    nextActionDate: todayStr,
    nextActionChannel: 'whatsapp',
    notes: 'Identificado via LinkedIn Sales Navigator. Decisor de alta prioridade.',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    companyId: 'comp-2',
    contactId: 'cnt-2',
    serviceId: 'srv-2',
    serviceName: 'Desenvolvimento de Aplicações Web Modernas',
    source: 'LinkedIn Prospecção',
    score: 92,
    priority: 'alta',
    temperature: 'quente',
    stage: 'RESPONDEU',
    status: 'active',
    entryDate: new Date(Date.now() - 86400000 * 8).toISOString().slice(0, 10),
    lastContactDate: yesterdayStr,
    nextActionTitle: 'Enviar mensagem de follow-up pós-resposta',
    nextActionDate: todayStr,
    nextActionChannel: 'whatsapp',
    notes: 'Respondeu demonstrando interesse na arquitetura offline e PWA.',
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    companyId: 'comp-3',
    contactId: 'cnt-3',
    serviceId: 'srv-1',
    serviceName: 'Consultoria de Estruturação Comercial',
    source: 'Google Maps / Google Meu Negócio',
    score: 65,
    priority: 'média',
    temperature: 'morno',
    stage: 'NOVO',
    status: 'active',
    entryDate: new Date(Date.now() - 86400000 * 3).toISOString().slice(0, 10),
    lastContactDate: undefined,
    nextActionTitle: 'Primeiro contato com apresentação executiva',
    nextActionDate: todayStr,
    nextActionChannel: 'whatsapp',
    notes: 'Buscando automação para captação de clientes corporativos.',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-4',
    companyId: 'comp-4',
    contactId: 'cnt-4',
    serviceId: 'srv-2',
    serviceName: 'Desenvolvimento de Aplicações Web Modernas',
    source: 'Indicação de Cliente',
    score: 98,
    priority: 'alta',
    temperature: 'quente',
    stage: 'QUALIFICADO',
    status: 'active',
    entryDate: new Date(Date.now() - 86400000 * 14).toISOString().slice(0, 10),
    lastContactDate: yesterdayStr,
    nextActionTitle: 'Confirmar horário da demonstração técnica',
    nextActionDate: todayStr,
    nextActionChannel: 'whatsapp',
    notes: 'Projeto aprovado pela diretoria, aguardando call de alinhamento técnico.',
    createdAt: new Date(Date.now() - 86400000 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_HISTORY: HistoryEvent[] = [
  {
    id: 'hist-1',
    companyId: 'comp-1',
    contactId: 'cnt-1',
    leadId: 'lead-1',
    type: 'created',
    title: 'Empresa e Lead cadastrados',
    description: 'Lead captado via prospecção outbound.',
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'hist-2',
    companyId: 'comp-2',
    contactId: 'cnt-2',
    leadId: 'lead-2',
    type: 'contact_made',
    title: 'Primeiro contato realizado via WhatsApp',
    description: 'Enviada mensagem inicial apresentando cases de tecnologia web.',
    timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'hist-3',
    companyId: 'comp-2',
    contactId: 'cnt-2',
    leadId: 'lead-2',
    type: 'stage_change',
    title: 'Avanço de estágio: NOVO ➔ RESPONDEU',
    description: 'Mariana respondeu com interesse em agendar diagnóstico.',
    timestamp: yesterdayStr,
  },
  {
    id: 'hist-4',
    companyId: 'comp-4',
    contactId: 'cnt-4',
    leadId: 'lead-4',
    type: 'stage_change',
    title: 'Avanço de estágio: PRIMEIRO_CONTACTO ➔ QUALIFICADO',
    description: 'Perfil altamente qualificado para desenvolvimento de app.',
    timestamp: yesterdayStr,
  },
];

export const SEED_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Carlos Drummond',
    company: 'Logística Drummond & Co',
    role: 'Diretor Comercial',
    phone: '11987654321',
    whatsapp: '11987654321',
    email: 'carlos@drummondlog.com.br',
    segment: 'Logística & Transporte',
    status: 'new',
    stageId: 'stage-new',
    campaignId: 'cmp-1',
    serviceIds: ['srv-1'],
    notes: 'Lead quente identificado via LinkedIn. Empresa expandindo frota.',
    tags: ['Decisor', 'Lead Frio', 'Q3'],
    nextFollowUpDate: todayStr,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cli-2',
    name: 'Mariana Silveira',
    company: 'Silveira Tech Solutions',
    role: 'CEO',
    phone: '21998765432',
    whatsapp: '21998765432',
    email: 'mariana@silveiratech.io',
    linkedinUrl: 'https://linkedin.com/in/marianasilveira',
    segment: 'SaaS / Tecnologia',
    status: 'in_contact',
    stageId: 'stage-contacted',
    campaignId: 'cmp-1',
    serviceIds: ['srv-2'],
    notes: 'Interessada em reformular o portal de clientes. Pediu follow-up hoje.',
    tags: ['Alta Prioridade', 'SaaS'],
    lastContactedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    nextFollowUpDate: todayStr,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cli-3',
    name: 'Rodrigo Albuquerque',
    company: 'Albuquerque & Associados',
    role: 'Sócio Fundador',
    phone: '31976543210',
    whatsapp: '31976543210',
    email: 'rodrigo@albuquerqueadv.com.br',
    segment: 'Serviços Jurídicos',
    status: 'new',
    stageId: 'stage-new',
    campaignId: 'cmp-1',
    serviceIds: ['srv-1'],
    notes: 'Buscando automação para captação de clientes corporativos.',
    tags: ['Lead Frio'],
    nextFollowUpDate: todayStr,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cli-4',
    name: 'Fernanda Montenegro Santos',
    company: 'Grupo Horizonte Varejo',
    role: 'Head de Inovação',
    phone: '11971234567',
    whatsapp: '11971234567',
    email: 'fernanda@grupo-horizonte.com.br',
    segment: 'Varejo Multicanal',
    status: 'qualified',
    stageId: 'stage-qualified',
    campaignId: 'cmp-1',
    serviceIds: ['srv-2'],
    notes: 'Respondeu muito bem ao primeiro contato. Agendar demonstração.',
    tags: ['Qualificado', 'Projeto Grande'],
    lastContactedAt: new Date(Date.now() - 86400000).toISOString(),
    nextFollowUpDate: todayStr,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SEED_ACTIONS: ProspectAction[] = [
  {
    id: 'act-1',
    clientId: 'cli-1',
    campaignId: 'cmp-1',
    templateId: 'tpl-1',
    channel: 'whatsapp',
    scheduledDate: todayStr,
    status: 'pending',
    priority: 'high',
    estMinutes: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-2',
    clientId: 'cli-2',
    campaignId: 'cmp-1',
    templateId: 'tpl-2',
    channel: 'whatsapp',
    scheduledDate: todayStr,
    status: 'pending',
    priority: 'high',
    estMinutes: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-3',
    clientId: 'cli-3',
    campaignId: 'cmp-1',
    templateId: 'tpl-1',
    channel: 'whatsapp',
    scheduledDate: todayStr,
    status: 'pending',
    priority: 'medium',
    estMinutes: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act-4',
    clientId: 'cli-4',
    campaignId: 'cmp-1',
    templateId: 'tpl-2',
    channel: 'whatsapp',
    scheduledDate: todayStr,
    status: 'pending',
    priority: 'high',
    estMinutes: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
