import { ScriptStepDefinition } from '../types/scripts';

export const PROBLEMA_IDENTIFICADO_STEPS: ScriptStepDefinition[] = [
  {
    id: 'prob-step-1',
    stepNumber: 1,
    title: 'ETAPA 1 — Primeira Mensagem',
    flowType: 'problema_identificado',
    category: 'Abertura & Atenção',
    objective: 'Chamar atenção, demonstrar personalização real, criar curiosidade e obter primeira interação sem tentar vender.',
    purposeDescription: 'Mensagem curta com contexto + observação específica + curiosidade + pergunta simples.',
    isInitialContact: true,
    requiresResponse: true,
    roleTarget: 'indeterminado',
    scriptTemplate: 'Olá, {{primeiro_nome}}. Encontrei a {{empresa}} e reparei em {{observacao_especifica}}. Fiquei com uma dúvida rápida: você cuida dessa parte da empresa ou poderia me indicar quem é o responsável?',
    countryVariations: {
      BR: 'Olá, {{primeiro_nome}}. Encontrei a {{empresa}} e reparei em {{observacao_especifica}}. Fiquei com uma dúvida rápida: você cuida dessa parte da empresa ou poderia me indicar quem é o responsável?',
      PT: 'Olá, {{primeiro_nome}}. Encontrei a {{empresa}} e reparei em {{observacao_especifica}}. Fiquei com uma dúvida rápida: é o responsável por esta área ou poderia indicar-me quem trata deste assunto?',
      MZ: 'Olá, {{primeiro_nome}}. Encontrei a {{empresa}} e reparei em {{observacao_especifica}}. Gostaria de saber se é o responsável por esta área ou se me pode indicar a pessoa encarregada?',
    },
    alternativeTemplates: {
      consultivo: 'Olá, {{primeiro_nome}}! Estive a analisar o posicionamento online da {{empresa}} e notei que {{observacao_especifica}}. Para eu direcionar da melhor forma: é você quem acompanha essa área ou teria outra pessoa responsável?',
      direto: 'Olá, {{primeiro_nome}}. Vi a {{empresa}} no Google e notei que {{observacao_especifica}}. Você é quem cuida disso diretamente ou me indica o responsável?',
      casual: 'Oi, {{primeiro_nome}}, tudo bem? Achei a {{empresa}} e vi um detalhe em {{observacao_especifica}}. É você quem toca essa parte ou me recomenda falar com outra pessoa?',
    },
    dosAndDonts: {
      do: ['Mensagem curta', 'Citar observação real registrada', 'Perguntar quem é o responsável'],
      dont: ['Enviar preço', 'Apresentar lista de serviços', 'Fazer promessas falsas', 'Textos longos'],
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '4–8 horas',
        intervalHours: 6,
        message: 'Oi, {{primeiro_nome}}, passando só para confirmar se recebeu a mensagem acima. Conseguiu ver?',
        objective: 'Relembrar de forma ultra leve sem pressionar',
        tone: 'casual',
        condition: 'Quando a primeira mensagem não obteve retorno no mesmo dia útil',
        whenNotToUse: 'Se o contato respondeu ou recusou',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Olá, {{primeiro_nome}}. Imagino que sua rotina na {{empresa}} esteja corrida. Só queria confirmar se esse canal é o melhor para falar sobre {{observacao_especifica}} ou se prefere por e-mail.',
        objective: 'Validar o canal e manter porta aberta',
        tone: 'consultivo',
        condition: '1 dia sem resposta após tentativa inicial',
        whenNotToUse: 'Fora do horário comercial',
      },
      {
        number: 3,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Tentei contato antes pois identifiquei um ponto bem pontual em {{observacao_especifica}} da {{empresa}}. Vale 2 minutos de conversa?',
        objective: 'Reforçar o valor da observação específica',
        tone: 'direto',
        condition: '2 dias sem interação',
        whenNotToUse: 'Se o contato estiver de férias/ausente',
      },
      {
        number: 4,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}. Queria apenas evitar insistir sem necessidade. Essa melhoria em {{observacao_especifica}} é algo que a {{empresa}} pretende olhar agora ou não é o momento?',
        objective: 'Desarmar objeção de timing de forma educada',
        tone: 'profissional',
        condition: '4 dias de silêncio',
        whenNotToUse: 'Se já foi marcado Não Contactar',
      },
      {
        number: 5,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi, {{primeiro_nome}}. Como não tive retorno, imaginei que o foco agora seja outro na {{empresa}}. Se fizer sentido retomar no futuro, continuo por aqui!',
        objective: 'Quebra de padrão elegante (fechamento de loop suave)',
        tone: 'consultivo',
        condition: '1 semana sem resposta',
        whenNotToUse: 'Se houve resposta negativa',
      },
      {
        number: 6,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}! Lembra do ponto em {{observacao_especifica}} que comentei na {{empresa}}? Surgiu uma novidade prática nessa área e lembrei de você. Posso mandar em 30 segundos?',
        objective: 'Tentativa de reativação com novidade prática',
        tone: 'casual',
        condition: 'Após 2 semanas de silêncio antes de arquivar',
        whenNotToUse: 'Se o cliente pediu para não mandar mensagem',
      },
    ],
  },
  {
    id: 'prob-step-2',
    stepNumber: 2,
    title: 'ETAPA 2 — Descobrir se é Funcionário ou Responsável',
    flowType: 'problema_identificado',
    category: 'Qualificação de Interlocutor',
    objective: 'Identificar se o interlocutor tem poder de decisão ou se deve ser redirecionado para a rota funcionário.',
    purposeDescription: 'Verificação rápida de papel na empresa para direcionar o fluxo correto.',
    requiresResponse: true,
    scriptTemplate: 'Obrigado pelo retorno, {{primeiro_nome}}! Para eu te passar as informações certas: você é quem toma as decisões sobre {{servico}} na {{empresa}} ou atua junto com outra pessoa?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '6–8 horas',
        intervalHours: 8,
        message: 'Oi {{primeiro_nome}}, se for mais fácil, posso falar diretamente com a pessoa encarregada dessa parte aí na {{empresa}}.',
        objective: 'Facilitar a resposta sem travar a conversa',
        tone: 'casual',
        condition: 'Quando a pessoa visualizou e não respondeu o cargo',
        whenNotToUse: 'Se já esclareceu que é o dono',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, pergunto porque não quero tomar seu tempo se essa responsabilidade for de outro setor na {{empresa}}.',
        objective: 'Mostrar respeito pelo tempo do interlocutor',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se houve recusa expressa',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Conseguiria me passar o contato de quem normalmente cuida de {{servico}} aí na {{empresa}}?',
        objective: 'Pedido direto de contato',
        tone: 'direto',
        condition: 'Após 3 dias',
        whenNotToUse: 'Se for o próprio decisor',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se preferir, posso enviar um e-mail formal para a diretoria da {{empresa}}. Qual seria o melhor endereço?',
        objective: 'Alternativa formal para e-mail',
        tone: 'formal',
        condition: 'Sem retorno no WhatsApp',
        whenNotToUse: 'Se já tem o e-mail do decisor',
      },
      {
        number: 5,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Olá, {{primeiro_nome}}. Vou deixar anotado para tentar contato com a equipe da {{empresa}} em outro momento. Um abraço!',
        objective: 'Pausa educada',
        tone: 'profissional',
        condition: 'Sem resposta após 10 dias',
        whenNotToUse: 'Se engajou na conversa',
      },
      {
        number: 6,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Oi {{primeiro_nome}}, tudo bem? Tivemos uma atualização sobre {{servico}} que pode interessar à {{empresa}}. Quem seria a melhor pessoa para ver?',
        objective: 'Tentativa final de roteamento',
        tone: 'casual',
        condition: 'Reativação após 20 dias',
        whenNotToUse: 'DNC ativo',
      },
    ],
  },
  {
    id: 'prob-step-3',
    stepNumber: 3,
    title: 'ETAPA 3 — Rota Funcionário (Agradecimento & Motivo)',
    flowType: 'problema_identificado',
    category: 'Rota Funcionário',
    objective: 'Agradecer, explicar brevemente o motivo sem jargão e pedir indicação do responsável.',
    purposeDescription: 'Quando o interlocutor diz "não sou eu quem cuida disso", "trabalho na recepção", etc.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}, muito obrigado! Estou entrando em contato porque identifiquei que {{observacao_especifica}} na {{empresa}}. Quem normalmente cuida dessa parte aí com vocês?',
    alternativeTemplates: {
      consultivo: 'Entendido, {{primeiro_nome}}, agradeço pela transparência! É que notei um ponto prático em {{observacao_especifica}} que pode estar fazendo a {{empresa}} perder clientes. Você saberia me dizer quem é o responsável por isso?',
      direto: 'Obrigado, {{primeiro_nome}}! Quem é a pessoa na {{empresa}} responsável por aprovar melhorias em {{servico}}?',
      casual: 'Sem problemas, {{primeiro_nome}}! Quem aí na {{empresa}} costuma ver essa parte de site e internet?',
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '8 horas',
        intervalHours: 8,
        message: 'Se for mais simples, pode ser só o primeiro nome ou o e-mail da pessoa na {{empresa}}.',
        objective: 'Diminuir o esforço do funcionário',
        tone: 'casual',
        condition: 'Funcionário parou de responder',
        whenNotToUse: 'Se disse que não pode passar',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi, {{primeiro_nome}}! Conseguiu verificar quem cuida dessa área na {{empresa}}?',
        objective: 'Checagem amigável',
        tone: 'consultivo',
        condition: '1 dia sem retorno',
        whenNotToUse: 'Se recusou expressamente',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, posso ligar rapidinho no fixo da {{empresa}} e pedir para falar com o responsável por {{servico}}? Qual o melhor ramal?',
        objective: 'Alternativa de transição para ligação',
        tone: 'direto',
        condition: '3 dias sem resposta',
        whenNotToUse: 'Se não há número fixo',
      },
      {
        number: 4,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Oi, {{primeiro_nome}}. Como não quero atrapalhar seu expediente, se puder me passar apenas o contato do gestor, eu falo diretamente com ele!',
        objective: 'Alívio de responsabilidade do funcionário',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'Se já passou o contato',
      },
      {
        number: 5,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Olá, {{primeiro_nome}}. Agradeço a atenção até aqui! Caso o responsável queira avaliar melhorias em {{servico}}, estou à disposição.',
        objective: 'Encerramento educado',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se passou o contato',
      },
      {
        number: 6,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Conseguiram definir quem responde por {{servico}} na {{empresa}}?',
        objective: 'Recontato posterior',
        tone: 'casual',
        condition: '20 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-4',
    stepNumber: 4,
    title: 'ETAPA 4 — Encaminhamento para Responsável',
    flowType: 'problema_identificado',
    category: 'Rota Funcionário',
    objective: 'Facilitar o encaminhamento e obter nome/telefone direto ou autorização para ser apresentado.',
    purposeDescription: 'Facilitador de transição para falar com o tomador de decisão.',
    scriptTemplate: 'Se for mais fácil para você, {{primeiro_nome}}, pode me indicar o nome e o WhatsApp dele(a)? Prometo ser super direto e objetivo.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi, {{primeiro_nome}}! Se preferir, posso te enviar um texto pronto para você apenas encaminhar para seu gestor.',
        objective: 'Entregar mensagem pronta para encaminhamento',
        tone: 'consultivo',
        condition: 'Funcionário com receio de passar contato',
        whenNotToUse: 'Se já forneceu o número',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, segue um resumo de 2 linhas caso queira repassar: "Olá [Nome Gestor], um profissional identificou uma oportunidade de melhoria em {{observacao_especifica}} da {{empresa}} e pediu autorização para mostrar um exemplo rápido."',
        objective: 'Mensagem formatada para o funcionário copiar',
        tone: 'direto',
        condition: '2 dias sem envio do contato',
        whenNotToUse: 'Se já conectou ao decisor',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Oi, {{primeiro_nome}}, conseguiu repassar para o responsável na {{empresa}}?',
        objective: 'Follow-up de encaminhamento',
        tone: 'casual',
        condition: '5 dias após envio do resumo',
        whenNotToUse: 'Se contato já recebido',
      },
      {
        number: 4,
        intervalRecommended: '8 dias',
        intervalHours: 192,
        message: 'Olá, {{primeiro_nome}}. Caso seu gestor tenha interesse, meu WhatsApp é este mesmo. Fico à disposição!',
        objective: 'Fixação de canal',
        tone: 'profissional',
        condition: '8 dias sem retorno',
        whenNotToUse: 'DNC',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Chegou a conversar com a diretoria sobre {{observacao_especifica}}?',
        objective: 'Checagem final',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}! Um abraço a toda equipe da {{empresa}}. Se precisarem de apoio em {{servico}}, contem comigo.',
        objective: 'Arquivo amigável',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
    ],
  },
  {
    id: 'prob-step-5',
    stepNumber: 5,
    title: 'ETAPA 5 — Responsável Identificado (Microcompromisso)',
    flowType: 'problema_identificado',
    category: 'Interação com Decisor',
    objective: 'Criar um microcompromisso sem jogar parede de texto.',
    purposeDescription: 'Nunca apresentar proposta de imediato. Pedir permissão para fazer uma pergunta rápida.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}! Posso te fazer uma pergunta bem rápida antes de te mostrar o motivo exato do contato sobre a {{empresa}}?',
    countryVariations: {
      BR: 'Perfeito, {{primeiro_nome}}! Posso te fazer uma pergunta bem rápida antes de te mostrar o motivo exato do contato sobre a {{empresa}}?',
      PT: 'Excelente, {{primeiro_nome}}! Posso fazer-lhe uma pergunta muito rápida antes de explicar o motivo específico do contacto sobre a {{empresa}}?',
      MZ: 'Perfeito, {{primeiro_nome}}! Posso fazer uma pergunta bem rápida antes de lhe mostrar o motivo do contacto sobre a {{empresa}}?',
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '6–8 horas',
        intervalHours: 8,
        message: 'É bem rápida mesmo, {{primeiro_nome}}, prometo não tomar mais de 1 minuto do seu tempo.',
        objective: 'Alívio de fricção de tempo',
        tone: 'casual',
        condition: 'Decisor visualizou e não autorizou a pergunta',
        whenNotToUse: 'Se respondeu "não"',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, pergunto porque tem relação direta com como os clientes encontram a {{empresa}} hoje na internet. Posso te perguntar?',
        objective: 'Adicionar curiosidade com foco no negócio',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Imagino a correria. Quando tiver 30 segundos, me avise por aqui!',
        objective: 'Leveza e respeito',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se já respondeu',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Se preferir que eu vá direto ao ponto e te mostre o que notei em {{observacao_especifica}}, é só me avisar.',
        objective: 'Oferta de ir direto ao ponto',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 5,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Olá, {{primeiro_nome}}. Vou pausar por aqui para não te incomodar. Se quiser avaliar {{servico}} no futuro, estarei por aqui!',
        objective: 'Fechamento suave de loop',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}! Tudo bem por aí? Passando só para saber se a {{empresa}} já conseguiu resolver a parte de {{observacao_especifica}}.',
        objective: 'Tentativa de reativação pontual',
        tone: 'casual',
        condition: '20 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-6',
    stepNumber: 6,
    title: 'ETAPA 6 — Investigação',
    flowType: 'problema_identificado',
    category: 'Diagnóstico & Descoberta',
    objective: 'Compreender como a empresa opera atualmente na área do problema identificado.',
    purposeDescription: 'Pergunta aberta sobre o processo atual.',
    scriptTemplate: 'Legal! Como vocês fazem para captar ou atender os clientes que chegam pela internet na {{empresa}} atualmente?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi, {{primeiro_nome}}, pergunto porque notei que hoje a maior parte dos clientes pode estar caindo sem atendimento imediato. É isso que acontece?',
        objective: 'Ajudar o lead a contextualizar a resposta',
        tone: 'consultivo',
        condition: '1 dia sem resposta à pergunta',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Vocês sentem que o canal digital hoje traz clientes suficientes ou gostariam de mais previsibilidade?',
        objective: 'Pergunta fechada de menor atrito',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Sei que seu dia a dia é corrido. Se puder responder em 1 palavra: seu site hoje te traz clientes todo mês?',
        objective: 'Pergunta de 1 palavra',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 4,
        intervalRecommended: '8 dias',
        intervalHours: 192,
        message: 'Oi {{primeiro_nome}}, se fizer mais sentido, posso te mandar um áudio de 40 segundos explicando o que vi na {{empresa}}.',
        objective: 'Oferta de áudio curto',
        tone: 'consultivo',
        condition: '8 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Como não conversamos, imagino que essa parte não seja prioridade neste momento na {{empresa}}. Tudo bem!',
        objective: 'Respeito ao timing',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}! Passando apenas para saber se vocês fizeram alguma mudança recente no site da {{empresa}}.',
        objective: 'Recontato de acompanhamento',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-7',
    stepNumber: 7,
    title: 'ETAPA 7 — Diagnóstico (Perguntas Adaptáveis)',
    flowType: 'problema_identificado',
    category: 'Diagnóstico Profundo',
    objective: 'Identificar Ponto A (situação atual), Ponto B (situação desejada) e Ponto C (consequências de não mudar).',
    purposeDescription: 'Perguntas adaptáveis. NÃO enviar mensagem seguinte antes da resposta.',
    diagnosticPoints: {
      pointA: 'Situação atual: site sem agendamento direto, desatualizado ou lento.',
      pointB: 'Situação desejada: clientes agendando facilmente pelo WhatsApp / site.',
      pointC: 'Consequência: clientes procuram concorrentes ou desistem da contratação.',
    },
    scriptTemplate: 'Entendido! Se você pudesse melhorar apenas uma coisa nessa parte digital da {{empresa}} hoje, qual seria a sua prioridade?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, muitos gestores me dizem que a prioridade é [ex: receber mensagens mais qualificadas no WhatsApp]. Na {{empresa}} é algo parecido?',
        objective: 'Dar exemplo para facilitar a resposta',
        tone: 'consultivo',
        condition: 'Lead não soube o que responder',
        whenNotToUse: 'Se já detalhou o problema',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, isso acaba gerando alguma dificuldade para vocês no dia a dia ou o processo atual atende bem?',
        objective: 'Investigar consequência real',
        tone: 'direto',
        condition: '3 dias sem resposta',
        whenNotToUse: 'Se já respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Essa melhoria é algo que vocês pretendem resolver neste trimestre ou mais para frente?',
        objective: 'Checar urgência e timing',
        tone: 'profissional',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '9 dias',
        intervalHours: 216,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico pensando se vocês já tentaram resolver isso antes e não deu certo.',
        objective: 'Entender frustrações passadas',
        tone: 'casual',
        condition: '9 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Vou deixar anotado por aqui para não te sobrecarregar. Um abraço!',
        objective: 'Fechamento de ciclo',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Surgiu alguma novidade sobre a estratégia digital da {{empresa}}?',
        objective: 'Reativação a longo prazo',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-8',
    stepNumber: 8,
    title: 'ETAPA 8 — Validação do Problema',
    flowType: 'problema_identificado',
    category: 'Validação',
    objective: 'Confirmar entendimento dos Pontos A, B e C antes de oferecer qualquer solução.',
    purposeDescription: 'Espelhar a dor do cliente com as próprias palavras dele sem exageros.',
    scriptTemplate: 'Deixa ver se entendi perfeitamente, {{primeiro_nome}}: hoje a {{empresa}} está em {{ponto_a}}, e o ideal seria {{ponto_b}}, mas o problema é que {{ponto_c}}. É exatamente isso ou esqueci de algum detalhe?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, faz sentido esse resumo que fiz acima ou a realidade da {{empresa}} é diferente?',
        objective: 'Estimular validação simples',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se validou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se tiver algum ponto que não ficou claro, me avise para eu ajustar!',
        objective: 'Humildade e escuta ativa',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Queria só ter certeza de que estamos na mesma página antes de te sugerir qualquer caminho.',
        objective: 'Demonstrar profissionalismo consultivo',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Quando puder me dar um toque se o resumo acima reflete o momento da {{empresa}}, te agradeço.',
        objective: 'Follow-up leve',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou pausar por aqui para respeitar seu tempo. Até uma próxima oportunidade!',
        objective: 'Pausa estruturada',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Lembra do ponto que conversamos sobre {{ponto_a}}? Como ficou essa questão na {{empresa}}?',
        objective: 'Reativação contextual',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-9',
    stepNumber: 9,
    title: 'ETAPA 9 — Apresentação da Solução',
    flowType: 'problema_identificado',
    category: 'Solução sob Medida',
    objective: 'Apresentar somente a solução ligada ao problema validado, com benefício realista.',
    purposeDescription: 'Não despejar todos os serviços. Foco cirúrgico na necessidade confirmada.',
    scriptTemplate: 'Entendi perfeitamente. Pelo que você me explicou, acredito que o principal ponto seja resolver {{problema}}. Minha ideia para a {{empresa}} seria implementar {{solucao}}, o que permitiria {{beneficio_realista}}. Faz sentido para você?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o que achou desse caminho para a {{empresa}}? Faz sentido na sua visão?',
        objective: 'Checar alinhamento',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se aprovou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, se você tiver alguma dúvida técnica ou sobre como isso funciona na prática, me diga que eu te explico em 1 minuto.',
        objective: 'Tirar dúvidas de viabilidade',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Gostaria de saber se você vê valor nessa abordagem para a {{empresa}} ou se pensou em algo diferente.',
        objective: 'Explorar alternativas na mente do cliente',
        tone: 'profissional',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Caso essa solução não seja a prioridade agora, sem problemas! Podemos conversar em outro momento.',
        objective: 'Descompressão',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar meus contatos por aqui para não te incomodar. Um abraço!',
        objective: 'Fechamento de loop',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '28 dias',
        intervalHours: 672,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Tive uma ideia complementar para {{solucao}} na {{empresa}} e lembrei da nossa conversa. Vale 2 minutos?',
        objective: 'Reativação com ideia nova',
        tone: 'casual',
        condition: '28 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-10',
    stepNumber: 10,
    title: 'ETAPA 10 — Pedido de Autorização para Mostrar Exemplo',
    flowType: 'problema_identificado',
    category: 'Demonstração & Protótipo',
    objective: 'Pedir permissão explícita antes de enviar a demonstração ou protótipo.',
    purposeDescription: 'Gera microcompromisso e curiosidade sem parecer invasivo.',
    scriptTemplate: 'Eu preparei um exemplo pensando especificamente na realidade da {{empresa}}. Se você quiser, posso te enviar para você me dizer o que acha. Posso mandar por aqui?',
    countryVariations: {
      BR: 'Eu preparei um exemplo pensando especificamente na realidade da {{empresa}}. Se você quiser, posso te enviar para você me dizer o que acha. Posso mandar por aqui?',
      PT: 'Preparei um exemplo a pensar especificamente na realidade da {{empresa}}. Se quiser, posso enviar-lhe para me dizer o que acha. Posso enviar por aqui?',
      MZ: 'Preparei um exemplo a pensar na realidade da {{empresa}}. Se concordar, posso enviar por aqui para me dar a sua opinião. Posso mandar?',
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '4–8 horas',
        intervalHours: 8,
        message: 'É um link bem simples e visual, {{primeiro_nome}}, dá para ver direto no celular.',
        objective: 'Reduzir barreira técnica',
        tone: 'casual',
        condition: 'Visualizou e não respondeu autorização',
        whenNotToUse: 'Se autorizou',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, se preferir eu te mando só um print rápido de 1 tela para não tomar tempo. O que acha?',
        objective: 'Alternativa ainda mais leve (print)',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! O exemplo está pronto por aqui. Se ainda tiver interesse em ver, é só me dar um ok!',
        objective: 'Disponibilidade sem pressão',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vou guardar o exemplo por aqui. Quando tiver um momento mais tranquilo na {{empresa}}, me avisa!',
        objective: 'Pausa amigável',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}. Para não insistir sem motivo, vou arquivar essa proposta de melhoria. Foi um prazer o contato!',
        objective: 'Fechamento elegante',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Aquele exemplo que estruturei para a {{empresa}} ainda está guardado. Quer dar uma olhada rápida?',
        objective: 'Reativação do protótipo',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-11',
    stepNumber: 11,
    title: 'ETAPA 11 — Envio da Demonstração',
    flowType: 'problema_identificado',
    category: 'Demonstração & Protótipo',
    objective: 'Enviar o protótipo, auditoria ou conceito personalizado com total transparência (sem inventar cases).',
    purposeDescription: 'Regra estrita: nunca inventar clientes, números ou depoimentos. Usar demonstração real.',
    scriptTemplate: 'Aqui está o exemplo que preparei para a {{empresa}}: {{link_demonstracao}}. Repare especialmente em como a parte de {{observacao_especifica}} foi reorganizada para facilitar o contato do cliente.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu abrir o exemplo no seu celular? Funcionou certinho?',
        objective: 'Checagem técnica e de abertura',
        tone: 'casual',
        condition: '1 dia após envio do link',
        whenNotToUse: 'Se já deu feedback',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? O que você achou daquela estrutura que montei para a {{empresa}}?',
        objective: 'Pedido suave de primeira impressão',
        tone: 'consultivo',
        condition: '2 dias sem feedback',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Teve chance de dar uma olhada? Fiquei curioso para saber sua opinião sincera.',
        objective: 'Estimular sinceridade',
        tone: 'direto',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi, {{primeiro_nome}}, sei que a rotina é corrida. Se preferir, me diga apenas o que você achou da primeira dobra da página!',
        objective: 'Facilitar com micro-feedback',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Caso tenha achado que o exemplo não combina com a {{empresa}}, pode me dizer com total franqueza!',
        objective: 'Dar permissão de rejeição para destravar conversa',
        tone: 'consultivo',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vou desativar o link de demonstração da {{empresa}} na próxima semana. Gostaria de salvar alguma parte antes?',
        objective: 'Escassez técnica real (limpeza de protótipo)',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-12',
    stepNumber: 12,
    title: 'ETAPA 12 — Perguntar o que Gostou',
    flowType: 'problema_identificado',
    category: 'Feedback & Co-criação',
    objective: 'Estimular o cliente a verbalizar os pontos positivos da solução.',
    purposeDescription: 'Não perguntar apenas "gostou?". Perguntar especificamente o que mais gostou.',
    scriptTemplate: 'Legal que conseguiu ver, {{primeiro_nome}}! Me diz uma coisa: do que você mais gostou nessa estrutura?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, a parte de [ex: botão direto do WhatsApp / carregamento rápido] fez sentido para o seu perfil de cliente?',
        objective: 'Direcionar para benefício específico',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Fique à vontade para me dizer se achou que ficou profissional para a {{empresa}}.',
        objective: 'Checar percepção de autoridade',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Só queria saber se o exemplo atendeu ao que você esperava.',
        objective: 'Validação de expectativa',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver 1 minuto para me dar seu parecer, fico à disposição.',
        objective: 'Aguardar momento',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar o acompanhamento do protótipo. Agradeço pela atenção!',
        objective: 'Encerramento',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Alguma novidade sobre o projeto da {{empresa}}?',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-13',
    stepNumber: 13,
    title: 'ETAPA 13 — Perguntar o que Gostaria de Melhorar',
    flowType: 'problema_identificado',
    category: 'Feedback & Co-criação',
    objective: 'Dar espaço seguro para o cliente apontar ressalvas e participar da co-criação.',
    purposeDescription: 'Descobre objeções antes da proposta.',
    scriptTemplate: 'E sendo bem sincero, {{primeiro_nome}}: tem alguma parte que você mudaria ou que sente que não combina 100% com a {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Pode ser bem transparente mesmo, {{primeiro_nome}}! Isso ajuda a deixar o projeto com a cara exata da {{empresa}}.',
        objective: 'Incentivar franqueza',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Oi {{primeiro_nome}}, seja cores, textos ou fotos: se tiver algo para ajustar, é super rápido de alinhar.',
        objective: 'Demonstrar flexibilidade',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: '{{primeiro_nome}}, se estiver tudo aprovado como está, também me avise para eu te passar como seria a implementação!',
        objective: 'Ponte para a proposta',
        tone: 'direto',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '9 dias',
        intervalHours: 216,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição caso queira trocar alguma ideia sobre os ajustes.',
        objective: 'Suporte aberto',
        tone: 'profissional',
        condition: '9 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, vou pausar por aqui. Se quiser retomar os ajustes mais para frente, é só chamar!',
        objective: 'Pausa amigável',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}, tudo bem? Tivemos algumas melhorias nessa estrutura que podem ser úteis para a {{empresa}}. Quer ver?',
        objective: 'Reativação de produto',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-14',
    stepNumber: 14,
    title: 'ETAPA 14 — Ajustes',
    flowType: 'problema_identificado',
    category: 'Alinhamento',
    objective: 'Confirmar os ajustes solicitados e preparar o terreno para a proposta comercial.',
    purposeDescription: 'Garante que todos os requisitos foram incorporados.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}! Já incorporei esses pontos: {{ajustes_solicitados}}. Ficou exatamente como você imaginava para a {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu ver as alterações que fiz no link?',
        objective: 'Checar validação dos ajustes',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se validou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, se estiver tudo 100%, posso te passar os detalhes de como colocar no ar e as condições.',
        objective: 'Transição suave para proposta',
        tone: 'consultivo',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Ficou mais alguma dúvida sobre a estrutura ajustada?',
        objective: 'Checar pendências',
        tone: 'direto',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando puder me dar o ok final, te envio o cronograma!',
        objective: 'Avanço de etapa',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Como não tivemos retorno, vou manter o projeto em espera por aqui.',
        objective: 'Aviso de espera',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de retomar a publicação desse projeto na {{empresa}}?',
        objective: 'Reativação comercial',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-15',
    stepNumber: 15,
    title: 'ETAPA 15 — Apresentação da Proposta',
    flowType: 'problema_identificado',
    category: 'Proposta Comercial',
    objective: 'Resumir o problema, a solução e o que será entregue antes de falar o preço.',
    purposeDescription: 'Resumo de valor antes da ancoragem de preço.',
    scriptTemplate: 'Excelente, {{primeiro_nome}}! Resumindo o que combinamos: vamos resolver {{problema}} da {{empresa}} entregando {{escopo_entregas}}. Assim vocês conseguem {{beneficio_principal}}.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, tudo certo com esse escopo? Se estiver ok, já te passo os valores e prazos!',
        objective: 'Confirmação pré-preço',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aprovou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tem mais algum item que você gostaria de incluir no escopo antes do valor final?',
        objective: 'Checar escopo adicional',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Podemos avançar para a parte de valores e datas?',
        objective: 'Pedido de permissão de preço',
        tone: 'profissional',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no seu aguardo para te enviar os detalhes comerciais!',
        objective: 'Lembrete amigável',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Vou deixar a proposta em aberto por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '28 dias',
        intervalHours: 672,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Quando for o momento de tirar esse projeto do papel, conte comigo!',
        objective: 'Reativação',
        tone: 'casual',
        condition: '28 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-16',
    stepNumber: 16,
    title: 'ETAPA 16 — Ancoragem e Contraste',
    flowType: 'problema_identificado',
    category: 'Proposta Comercial',
    objective: 'Apresentar a faixa de referência de mercado e contrastar com a proposta especial do Leadion.',
    purposeDescription: 'Ancoragem justa com justificativa configurável por país/moeda.',
    scriptTemplate: 'Projetos desse tipo, dependendo do nível de desenvolvimento, costumam ficar na faixa de {{preco_ancora}} no mercado. Para este projeto específico da {{empresa}}, o valor que estou propondo é {{preco}}.',
    countryVariations: {
      BR: 'Projetos desse tipo, dependendo do nível de desenvolvimento, costumam ficar na faixa de R$ 2.000 a R$ 3.000 no mercado. Para este projeto específico da {{empresa}}, o valor que estou propondo é R$ 597.',
      PT: 'Projetos deste tipo, dependendo do nível de desenvolvimento, costumam situar-se na faixa de 450 € a 700 € no mercado. Para este projeto específico da {{empresa}}, o valor que proponho é 180 €.',
      MZ: 'Projetos deste tipo, dependendo da complexidade, costumam ficar na faixa de 25.000 a 40.000 MT no mercado. Para este projeto da {{empresa}}, o valor que estou a propor é {{preco}}.',
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o que achou da condição para a {{empresa}}?',
        objective: 'Checar recepção do preço',
        tone: 'consultivo',
        condition: '1 dia após envio do preço',
        whenNotToUse: 'Se já aceitou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, além desse valor especial, consigo incluir [ex: suporte inicial / configuração de domínio] sem custo adicional. Fica bom para vocês?',
        objective: 'Adicionar valor percebido',
        tone: 'direto',
        condition: '2 dias sem retorno',
        whenNotToUse: 'Se contestou preço',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! O valor ficou dentro do que a {{empresa}} tinha planejado investir?',
        objective: 'Diagnóstico de orçamento',
        tone: 'profissional',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Caso precise de facilidades de pagamento ou parcelamento, me avise para eu verificar aqui.',
        objective: 'Oferecer condição de pagamento sem dar desconto',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se fechou',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Como não tivemos retorno sobre a proposta, vou manter essas condições guardadas por 7 dias. Um abraço!',
        objective: 'Aviso de expiração de condição especial',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou o planejamento da {{empresa}} para essa parte.',
        objective: 'Reativação de proposta',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-17',
    stepNumber: 17,
    title: 'ETAPA 17 — Preço & Condições',
    flowType: 'problema_identificado',
    category: 'Fechamento & Negociação',
    objective: 'Formalizar o valor, forma de pagamento e prazos de entrega.',
    purposeDescription: 'Apresentação clara de prazo e termos de aprovação.',
    scriptTemplate: 'O investimento total fica em {{preco}}, com entrega em {{prazo_entrega}} dias. Você aprova o projeto primeiro, e o acerto é feito após a sua validação, conforme combinamos. Como fica melhor para você: Pix, cartão ou transferência?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, tudo certo para iniciarmos ou tem alguma dúvida sobre a forma de pagamento?',
        objective: 'Checar método de pagamento',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se confirmou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, se você preferir, posso reservar sua vaga de início para esta quinta-feira. O que acha?',
        objective: 'Reserva de calendário',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Me avise se podemos dar o pontapé inicial no projeto da {{empresa}}.',
        objective: 'Confirmação de início',
        tone: 'profissional',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '8 dias',
        intervalHours: 192,
        message: 'Oi {{primeiro_nome}}, tudo bem? Algum impedimento para iniciarmos ou ficou alguma pendência?',
        objective: 'Descobrir gargalo',
        tone: 'casual',
        condition: '8 dias',
        whenNotToUse: 'Se fechou',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Vou liberar a agenda por aqui. Quando quiser iniciar, é só me dar um toque!',
        objective: 'Liberação de vaga',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Abrimos um novo lote de projetos para este mês na {{empresa}}. Vamos iniciar?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-18',
    stepNumber: 18,
    title: 'ETAPA 18 — Negociação & Ajuste de Escopo',
    flowType: 'problema_identificado',
    category: 'Negociação',
    objective: 'Negociar de forma ética e consultiva sem desvalorizar o trabalho.',
    purposeDescription: 'Ajustar escopo ou cronograma antes de dar descontos desproporcionais.',
    scriptTemplate: 'Compreendo perfeitamente, {{primeiro_nome}}. Para ajustarmos ao que você precisa hoje na {{empresa}}, podemos fazer uma primeira etapa com {{escopo_reduzido}} por {{preco_ajustado}}. Assim já colocamos no ar e colhemos resultados rápidos. O que acha?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, esse formato mais enxuto fica mais confortável para o caixa da {{empresa}}?',
        objective: 'Validar conforto financeiro',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, o principal é resolver {{problema}} sem pesar no seu orçamento. Podemos fechar dessa forma?',
        objective: 'Relembrar a dor central',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição para adaptarmos como for melhor para a {{empresa}}.',
        objective: 'Abertura negociadora',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver um parecer da diretoria, me avise!',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou congelar essa proposta por enquanto. Um abraço!',
        objective: 'Congelamento',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Tivemos novos recursos disponíveis para {{servico}}. Quer retomar?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-19',
    stepNumber: 19,
    title: 'ETAPA 19 — Fechamento',
    flowType: 'problema_identificado',
    category: 'Fechamento',
    objective: 'Confirmar a decisão e fechar o acordo de forma calorosa e profissional.',
    purposeDescription: 'Confirmação do acordo e alinhamento de próximos passos.',
    scriptTemplate: 'Excelente decisão, {{primeiro_nome}}! Tenho certeza de que a {{empresa}} vai colher ótimos frutos com essa melhoria. Já estou organizando o cronograma de produção.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, só preciso dos dados cadastrais básicos da {{empresa}} para formalizar o início.',
        objective: 'Coleta de dados de início',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, assim que você me enviar o logotipo e informações básicas, já dou o start no ambiente de testes!',
        objective: 'Coleta de ativos',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Passando só para confirmar se conseguiu separar os materiais da {{empresa}}.',
        objective: 'Acompanhamento de materiais',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '9 dias',
        intervalHours: 216,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se precisar de ajuda para exportar o logo ou textos, me avisa que te auxilio.',
        objective: 'Ajuda técnica',
        tone: 'consultivo',
        condition: '9 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Fico no seu aguardo para darmos continuidade ao projeto!',
        objective: 'Lembrete profissional',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vamos dar andamento ao início do projeto da {{empresa}}?',
        objective: 'Reativação de fechamento',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-20',
    stepNumber: 20,
    title: 'ETAPA 20 — Pagamento & Validação',
    flowType: 'problema_identificado',
    category: 'Pagamento',
    objective: 'Instruções de pagamento transparentes e emissão de recibo/comprovante.',
    purposeDescription: 'Clareza total nos dados de pagamento.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}! Seguem os dados para o acerto do projeto da {{empresa}}: {{dados_pagamento}}. Assim que realizar, é só me enviar o comprovante por aqui para eu gerar seu recibo.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu realizar o pagamento ou teve alguma dificuldade com os dados bancários?',
        objective: 'Checar se houve problema técnico',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se pago',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Me avise assim que o financeiro da {{empresa}} fizer a liquidação para eu já emitir sua nota/recibo.',
        objective: 'Acompanhamento financeiro',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Precisa que eu envie os dados em outro formato para o setor financeiro?',
        objective: 'Facilitar trâmite de contas a pagar',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no aguardo do comprovante para liberarmos a entrega final no domínio oficial!',
        objective: 'Lembrete de liberação',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Caso tenha havido qualquer imprevisto com o pagamento, me avise para vermos uma alternativa.',
        objective: 'Compreensão de imprevisto',
        tone: 'consultivo',
        condition: '16 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para regularizarmos a pendência do projeto da {{empresa}}.',
        objective: 'Regularização financeira',
        tone: 'direto',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-21',
    stepNumber: 21,
    title: 'ETAPA 21 — Início do Projeto',
    flowType: 'problema_identificado',
    category: 'Onboarding & Produção',
    objective: 'Alinhar expectativas, canais de comunicação e cronograma de entrega.',
    purposeDescription: 'Boas-vindas operacionais e início da execução.',
    scriptTemplate: 'Pagamento confirmado com sucesso, {{primeiro_nome}}! Obrigado pela confiança. Nosso projeto está oficialmente iniciado! Vou te mantendo atualizado a cada marco até a publicação final.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, primeira etapa da produção concluída! Estamos dentro do cronograma previsto para a {{empresa}}.',
        objective: 'Atualização de progresso',
        tone: 'consultivo',
        condition: '2 dias após início',
        whenNotToUse: 'Se projeto entregue',
      },
      {
        number: 2,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: '{{primeiro_nome}}, o ambiente de testes está quase pronto para a sua revisão final!',
        objective: 'Antecipação de entrega',
        tone: 'direto',
        condition: '5 dias',
        whenNotToUse: 'Se já entregue',
      },
      {
        number: 3,
        intervalRecommended: '8 dias',
        intervalHours: 192,
        message: 'Olá, {{primeiro_nome}}! Tudo pronto no ambiente oficial. Vamos fazer a checagem final juntos?',
        objective: 'Checagem final',
        tone: 'profissional',
        condition: '8 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Oi {{primeiro_nome}}, tudo rodando perfeitamente no domínio da {{empresa}}!',
        objective: 'Confirmação de Go-live',
        tone: 'casual',
        condition: '12 dias',
        whenNotToUse: 'Se já validado',
      },
      {
        number: 5,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}. Passando para saber como foram os primeiros dias do novo site no ar!',
        objective: 'Acompanhamento pós-go-live',
        tone: 'consultivo',
        condition: '20 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de agendar um bate-papo de 10 minutos para avaliar os primeiros resultados?',
        objective: 'Reunião de resultados',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-22',
    stepNumber: 22,
    title: 'ETAPA 22 — Pós-venda & Suporte',
    flowType: 'problema_identificado',
    category: 'Pós-Venda',
    objective: 'Garantir satisfação plena, tirar dúvidas e oferecer suporte preventivo.',
    purposeDescription: 'Cuidado genuíno pós-entrega.',
    scriptTemplate: 'Olá, {{primeiro_nome}}! Passando para saber como está o funcionamento do projeto na {{empresa}} após esses primeiros dias. Está tudo rodando 100% como você esperava?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Oi {{primeiro_nome}}, se tiver qualquer dúvida de edição de textos ou fotos, é só me chamar por aqui!',
        objective: 'Suporte aberto',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: '{{primeiro_nome}}, já começaram a notar novos contatos chegando pelo botão do WhatsApp da {{empresa}}?',
        objective: 'Checagem de impacto real',
        tone: 'consultivo',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}! Tudo certo com a velocidade de carregamento e formulários?',
        objective: 'Auditoria técnica pós-venda',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi {{primeiro_nome}}, completamos 1 mês do projeto no ar! Parabéns pelos resultados da {{empresa}}!',
        objective: 'Celebração de 1 mês',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Olá, {{primeiro_nome}}. Se precisarem de alguma expansão ou novo serviço para a {{empresa}}, estou por aqui.',
        objective: 'Oportunidade de cross-sell suave',
        tone: 'consultivo',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para deixar um abraço e saber como estão as metas da {{empresa}}.',
        objective: 'Relacionamento contínuo',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'prob-step-23',
    stepNumber: 23,
    title: 'ETAPA 23 — Pedido de Recomendação & Depoimento Real',
    flowType: 'problema_identificado',
    category: 'Recomendação & Autoridade',
    objective: 'Pedir recomendação e feedback sincero somente após cliente satisfeito (sem inventar nada).',
    purposeDescription: 'Geração de prova social autêntica e novas indicações.',
    scriptTemplate: 'Oi, {{primeiro_nome}}! Fico muito feliz que tenha gostado do resultado na {{empresa}}. Você conhece algum outro empresário ou parceiro que também poderia se beneficiar de uma melhoria parecida nessa parte?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, se lembrar de alguém, pode só me passar o contato ou passar o meu número para ele!',
        objective: 'Facilitar a indicação',
        tone: 'casual',
        condition: '2 dias',
        whenNotToUse: 'Se indicou',
      },
      {
        number: 2,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: '{{primeiro_nome}}, se for mais fácil, posso preparar uma condição especial para os parceiros indicados pela {{empresa}}!',
        objective: 'Incentivo para indicação',
        tone: 'consultivo',
        condition: '5 dias',
        whenNotToUse: 'Se já indicou',
      },
      {
        number: 3,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Olá, {{primeiro_nome}}! Caso você possa deixar uma avaliação rápida de 1 linha sobre nosso atendimento, me ajudaria bastante.',
        objective: 'Pedido de review real',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Oi {{primeiro_nome}}, obrigado novamente pela parceria com a {{empresa}}! Um ótimo mês para vocês.',
        objective: 'Agradecimento',
        tone: 'casual',
        condition: '20 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '40 dias',
        intervalHours: 960,
        message: 'Olá, {{primeiro_nome}}. Como estão as coisas por aí? Se surgir qualquer necessidade técnica, é só me avisar!',
        objective: 'Manutenção de rede',
        tone: 'profissional',
        condition: '40 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '75 dias',
        intervalHours: 1800,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Estamos iniciando um novo ciclo e lembrei da {{empresa}}. Como estão os negócios?',
        objective: 'Reativação semestral',
        tone: 'casual',
        condition: '75 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
];
