import { ContextualFollowUpScenario } from '../types/scripts';

export const CONTEXTUAL_FOLLOWUP_SCENARIOS: ContextualFollowUpScenario[] = [
  {
    id: 'scen-1',
    number: 1,
    title: 'CENÁRIO 1 — Primeira Mensagem Ignorada',
    description: 'Quando a primeira mensagem de prospecção foi enviada e não houve retorno nas primeiras horas ou dias.',
    triggerCondition: 'primeira_mensagem_sem_resposta',
    followUps: [
      {
        number: 1,
        intervalRecommended: '4–8 horas',
        intervalHours: 6,
        message: 'Oi, {{primeiro_nome}}, passando só para confirmar se recebeu a mensagem acima. Conseguiu ver?',
        objective: 'Lembrete super leve e sutil no mesmo dia',
        tone: 'casual',
        condition: 'Primeira mensagem enviada sem retorno',
        whenNotToUse: 'Se respondeu ou recusou',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Olá, {{primeiro_nome}}. Imagino que sua rotina na {{empresa}} esteja corrida. Só queria confirmar se esse canal é o melhor para falar sobre {{observacao_especifica}} ou se prefere por e-mail.',
        objective: 'Validar canal e respeitar rotina',
        tone: 'consultivo',
        condition: '24h de silêncio',
        whenNotToUse: 'Fora do horário comercial',
      },
      {
        number: 3,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Tentei contato antes pois identifiquei um ponto bem pontual em {{observacao_especifica}} da {{empresa}}. Vale 2 minutos de conversa?',
        objective: 'Reiterar a observação pontual',
        tone: 'direto',
        condition: '48h sem resposta',
        whenNotToUse: 'Se o contato estiver ausente',
      },
      {
        number: 4,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}. Queria apenas evitar insistir sem necessidade. Essa melhoria em {{observacao_especifica}} é algo que a {{empresa}} pretende olhar agora ou não é o momento?',
        objective: 'Desarmar objeção de timing',
        tone: 'profissional',
        condition: '4 dias sem retorno',
        whenNotToUse: 'DNC',
      },
      {
        number: 5,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi, {{primeiro_nome}}. Como não tive retorno, imaginei que o foco agora seja outro na {{empresa}}. Se fizer sentido retomar no futuro, continuo por aqui!',
        objective: 'Fechamento elegante de ciclo',
        tone: 'consultivo',
        condition: '1 semana de silêncio',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 6,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}! Lembra do ponto em {{observacao_especifica}} que comentei na {{empresa}}? Surgiu uma novidade prática nessa área e lembrei de você. Posso mandar em 30 segundos?',
        objective: 'Tentativa de reativação com novidade prática',
        tone: 'casual',
        condition: '2 semanas antes de arquivar',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-2',
    number: 2,
    title: 'CENÁRIO 2 — Pergunta Ignorada',
    description: 'Quando você fez uma pergunta de qualificação ou processo e o lead parou de responder.',
    triggerCondition: 'pergunta_sem_resposta',
    followUps: [
      {
        number: 1,
        intervalRecommended: '6–8 horas',
        intervalHours: 8,
        message: 'Oi {{primeiro_nome}}, se for mais fácil, pode me responder em apenas uma palavra ou áudio!',
        objective: 'Facilitar resposta imediata',
        tone: 'casual',
        condition: 'Visualizou e não respondeu à pergunta',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, tudo bem? Pergunto porque muitos gestores de {{nicho}} passam pelo mesmo desafio na {{empresa}}.',
        objective: 'Conectar à dor de mercado',
        tone: 'consultivo',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Só para eu saber se faz sentido mantermos essa conversa ou se prefere pausar por aqui.',
        objective: 'Checagem de continuidade',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fique à vontade para responder quando seu dia estiver mais tranquilo.',
        objective: 'Compreensão de rotina',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}. Vou deixar anotado por aqui para não te sobrecarregar. Um abraço!',
        objective: 'Pausa profissional',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Surgiu alguma novidade sobre como a {{empresa}} está tratando esse ponto?',
        objective: 'Reativação a 25 dias',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-3',
    number: 3,
    title: 'CENÁRIO 3 — Diagnóstico Interrompido',
    description: 'Quando a conversa estava engajada na descoberta de dores e o lead sumiu no meio do diagnóstico.',
    triggerCondition: 'diagnostico_interrompido',
    followUps: [
      {
        number: 1,
        intervalRecommended: '8 horas',
        intervalHours: 8,
        message: 'Oi {{primeiro_nome}}, estávamos falando sobre {{ultimo_ponto_mencionado}}. Conseguiu ver minha última mensagem?',
        objective: 'Retomar contexto da conversa',
        tone: 'casual',
        condition: 'Parou no meio do diálogo',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, tudo bem? Se for mais rápido, posso resumir o que identifiquei da {{empresa}} em 2 pontos.',
        objective: 'Oferta de síntese rápida',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Queria só saber se vocês chegaram a resolver aquela parte de {{problema}} na {{empresa}}.',
        objective: 'Checar resolução independente',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver um momento livre para continuarmos o diagnóstico, estou por aqui.',
        objective: 'Aguardar momento',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Vou pausar nosso diagnóstico por enquanto para não te incomodar. Sucesso na {{empresa}}!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Lembra do diagnóstico de {{problema}} que iniciamos? Gostaria de retomar?',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-4',
    number: 4,
    title: 'CENÁRIO 4 — Demonstração / Link Enviado sem Resposta',
    description: 'Quando o protótipo, auditoria ou exemplo foi enviado e o lead não deu retorno.',
    triggerCondition: 'demo_enviada_sem_resposta',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu abrir o exemplo no seu celular? Funcionou certinho por aí?',
        objective: 'Checagem de abertura e usabilidade',
        tone: 'casual',
        condition: '1 dia após envio do protótipo',
        whenNotToUse: 'Se já deu feedback',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? O que você achou daquela estrutura que preparei para a {{empresa}}?',
        objective: 'Pedido suave de primeira impressão',
        tone: 'consultivo',
        condition: '2 dias sem retorno',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Teve chance de dar uma olhada? Fiquei curioso para saber sua opinião sincera.',
        objective: 'Estimular sinceridade',
        tone: 'direto',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi, {{primeiro_nome}}, sei que a rotina é corrida. Se puder me dizer apenas se o design combina com a {{empresa}}, te agradeço!',
        objective: 'Micro-feedback rápido',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Se achou que a demonstração não faz sentido para a {{empresa}}, pode me dizer com total franqueza!',
        objective: 'Permissão de rejeição para destravar',
        tone: 'consultivo',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vou desativar o link temporário de testes da {{empresa}} na próxima semana. Gostaria de salvar algo?',
        objective: 'Escassez técnica real',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-5',
    number: 5,
    title: 'CENÁRIO 5 — Feedback Solicitado sem Resposta',
    description: 'Quando o lead viu a demonstração mas não respondeu sobre o que gostou ou o que mudaria.',
    triggerCondition: 'feedback_solicitado_sem_resposta',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, não precisa de análise longa! Só me diz se a proposta visual te agradou.',
        objective: 'Reduzir barreira de resposta',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Se tiver qualquer detalhe de cores ou textos que você mudaria, é super fácil ajustar.',
        objective: 'Mostrar flexibilidade de ajustes',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Quer que eu adapte alguma coisa no exemplo antes de falarmos sobre implementação?',
        objective: 'Propor adaptação',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no seu aguardo para refinarmos o modelo da {{empresa}}.',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou pausar os ajustes por enquanto. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de dar continuidade àqueles ajustes na {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-6',
    number: 6,
    title: 'CENÁRIO 6 — Proposta Enviada sem Resposta',
    description: 'Quando o valor e as condições foram apresentados e o lead não confirmou nem recusou.',
    triggerCondition: 'proposta_sem_resposta',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o que achou da condição de {{preco}} para a {{empresa}}? Ficou dentro do esperado?',
        objective: 'Checar recepção da proposta',
        tone: 'consultivo',
        condition: '1 dia após proposta',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Ficou alguma dúvida sobre o cronograma ou formas de pagamento?',
        objective: 'Tirar dúvidas comerciais',
        tone: 'direto',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: 'Olá, {{primeiro_nome}}! Conseguimos incluir {{bonus_incluso}} sem acréscimo se iniciarmos nesta semana.',
        objective: 'Adicionar valor para destravar',
        tone: 'profissional',
        condition: '4 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Caso precise de flexibilidade de pagamento para a {{empresa}}, é só me falar.',
        objective: 'Oferecer condição financeira',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Olá, {{primeiro_nome}}. Como não tivemos retorno, vou manter essa proposta reservada por mais 3 dias. Um abraço!',
        objective: 'Aviso de expiração',
        tone: 'profissional',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou a decisão sobre o projeto da {{empresa}}.',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-7',
    number: 7,
    title: 'CENÁRIO 7 — Negociação Interrompida',
    description: 'Quando vocês estavam alinhando escopo ou preço e o lead não respondeu a contraproposta.',
    triggerCondition: 'negociacao_interrompida',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, aquela contraproposta de {{preco_ajustado}} atende ao que a {{empresa}} precisa?',
        objective: 'Validar contraproposta',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Me avise se preferir ajustar o escopo de outra forma.',
        objective: 'Flexibilidade de negociação',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição para batermos o martelo nas melhores condições para vocês.',
        objective: 'Aproximação de fechamento',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver um retorno da diretoria, me avise!',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou congelar os termos negociados por enquanto. Um abraço!',
        objective: 'Congelamento',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de retomar a negociação do projeto da {{empresa}}?',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-8',
    number: 8,
    title: 'CENÁRIO 8 — Cliente Disse "Vou Pensar"',
    description: 'Quando o cliente usou a frase clássica de reflexão e não voltou com a resposta.',
    triggerCondition: 'cliente_disse_vou_pensar',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu pensar um pouco sobre a proposta da {{empresa}}? Ficou alguma dúvida?',
        objective: 'Checagem respeitosa de 24h',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se pediu mais prazo',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Preparei um resumo de 3 pontos para te ajudar a avaliar com calma.',
        objective: 'Material de apoio à reflexão',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Chegou a alguma conclusão sobre o projeto ou prefere deixar para outro momento?',
        objective: 'Desarmar indecisão',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Sem pressão nenhuma: se não for o momento da {{empresa}}, pode me dizer com total franqueza!',
        objective: 'Permissão de "não"',
        tone: 'consultivo',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou fechar essa proposta por aqui para não te incomodar. Um abraço!',
        objective: 'Fechamento de loop',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando só para saber como ficaram os planos da {{empresa}}.',
        objective: 'Reativação a 35 dias',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-9',
    number: 9,
    title: 'CENÁRIO 9 — Cliente Pediu para Falar Depois',
    description: 'Quando o lead pediu para entrar em contato em um momento futuro.',
    triggerCondition: 'cliente_pediu_falar_depois',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Perfeito, {{primeiro_nome}}! Registrei na minha agenda. Qual dia específico fica melhor para eu te procurar?',
        objective: 'Confirmar dia exato',
        tone: 'profissional',
        condition: '1 dia',
        whenNotToUse: 'Se já definiu dia',
      },
      {
        number: 2,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, tudo bem? Passando só para desejar uma ótima semana na {{empresa}}!',
        objective: 'Presença leve',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: 'Data agendada',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}! Conforme combinamos: como está o momento da {{empresa}} para iniciarmos o projeto agora?',
        objective: 'Recontato na data combinada',
        tone: 'consultivo',
        condition: 'Na data combinada',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '5 dias após data',
        intervalHours: 840,
        message: 'Oi {{primeiro_nome}}, tudo bem? Conseguiu checar se o calendário da {{empresa}} abriu para esse projeto?',
        objective: 'Checagem pós-data combinada',
        tone: 'direto',
        condition: '5 dias após data',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias após data',
        intervalHours: 1080,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição quando o calendário da {{empresa}} estiver propício.',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '15 dias após data',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '45 dias após data',
        intervalHours: 1800,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou o planejamento da {{empresa}}.',
        objective: 'Reativação a 45 dias',
        tone: 'casual',
        condition: '45 dias após data',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-10',
    number: 10,
    title: 'CENÁRIO 10 — Responsável Não Respondeu',
    description: 'Quando o contato foi direcionado para o decisor e este não respondeu.',
    triggerCondition: 'responsavel_nao_respondeu',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Olá, {{primeiro_nome}}. Foi o {{nome_funcionario}} quem me indicou falar com você sobre {{observacao_especifica}} da {{empresa}}.',
        objective: 'Citar quem indicou internamente',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Sei que sua rotina de gestão é intensa. Prometo ser super objetivo em 1 minuto.',
        objective: 'Alívio de tempo do gestor',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! O exemplo que preparei para a {{empresa}} está disponível se você quiser ver sem compromisso.',
        objective: 'Oferta do exemplo pronto',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, caso você delegue essa área para outra pessoa, pode só me passar o nome dela!',
        objective: 'Pedido de delegação',
        tone: 'consultivo',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar meus contatos por aqui para não atrapalhar. Sucesso à frente da {{empresa}}!',
        objective: 'Pausa profissional',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando apenas para saber se vocês já ajustaram {{observacao_especifica}} na {{empresa}}.',
        objective: 'Reativação a 35 dias',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-11',
    number: 11,
    title: 'CENÁRIO 11 — Funcionário Não Indicou Responsável',
    description: 'Quando o atendente/recepcionista visualizou e não passou o contato do gestor.',
    triggerCondition: 'funcionario_nao_indicou',
    followUps: [
      {
        number: 1,
        intervalRecommended: '8 horas',
        intervalHours: 8,
        message: 'Oi {{primeiro_nome}}, se for mais fácil, pode ser só o primeiro nome ou e-mail de quem cuida dessa área!',
        objective: 'Facilitar com micro-dado',
        tone: 'casual',
        condition: '8h sem resposta',
        whenNotToUse: 'Se já passou',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, tudo bem? É bem rápido e prometo não incomodar a diretoria sem motivo.',
        objective: 'Garantia de discrição',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Se preferir, posso ligar no fixo da {{empresa}}. Qual o melhor ramal?',
        objective: 'Transição para fixo',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Oi {{primeiro_nome}}, como não quero atrapalhar seu atendimento, se puder só repassar meu contato para o gestor, te agradeço!',
        objective: 'Incentivar repasse passivo',
        tone: 'casual',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Agradeço a atenção até aqui. Um ótimo trabalho para vocês!',
        objective: 'Encerramento educado',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Conseguiram definir quem responde por {{servico}} na {{empresa}}?',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-12',
    number: 12,
    title: 'CENÁRIO 12 — Desapareceu Após Demonstrar Interesse',
    description: 'Quando o lead disse "adorei!", "muito bom!", "vamos fazer", e depois sumiu.',
    triggerCondition: 'desapareceu_pos_interesse',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, fiquei super empolgado com o projeto da {{empresa}}! Aconteceu algum imprevisto por aí?',
        objective: 'Checagem empática de imprevisto',
        tone: 'casual',
        condition: '1 dia após sumiço',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Deixei a vaga de produção reservada para vocês nesta semana.',
        objective: 'Gatilho de reserva de vaga',
        tone: 'consultivo',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Só para eu saber se podemos dar continuidade ou se surgiu algum impedimento.',
        objective: 'Checar impedimento real',
        tone: 'direto',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '9 dias',
        intervalHours: 216,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se você preferir adiar o início para o próximo mês, sem problemas!',
        objective: 'Oferecer adiamento tranquilo',
        tone: 'casual',
        condition: '9 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou liberar a vaga da agenda por enquanto para não segurar sua rotina. Um abraço!',
        objective: 'Liberação de agenda',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vamos retomar aquele projeto incrível da {{empresa}} que conversamos?',
        objective: 'Reativação a 30 dias',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-13',
    number: 13,
    title: 'CENÁRIO 13 — Pagamento Pendente',
    description: 'Quando os dados de pagamento foram enviados e o comprovante ainda não foi recebido.',
    triggerCondition: 'pagamento_pendente',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu fazer o acerto ou teve alguma dificuldade com os dados bancários/Pix?',
        objective: 'Checar dificuldade técnica',
        tone: 'casual',
        condition: '1 dia após dados de pagamento',
        whenNotToUse: 'Se pago',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo bem? Me avise assim que o financeiro da {{empresa}} aprovar para eu emitir seu recibo.',
        objective: 'Lembrete financeiro',
        tone: 'consultivo',
        condition: '2 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Precisa que eu envie a fatura ou dados em outro formato?',
        objective: 'Facilitar formato contábil',
        tone: 'direto',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '9 dias',
        intervalHours: 216,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no aguardo para liberarmos a entrega final no domínio oficial!',
        objective: 'Lembrete de liberação',
        tone: 'casual',
        condition: '9 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Caso tenha havido algum imprevisto, me avise para reorganizarmos os prazos.',
        objective: 'Compreensão de imprevisto',
        tone: 'consultivo',
        condition: '16 dias',
        whenNotToUse: 'Se pago',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para regularizarmos a pendência do projeto da {{empresa}}.',
        objective: 'Regularização financeira',
        tone: 'direto',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'scen-14',
    number: 14,
    title: 'CENÁRIO 14 — Projeto Aprovado Não Iniciado',
    description: 'Quando o cliente aprovou o projeto e fez o pagamento, mas não enviou o logo, textos ou acessos.',
    triggerCondition: 'aprovado_nao_iniciado',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, só preciso do seu logo e cores básicas para darmos o start no ambiente de testes!',
        objective: 'Solicitação de logo e cores',
        tone: 'casual',
        condition: '1 dia após aprovação',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Se você não tiver o logo em alta resolução, pode me mandar o print do Instagram que nós tratamos aqui!',
        objective: 'Facilitar envio de arquivos brutos',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Passando só para saber se conseguiu separar os materiais da {{empresa}}.',
        objective: 'Acompanhamento de materiais',
        tone: 'direto',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se preferir, posso criar um rascunho com fotos de banco de imagem para você apenas aprovar.',
        objective: 'Oferta de preenchimento automático',
        tone: 'casual',
        condition: '14 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 5,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}. Estamos com a equipe pronta para publicar o projeto da {{empresa}} assim que você puder!',
        objective: 'Prontidão de equipe',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 6,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vamos dar o start na publicação do site da {{empresa}}?',
        objective: 'Reativação operacional',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
];
