import { ScriptStepDefinition } from '../types/scripts';

export const OPORTUNIDADE_LATENTE_STEPS: ScriptStepDefinition[] = [
  {
    id: 'latent-step-1',
    stepNumber: 1,
    title: 'ETAPA 1 — Primeira Interação (Investigativa)',
    flowType: 'oportunidade_latente',
    category: 'Abertura & Exploração',
    objective: 'Iniciar conversa sem afirmar que o cliente precisa de um app ou sistema. Focar em curiosidade sobre o processo.',
    purposeDescription: 'NÃO afirmar "você precisa de um app". Fazer pergunta aberta sobre o fluxo operacional.',
    isInitialContact: true,
    requiresResponse: true,
    roleTarget: 'indeterminado',
    scriptTemplate: 'Olá, {{primeiro_nome}}. Acompanho o crescimento da {{empresa}} no setor de {{nicho}} e fiquei com uma curiosidade profissional: como vocês organizam o fluxo de {{processo_chave}} hoje em dia?',
    countryVariations: {
      BR: 'Olá, {{primeiro_nome}}. Acompanho o crescimento da {{empresa}} no setor de {{nicho}} e fiquei com uma curiosidade profissional: como vocês organizam o fluxo de {{processo_chave}} hoje em dia?',
      PT: 'Olá, {{primeiro_nome}}. Acompanho o crescimento da {{empresa}} no sector de {{nicho}} e fiquei com uma curiosidade profissional: como gerem o fluxo de {{processo_chave}} hoje em dia?',
      MZ: 'Olá, {{primeiro_nome}}. Tenho acompanhado o trabalho da {{empresa}} em {{nicho}} e fiquei com uma curiosidade: como organizam o fluxo de {{processo_chave}} hoje em dia?',
    },
    followUps: [
      {
        number: 1,
        intervalRecommended: '6–8 horas',
        intervalHours: 8,
        message: 'Oi {{primeiro_nome}}, pergunto porque muitas operações do seu tamanho gastam muitas horas manuais nessa parte. É o caso de vocês?',
        objective: 'Relembrar com dor comum do segmento',
        tone: 'consultivo',
        condition: 'Sem resposta após 6-8h',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, tudo bem? Se você for o gestor dessa área na {{empresa}}, adoraria trocar 2 minutos de ideias!',
        objective: 'Checar se é o gestor da área',
        tone: 'casual',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Sei que o dia a dia na {{empresa}} é agitado. Vocês usam alguma ferramenta ou planilha para controlar isso hoje?',
        objective: 'Pergunta fechada mais simples',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi {{primeiro_nome}}, caso essa parte esteja 100% automatizada e funcionando redonda na {{empresa}}, maravilha! Se não, estou por aqui.',
        objective: 'Dar espaço e desarmar resistência',
        tone: 'consultivo',
        condition: '6 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}. Vou pausar meus contatos para não atrapalhar seu expediente. Um abraço!',
        objective: 'Pausa suave',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Surgiu uma ferramenta prática para {{nicho}} e lembrei da {{empresa}}. Vale te mostrar?',
        objective: 'Reativação exploratória',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-2',
    stepNumber: 2,
    title: 'ETAPA 2 — Descobrir Responsável por Tecnologia / Processos',
    flowType: 'oportunidade_latente',
    category: 'Mapeamento de Decisor',
    objective: 'Identificar quem lidera decisões de sistemas, automação ou operações na empresa.',
    purposeDescription: 'Descobrir se está falando com o sócio, diretor de operações ou gerente.',
    scriptTemplate: 'Entendido, {{primeiro_nome}}! Quem na {{empresa}} costuma liderar as iniciativas de melhoria de processos ou tecnologia?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, se for você mesmo, maravilha! Se for outra pessoa, pode ser só o primeiro nome.',
        objective: 'Facilitar a confirmação',
        tone: 'casual',
        condition: '1 dia sem resposta',
        whenNotToUse: 'Se já confirmou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, pergunto para não falar de processos com quem está focado em outra área.',
        objective: 'Respeito à função',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Conseguiria me indicar o responsável pela área operacional da {{empresa}}?',
        objective: 'Pedido formal',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Caso prefira, posso enviar uma apresentação em PDF para a diretoria.',
        objective: 'Alternativa em PDF',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição caso a {{empresa}} queira avaliar soluções nessa área no futuro.',
        objective: 'Encerramento',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como ficaram as metas de tecnologia da {{empresa}} para este trimestre?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-3',
    stepNumber: 3,
    title: 'ETAPA 3 — Contextualização do Cenário',
    flowType: 'oportunidade_latente',
    category: 'Contextualização',
    objective: 'Alinhar o cenário de mercado do nicho sem prescrever solução pronta.',
    purposeDescription: 'Demonstrar autoridade no segmento.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}. Conversando com outras empresas de {{nicho}}, temos visto que à medida que o volume cresce, manter o controle em planilhas ou WhatsApp acaba gerando gargalos. É algo que você também percebe na {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, vocês sentem esse atrito hoje ou a operação está rodando lisa?',
        objective: 'Estimular resposta binária',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, pergunto porque pequenas travas manuais no dia a dia somam dezenas de horas no fim do mês.',
        objective: 'Quantificar impacto no tempo',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! O que mais toma tempo da sua equipe nessa rotina?',
        objective: 'Pergunta de dor operacional',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver 2 minutos para falar sobre esse ponto, me avisa!',
        objective: 'Aguardar momento',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Vou deixar anotado por aqui. Um abraço para a equipe da {{empresa}}!',
        objective: 'Fechamento de ciclo',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como está o fluxo operacional da {{empresa}} atualmente?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-4',
    stepNumber: 4,
    title: 'ETAPA 4 — Pergunta sobre Processo Atual',
    flowType: 'oportunidade_latente',
    category: 'Diagnóstico Operacional',
    objective: 'Entender detalhadamente as etapas do processo atual.',
    purposeDescription: 'Descobrir se é manual, planilha ou sistema genérico.',
    scriptTemplate: 'Hoje, quando entra uma nova demanda na {{empresa}}, quais são exatamente as etapas até a entrega ou conclusão?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, pode ser um resumo bem simples de 3 linhas!',
        objective: 'Reduzir esforço de escrita',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se detalhou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, esse processo é feito de forma manual pela equipe ou vocês já usam algum software?',
        objective: 'Identificar stack tecnológica',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Se preferir me mandar um áudio rápido de 30 segundos explicando, fique à vontade.',
        objective: 'Facilitar via áudio',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico à disposição para quando puder compartilhar como roda a operação da {{empresa}}.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou pausar por aqui para não te sobrecarregar. Sucesso com a {{empresa}}!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Alguma mudança nas ferramentas de gestão da {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-5',
    stepNumber: 5,
    title: 'ETAPA 5 — Identificação de Gargalo',
    flowType: 'oportunidade_latente',
    category: 'Gargalos & Dores',
    objective: 'Identificar onde ocorrem atrasos, retrabalhos ou perda de dados.',
    purposeDescription: 'Foco no ponto mais crítico do fluxo.',
    scriptTemplate: 'E nesse fluxo todo, {{primeiro_nome}}, qual é a parte que mais costuma gerar retrabalho ou atraso para a equipe da {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, costuma ser a comunicação interna ou o acompanhamento dos clientes?',
        objective: 'Sugerir hipóteses comuns',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se você pudesse eliminar 1 tarefa repetitiva da sua equipe hoje, qual seria?',
        objective: 'Pergunta de desejo de eliminação de tarefa',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Já chegaram a calcular quanto tempo isso custa por semana para a {{empresa}}?',
        objective: 'Conscientização de custo de ineficiência',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver um tempo para pensarmos em como destravar esse gargalo, me avisa!',
        objective: 'Lembrete amigável',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar por aqui para respeitar sua rotina. Até uma próxima!',
        objective: 'Fechamento',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Conseguiram destravar aquele ponto na rotina da {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-6',
    stepNumber: 6,
    title: 'ETAPA 6 — Exploração & Impacto',
    flowType: 'oportunidade_latente',
    category: 'Impacto & Dimensionamento',
    objective: 'Explorar a extensão do gargalo e quantas pessoas são afetadas.',
    purposeDescription: 'Entender a escala da oportunidade.',
    scriptTemplate: 'Entendi o ponto! Quantas pessoas na {{empresa}} participam diretamente desse processo e quanto tempo em média gastam com isso por dia?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, é um processo que envolve mais de 3 pessoas ou é mais concentrado?',
        objective: 'Facilitar estimativa de time',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, pergunto porque se economizarmos 1h por dia de cada um, o ganho de produtividade para a {{empresa}} é enorme.',
        objective: 'Mostrar ganho tangível',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Faz sentido para você avaliarmos uma forma de automatizar essa etapa?',
        objective: 'Checar interesse em automação',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico à disposição para trocarmos uma ideia rápida sobre isso.',
        objective: 'Aguardar momento',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}. Vou pausar por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Algum avanço na automação desses processos na {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-7',
    stepNumber: 7,
    title: 'ETAPA 7 — Dimensionamento do Problema',
    flowType: 'oportunidade_latente',
    category: 'Impacto & Dimensionamento',
    objective: 'Ajudar o cliente a quantificar a perda de tempo e oportunidades.',
    purposeDescription: 'Tornar o custo da inação visível de forma sutil.',
    scriptTemplate: 'Faz total sentido. Se a gente olhar no mês todo, isso deve representar várias horas de trabalho repetitivo. Já chegaram a pensar em estruturar uma solução própria para a {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, ou vocês preferem adaptar ferramentas de prateleira já existentes?',
        objective: 'Explorar ferramentas de prateleira vs custom',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, o que impediu vocês de resolverem isso até hoje? Foi falta de tempo ou de um parceiro técnico?',
        objective: 'Descobrir barreira histórica',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Se puder me dizer qual seria a principal função que você gostaria de ter nessa solução, eu te dou uma direção.',
        objective: 'Identificar a "killer feature"',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser bater um papo sobre como estruturar isso, estou por aqui.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou congelar esse tema por enquanto. Sucesso com as metas!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Lembra da conversa sobre a automação da {{empresa}}? Quer dar uma olhada num modelo prático?',
        objective: 'Reativação com modelo',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-8',
    stepNumber: 8,
    title: 'ETAPA 8 — Validação de Interesse',
    flowType: 'oportunidade_latente',
    category: 'Validação',
    objective: 'Confirmar se resolver esse gargalo é prioridade estratégica no momento.',
    purposeDescription: 'Checar se há apetite para investir tempo e foco.',
    scriptTemplate: 'Se existisse uma forma simples de automatizar isso sem burocracia, resolver essa questão seria uma prioridade para a {{empresa}} neste trimestre?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, pergunto com total transparência: é algo prioritário agora ou um projeto mais para o futuro?',
        objective: 'Checagem de timing sem pressão',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se for prioridade, posso desenhar um conceito inicial em 1 página para você ver como ficaria.',
        objective: 'Oferta de conceito em 1 página',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Fique à vontade para me dizer se o foco da {{empresa}} estiver em outra área neste momento.',
        objective: 'Alívio de pressão',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando for o momento ideal para a {{empresa}}, é só me dar um alô!',
        objective: 'Porta aberta',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar por aqui para respeitar o seu calendário. Um abraço!',
        objective: 'Fechamento',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como ficaram os planos de novos sistemas para a {{empresa}}?',
        objective: 'Reativação trimestral',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-9',
    stepNumber: 9,
    title: 'ETAPA 9 — Conceito da Solução (Sem Promessas Falsas)',
    flowType: 'oportunidade_latente',
    category: 'Conceito & Arquitetura',
    objective: 'Apresentar a lógica funcional da solução sem inventar integrações mágicas ou cases.',
    purposeDescription: 'Conceito transparente de fluxo.',
    scriptTemplate: 'Minha ideia para a {{empresa}} seria criar um fluxo onde: 1. {{etapa_1_entrada}}, 2. {{etapa_2_processamento_automatico}}, 3. {{etapa_3_saida_notificacao}}. Isso eliminaria a necessidade de controle manual. O que você acha dessa dinâmica?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, essa lógica resolve o gargalo que você comentou?',
        objective: 'Validar a lógica proposta',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se validou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se tiver alguma regra de negócio específica da {{empresa}} que precise entrar no fluxo, podemos incluir!',
        objective: 'Flexibilidade técnica',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Posso montar um protótipo visual rápido dessa tela para você testar no celular?',
        objective: 'Oferta de protótipo interativo',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver 2 minutos para avaliar esse conceito, fico à disposição.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou guardar esse conceito por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Tivemos novos modelos de automação para {{nicho}}. Quer dar uma olhada?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-10',
    stepNumber: 10,
    title: 'ETAPA 10 — Demonstração do Conceito / Wireframe',
    flowType: 'oportunidade_latente',
    category: 'Demonstração',
    objective: 'Apresentar o protótipo visual demonstrativo com autorização prévia.',
    purposeDescription: 'Demonstração prática baseada em conceito real.',
    scriptTemplate: 'Preparei um fluxo visual simplificado pensando na rotina da {{empresa}}: {{link_prototipo}}. Repare em como a equipe economizaria cliques para registrar cada etapa.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu abrir o protótipo? O que achou da usabilidade?',
        objective: 'Checagem de abertura',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Esse modelo te parece intuitivo para o time da {{empresa}} usar no dia a dia?',
        objective: 'Validar facilidade de adoção',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Ficou alguma dúvida sobre como os dados seriam salvos e exportados?',
        objective: 'Checar dúvidas técnicas',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se quiser agendar 10 minutos para vermos juntos na tela, é só me falar!',
        objective: 'Oferta de demo ao vivo',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou manter o link ativo por mais alguns dias. Obrigado pela atenção!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de avançar com o protótipo da {{empresa}} para uma versão funcional?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-11',
    stepNumber: 11,
    title: 'ETAPA 11 — Feedback & Validação de Requisitos',
    flowType: 'oportunidade_latente',
    category: 'Co-criação & Requisitos',
    objective: 'Coletar impressões sinceras e refinar escopo funcional.',
    purposeDescription: 'Perguntas detalhadas sobre campos e permissões.',
    scriptTemplate: 'Qual tela ou função você achou mais indispensável, e o que você sente que ainda faltou para atender a rotina da {{empresa}}?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, os relatórios e campos atendem ou tem algum dado específico que precisa ser registrado?',
        objective: 'Mapear campos customizados',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Se puder me dizer o que achou dos botões principais, te agradeço!',
        objective: 'Feedback de interface',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Podemos validar os requisitos finais para eu montar a estimativa de tempo e investimento?',
        objective: 'Ponte para viabilidade',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no seu aguardo para refinarmos o escopo.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou arquivar as notas funcionais por enquanto. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Quando quiser retomar o mapeamento da {{empresa}}, é só me chamar!',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-12',
    stepNumber: 12,
    title: 'ETAPA 12 — Requisitos & Escopo Fechado (MVP)',
    flowType: 'oportunidade_latente',
    category: 'Escopo & MVP',
    objective: 'Conter o escopo em um MVP (Produto Mínimo Viável) para validação rápida.',
    purposeDescription: 'Evitar escopos gigantescos que travam o fechamento.',
    scriptTemplate: 'Minha recomendação para a {{empresa}} é focarmos num MVP com {{escopo_mvp}}. Assim entregamos em {{prazo_mvp}} dias, colocamos a equipe para rodar e colhemos feedback real sem risco. Faz sentido esse caminho ágil?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, começar por esse escopo enxuto te deixa mais seguro?',
        objective: 'Checar segurança no modelo ágil',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aprovou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, dessa forma o time já começa a economizar tempo na semana que vem!',
        objective: 'Reforçar velocidade de entrega',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Quer que eu te envie o cronograma e os valores desse MVP?',
        objective: 'Avanço para proposta',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando puder me dar o ok nesse escopo, te formalizo a proposta!',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou manter esse escopo reservado por enquanto. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Gostaria de tirar esse MVP do papel neste mês na {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-13',
    stepNumber: 13,
    title: 'ETAPA 13 — Viabilidade & Prazos',
    flowType: 'oportunidade_latente',
    category: 'Planejamento Técnico',
    objective: 'Confirmar cronograma, infraestrutura e suporte inclusos.',
    purposeDescription: 'Transparência de entrega e suporte.',
    scriptTemplate: 'Validando a viabilidade: conseguimos estruturar o sistema em {{prazo_dias}} dias úteis, incluindo hospedagem em nuvem, banco de dados seguro, treinamento rápido da equipe e suporte de 30 dias após a entrega.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, esse prazo atende ao planejamento da {{empresa}}?',
        objective: 'Checar aderência de prazo',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se precisarem de entrega acelerada por conta de alguma data limite, me avise para eu verificar nossa alocação.',
        objective: 'Checar urgência de cronograma',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Posso te apresentar a proposta comercial com as opções de investimento?',
        objective: 'Permissão para proposta',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no aguardo para formalizarmos os termos.',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou liberar a estimativa da fila de produção. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Abrimos nova janela de desenvolvimento para este mês. Faz sentido conversarmos?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-14',
    stepNumber: 14,
    title: 'ETAPA 14 — Proposta Comercial & ROI',
    flowType: 'oportunidade_latente',
    category: 'Proposta Comercial',
    objective: 'Apresentar o investimento estruturado comparando com o custo de manter o processo manual.',
    purposeDescription: 'Âncora de valor baseada no custo do retrabalho e horas economizadas.',
    scriptTemplate: 'Para o desenvolvimento completo desse sistema na {{empresa}}, o investimento fica em {{preco}}, com garantia de funcionamento e suporte. Considerando as horas que a equipe vai economizar todo mês, o retorno sobre o investimento costuma acontecer logo nas primeiras semanas. Como soa para você?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o que achou da condição proposta?',
        objective: 'Checar percepção de valor',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, temos também opção de parcelamento em até 3x sem juros para não pesar no fluxo de caixa da {{empresa}}.',
        objective: 'Oferecer condição financeira',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se fechou',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! O valor está dentro do orçamento previsto pela {{empresa}}?',
        objective: 'Diagnóstico de orçamento',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando tiver um retorno da diretoria, me avisa!',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou manter a proposta válida até o fim desta semana. Um abraço!',
        objective: 'Aviso de validade de proposta',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou a decisão sobre o sistema da {{empresa}}.',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-15',
    stepNumber: 15,
    title: 'ETAPA 15 — Negociação & Ajustes Finais',
    flowType: 'oportunidade_latente',
    category: 'Negociação',
    objective: 'Alinhar termos de contrato, forma de pagamento e entregáveis.',
    purposeDescription: 'Garante alinhamento final sem atritos.',
    scriptTemplate: 'Perfeito, {{primeiro_nome}}! Podemos estruturar o contrato com entrada de 50% no início e 50% após a homologação e aprovação do sistema pela {{empresa}}. Assim o seu risco é zero. Podemos formalizar dessa forma?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, essa condição de 50/50 traz total segurança para vocês?',
        objective: 'Reforçar segurança do acordo',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se confirmou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, já posso preparar a minuta contratual para a sua revisão?',
        objective: 'Avanço de contrato',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Ficou alguma cláusula ou condição que gostaria de ajustar?',
        objective: 'Checar pontos de contrato',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico no seu aguardo para darmos o start no desenvolvimento.',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '16 dias',
        intervalHours: 384,
        message: 'Olá, {{primeiro_nome}}. Vou deixar a minuta pausada por aqui. Até breve!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '16 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Vamos iniciar o desenvolvimento do sistema da {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'latent-step-16',
    stepNumber: 16,
    title: 'ETAPA 16 — Fechamento & Kick-off Técnico',
    flowType: 'oportunidade_latente',
    category: 'Fechamento & Kick-off',
    objective: 'Celebrar a parceria, agendar reunião de kick-off e iniciar a sprint de desenvolvimento.',
    purposeDescription: 'Início oficial e alinhamento de kick-off.',
    scriptTemplate: 'Parabéns pela decisão, {{primeiro_nome}}! Contrato formalizado com sucesso. Vamos agendar uma rápida chamada de kick-off de 20 minutos nesta quinta para alinharmos os acessos e iniciarmos a produção?',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, qual horário fica melhor para a chamada de kick-off: 10h ou 15h?',
        objective: 'Definição de horário',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se agendou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, segue o link da sala do Google Meet para o nosso kick-off: {{link_meet}}.',
        objective: 'Envio de link da reunião',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se já enviou',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Tudo pronto do nosso lado para iniciarmos os trabalhos. Nos vemos na call!',
        objective: 'Confirmação',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Oi {{primeiro_nome}}, primeira sprint em andamento conforme o plano alinhado no kick-off!',
        objective: 'Relato de progresso',
        tone: 'casual',
        condition: '12 dias',
        whenNotToUse: 'Se em contato',
      },
      {
        number: 5,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}. Passando para marcar a sessão de validação do protótipo funcional.',
        objective: 'Validação funcional',
        tone: 'consultivo',
        condition: '20 dias',
        whenNotToUse: 'Se validado',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi {{primeiro_nome}}, sistema homologado e equipe treinada com sucesso! Um prazer construir isso junto com a {{empresa}}.',
        objective: 'Celebração de entrega',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
];
