import { ObjectionComprehensive } from '../types/scripts';

export const COMPREHENSIVE_OBJECTIONS: ObjectionComprehensive[] = [
  {
    id: 'obj-1',
    number: 1,
    title: 'Está caro / Achei caro',
    category: 'preco',
    clientPhrase: '"Está caro" / "Achei o valor elevado"',
    underlyingMeaning: 'O cliente não percebeu valor suficiente em relação ao retorno esperado, ou tem receio de não ter ROI.',
    whatNotToSay: '"Mas nosso trabalho é de muita qualidade", "Você não vai achar mais barato", "Posso te dar 50% de desconto agora".',
    diagnosticQuestion: 'Entendo perfeitamente, {{primeiro_nome}}. Quando você diz que achou caro, está comparando com alguma outra solução ou o valor ficou fora do orçamento planejado para este momento?',
    shortResponse: 'Compreendo, {{primeiro_nome}}. Em relação ao retorno de clientes que a {{empresa}} pode ter, o que ficou pesado para você?',
    consultativeResponse: 'Entendo seu ponto, {{primeiro_nome}}. O investimento parece elevado quando olhamos isoladamente. Porém, se esse novo formato trouxer apenas 2 ou 3 novos clientes para a {{empresa}}, o projeto já se paga totalmente. Faz sentido olharmos por essa ótica?',
    whatsappResponse: 'Entendo perfeitamente, {{primeiro_nome}}! O valor só faz sentido se trouxer retorno real para a {{empresa}}. Para caber melhor no seu planejamento: se dividirmos o escopo ou parcelarmos, fica mais confortável?',
    callResponse: 'Compreendo perfeitamente, {{primeiro_nome}}. Na prática, nosso foco é que cada centavo investido retorne em novos clientes para a {{empresa}}. O que você acha de ajustarmos o escopo para caber no que você planejou investir hoje?',
    nextStep: 'Oferecer redução de escopo ou facilidade de parcelamento sem desvalorizar o serviço.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, estive pensando no que conversamos sobre o valor. Se fizermos uma primeira versão mais enxuta por {{preco_ajustado}}, fica viável para a {{empresa}}?',
        objective: 'Apresentar opção de escopo reduzido',
        tone: 'consultivo',
        condition: '1 dia após objeção de preço',
        whenNotToUse: 'Se aceitou outra proposta',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Conseguimos parcelar em 3x sem acréscimo para não impactar o caixa da {{empresa}}. O que acha?',
        objective: 'Condição facilitada de pagamento',
        tone: 'direto',
        condition: '3 dias sem resposta',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Queria só garantir que o orçamento não seja o único motivo para não resolvermos {{problema}} na {{empresa}}.',
        objective: 'Relembrar o problema principal',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando for o momento de priorizar essa melhoria na {{empresa}}, estou por aqui!',
        objective: 'Descompressão suave',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar o acompanhamento desta proposta. Agradeço pela conversa sincera!',
        objective: 'Fechamento de loop',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Tivemos uma condição promocional de início de mês para {{servico}}. Quer dar uma olhada?',
        objective: 'Reativação comercial',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-2',
    number: 2,
    title: 'Não tenho orçamento / Sem verba no momento',
    category: 'orcamento',
    clientPhrase: '"Não tenho orçamento agora" / "Estamos sem verba"',
    underlyingMeaning: 'Falta de liquidez temporária ou não é prioridade financeira no mês.',
    whatNotToSay: '"Como uma empresa desse tamanho não tem dinheiro?", "É um valor tão pequeno!".',
    diagnosticQuestion: 'Compreendo, {{primeiro_nome}}. É uma questão de fluxo de caixa neste mês específico ou vocês costumam planejar esses investimentos por trimestre?',
    shortResponse: 'Entendido, {{primeiro_nome}}. Quando vocês costumam revisar o orçamento para esse tipo de melhoria?',
    consultativeResponse: 'Super compreensível, {{primeiro_nome}}. Muitas empresas com quem trabalho passam por momentos de contenção. O que alguns clientes fazem é deixar a estrutura pronta agora e programar o acerto para o início do próximo mês. Seria uma alternativa viável?',
    whatsappResponse: 'Entendo perfeitamente, {{primeiro_nome}}! O fluxo de caixa manda no negócio. Se a gente programar o início para o próximo mês ou dividir em parcelas menores, ajudaria a {{empresa}}?',
    callResponse: 'Com certeza, {{primeiro_nome}}, entendo seu cuidado com os custos. Vamos fazer o seguinte: deixo as condições anotadas e alinhamos para o momento em que o caixa estiver mais folgado. Quando seria o melhor momento?',
    nextStep: 'Agendar data futura para recontato ou propor pagamento pós-faturamento.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, se for o caso de programar a fatura para o dia 10 do próximo mês, conseguimos flexibilizar para a {{empresa}}.',
        objective: 'Flexibilização de data de vencimento',
        tone: 'consultivo',
        condition: '2 dias após objeção de verba',
        whenNotToUse: 'Se recusou projeto',
      },
      {
        number: 2,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: '{{primeiro_nome}}, tudo bem? Posso deixar reservada essa condição especial para quando você for fechar o planejamento do próximo mês.',
        objective: 'Reserva de condição',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}! Como estão as previsões orçamentárias para o próximo mês na {{empresa}}?',
        objective: 'Checagem de virada de mês',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Oi {{primeiro_nome}}, tudo bem? Passando para saber se o momento financeiro da {{empresa}} já permite olharmos para esse projeto.',
        objective: 'Acompanhamento',
        tone: 'casual',
        condition: '20 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Início de novo mês por aqui! Gostaria de incluir o projeto da {{empresa}} na nossa agenda?',
        objective: 'Reativação de virada de mês',
        tone: 'consultivo',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou o planejamento da {{empresa}} para o novo trimestre.',
        objective: 'Acompanhamento trimestral',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-3',
    number: 3,
    title: 'Vou pensar / Deixa eu pensar',
    category: 'timing',
    clientPhrase: '"Vou pensar e te aviso" / "Deixa eu ver aqui"',
    underlyingMeaning: 'Existe uma dúvida oculta não revelada (preço, confiança, timing ou falta de interesse real).',
    whatNotToSay: '"Vai pensar no quê?", "Não tem o que pensar!", "Tenho promoção só até hoje".',
    diagnosticQuestion: 'Perfeito, {{primeiro_nome}}! Normalmente quando alguém diz que vai pensar, é porque faltou alguma informação importante ou o preço não encaixou. O que ficou com uma interrogação na sua cabeça?',
    shortResponse: 'Claro, {{primeiro_nome}}! Só para eu te ajudar a pensar: qual ponto principal você quer avaliar?',
    consultativeResponse: 'Faz todo sentido, {{primeiro_nome}}. Decisões boas são pensadas. Para te ajudar nessa reflexão: tem algum ponto específico de prazo, investimento ou resultado que você queira que eu esclareça melhor?',
    whatsappResponse: 'Super justo, {{primeiro_nome}}! Fique à vontade para pensar. Se tiver qualquer dúvida sobre prazos, formas de pagamento ou funcionamento, pode me mandar por aqui. Te dou um toque na quinta-feira para saber o que achou, pode ser?',
    callResponse: 'Com certeza, {{primeiro_nome}}, entendo perfeitamente. Geralmente quando meus clientes precisam pensar, é sobre a forma de pagamento ou se o retorno vai valer a pena. Qual dessas duas coisas pesa mais para você?',
    nextStep: 'Descobrir a dúvida real e agendar um horário específico de retorno.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu pensar um pouco sobre a proposta da {{empresa}}? Ficou alguma dúvida?',
        objective: 'Checagem respeitosa de 24h',
        tone: 'consultivo',
        condition: '1 dia após "vou pensar"',
        whenNotToUse: 'Se pediu mais prazo',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Preparei um resumo de 3 pontos para te ajudar a avaliar com calma.',
        objective: 'Resumo de apoio à decisão',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Chegou a alguma conclusão sobre o projeto ou prefere deixar para outro momento?',
        objective: 'Desarmar indecisão',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Sem pressão nenhuma: se não for o momento para a {{empresa}}, pode me dizer com total franqueza!',
        objective: 'Permissão de "não"',
        tone: 'consultivo',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou fechar essa proposta por aqui para não te incomodar. Um abraço!',
        objective: 'Fechamento de loop',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando só para saber como ficaram os planos da {{empresa}}.',
        objective: 'Reativação a 35 dias',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-4',
    number: 4,
    title: 'Preciso falar com meu sócio / diretoria',
    category: 'decisor',
    clientPhrase: '"Preciso ver com meu sócio" / "Vou apresentar para a diretoria"',
    underlyingMeaning: 'O interlocutor não decide sozinho ou está usando o sócio como escudo para não se comprometer.',
    whatNotToSay: '"Mas você não tem autonomia?", "Ele vai aprovar na hora, nem precisa falar com ele".',
    diagnosticQuestion: 'Com certeza, {{primeiro_nome}}! Na sua visão pessoal, você acha que essa proposta resolve o que a {{empresa}} precisa? E qual o ponto que seu sócio costuma ser mais exigente?',
    shortResponse: 'Perfeito, {{primeiro_nome}}! O que seu sócio normalmente mais preza nesse tipo de decisão: prazo, preço ou retorno?',
    consultativeResponse: 'Totalmente compreensível, {{primeiro_nome}}. Decisões societárias precisam de alinhamento. Para te ajudar a apresentar, posso preparar um resumo executivo em 1 página com o antes e depois da {{empresa}} para ele bater o olho e entender na hora. O que acha?',
    whatsappResponse: 'Excelente, {{primeiro_nome}}! Quer que eu te envie um resumo bem direto em tópicos com o protótipo para você apenas encaminhar no WhatsApp do seu sócio?',
    callResponse: 'Perfeito, {{primeiro_nome}}. Se quiser, podemos fazer uma chamada rápida de 10 minutos nós três juntos para eu tirar as dúvidas técnicas dele diretamente, poupando seu tempo. Faria sentido?',
    nextStep: 'Municiar o contato com materiais visuais claros para defender a proposta internamente.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu mostrar o exemplo para o seu sócio? O que ele achou?',
        objective: 'Checagem da conversa com o sócio',
        tone: 'consultivo',
        condition: '1 dia após reunião com sócio',
        whenNotToUse: 'Se a reunião ainda não ocorreu',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Surgiu alguma dúvida por parte da diretoria que eu possa esclarecer?',
        objective: 'Apoio a dúvidas do sócio',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Conseguiram alinhar a decisão internamente na {{empresa}}?',
        objective: 'Checagem de alinhamento',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se o seu sócio preferir outro formato ou cronograma, podemos adaptar.',
        objective: 'Flexibilidade para o sócio',
        tone: 'consultivo',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou deixar a proposta em espera por aqui. Um abraço para vocês!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Chegaram a bater o martelo sobre a estratégia digital da {{empresa}}?',
        objective: 'Reativação',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-5',
    number: 5,
    title: 'Não é prioridade agora / Momento errado',
    category: 'timing',
    clientPhrase: '"Não é nossa prioridade no momento" / "Agora estamos focados em outra coisa"',
    underlyingMeaning: 'A empresa tem outras urgências ou não percebeu a gravidade do problema atual.',
    whatNotToSay: '"Deveria ser prioridade!", "Se você não fizer agora vai quebrar", "Isso é mais importante que o resto".',
    diagnosticQuestion: 'Compreendo, {{primeiro_nome}}. Qual é o foco principal da {{empresa}} neste trimestre? Pergunto para saber se nossa solução atrapalha ou ajuda esse objetivo.',
    shortResponse: 'Entendido, {{primeiro_nome}}. Quando você acredita que isso deve entrar no radar da equipe?',
    consultativeResponse: 'Faz todo sentido respeitar o foco da empresa, {{primeiro_nome}}. Como nosso processo é 100% executado por nós, isso não exige esforço ou tempo do seu time. Seria o caso de deixar rodando sem tirar o foco de vocês ou prefere realmente adiar?',
    whatsappResponse: 'Entendido, {{primeiro_nome}}! O foco tem que ser respeitado. Vou deixar uma anotação para te dar um alô em [mês seguinte]. Posso te procurar em que data?',
    callResponse: 'Com certeza, {{primeiro_nome}}. Sei como é ter que priorizar incêndios maiores. Me diga uma coisa: se esse projeto rodar sem exigir nem 30 minutos da sua semana, ainda assim é melhor adiar?',
    nextStep: 'Validar a data exata de reabertura ou mostrar baixo consumo de tempo da equipe.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Oi {{primeiro_nome}}, só para eu organizar minha agenda aqui: qual mês seria mais oportuno para eu te procurar?',
        objective: 'Coleta de data precisa de recontato',
        tone: 'consultivo',
        condition: '3 dias após objeção de prioridade',
        whenNotToUse: 'Se já definiu data',
      },
      {
        number: 2,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: '{{primeiro_nome}}, tudo bem? Sucesso no projeto prioritário de vocês aí na {{empresa}}!',
        objective: 'Desejo de sucesso sem cobrança',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}! Como está o andamento daquelas metas prioritárias na {{empresa}}?',
        objective: 'Checagem de descompressão',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi {{primeiro_nome}}, tudo bem? Será que agora o momento está mais tranquilo para olharmos aquele projeto?',
        objective: 'Checagem de novo ciclo',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '70 dias',
        intervalHours: 1680,
        message: 'Olá, {{primeiro_nome}}. Início de novo trimestre! Se quiser retomar a conversa sobre {{servico}}, estou à disposição.',
        objective: 'Abertura de trimestre',
        tone: 'consultivo',
        condition: '70 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '100 dias',
        intervalHours: 2400,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para deixar um abraço e saber como estão os negócios na {{empresa}}.',
        objective: 'Reativação semestral',
        tone: 'casual',
        condition: '100 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-6',
    number: 6,
    title: 'Não tenho interesse (Técnica dos 3 Cs)',
    category: 'necessidade',
    clientPhrase: '"Não temos interesse" / "Não preciso"',
    underlyingMeaning: 'Reação automática de defesa contra vendedores, ou realmente não entendeu o problema.',
    whatNotToSay: '"Como assim não tem interesse?", "Você está perdendo dinheiro!", continuar empurrando texto.',
    diagnosticQuestion: 'Sem problemas, {{primeiro_nome}}! É porque vocês já têm esse ponto 100% resolvido com outra equipe ou porque realmente não veem necessidade hoje?',
    shortResponse: 'Totalmente compreendido, {{primeiro_nome}}! Obrigado pela clareza.',
    consultativeResponse: '1. Concordar: Perfeito, {{primeiro_nome}}, agradeço pela franqueza! 2. Redirecionar: É natural não ter interesse quando não se está buscando ativamente por isso. 3. Conduzir: Só para eu não te incomodar mais: se no futuro precisarem de apoio em {{servico}}, posso te mandar novidades ou prefere que encerre por aqui?',
    whatsappResponse: 'Entendido, {{primeiro_nome}}! Agradeço a resposta rápida. Vou encerrar meus contatos por aqui para respeitar o seu espaço. Se um dia a {{empresa}} quiser avaliar melhorias em {{servico}}, meu WhatsApp continua este!',
    callResponse: 'Perfeito, {{primeiro_nome}}, respeito 100% sua posição. Não vou insistir. Se me permite apenas uma pergunta rápida: vocês já têm uma pessoa interna cuidando disso hoje?',
    nextStep: 'Aplicar os 3 Cs (Concordar, Redirecionar, Conduzir) e respeitar o espaço do prospect.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Obrigado pela atenção até aqui, {{primeiro_nome}}! Desejo muito sucesso para a {{empresa}}.',
        objective: 'Encerramento com elegância',
        tone: 'profissional',
        condition: '1 dia após "não tenho interesse"',
        whenNotToUse: 'Se pediu para nunca mais mandar mensagem (DNC)',
      },
      {
        number: 2,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Oi {{primeiro_nome}}, caso queira guardar meu contato para qualquer emergência com o site da {{empresa}}, fico à disposição.',
        objective: 'Contato de suporte de prontidão',
        tone: 'casual',
        condition: '14 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 3,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Olá, {{primeiro_nome}}! Vi uma matéria recente sobre {{nicho}} e lembrei da {{empresa}}. Achei que você poderia gostar do insight!',
        objective: 'Entrega de valor desinteressada',
        tone: 'consultivo',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '90 dias',
        intervalHours: 2160,
        message: 'Oi {{primeiro_nome}}, tudo bem? Tivemos uma atualização de tecnologias que reduziu custos em 40%. Se fizer sentido dar uma olhada, me avise.',
        objective: 'Tentativa de reativação com nova proposta de valor',
        tone: 'casual',
        condition: '90 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 5,
        intervalRecommended: '150 dias',
        intervalHours: 3600,
        message: 'Olá, {{primeiro_nome}}. Como estão os resultados da {{empresa}} neste semestre? Um abraço!',
        objective: 'Manutenção de relacionamento',
        tone: 'profissional',
        condition: '150 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '210 dias',
        intervalHours: 5040,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando só para saber se a {{empresa}} tem novas metas digitais para este ano.',
        objective: 'Reativação anual',
        tone: 'casual',
        condition: '210 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-7',
    number: 7,
    title: 'Já tenho quem faça / Já temos agência ou programador',
    category: 'concorrencia',
    clientPhrase: '"Já temos agência" / "Já temos uma pessoa que cuida disso"',
    underlyingMeaning: 'Já existe um prestador de serviço e o cliente não quer o trabalho de trocar, ou tem relação de confiança.',
    whatNotToSay: '"Essa agência é ruim", "Eles estão te cobrando caro", "Eu faço muito melhor que eles".',
    diagnosticQuestion: 'Excelente, {{primeiro_nome}}! É ótimo saber que vocês já investem nisso. E vocês estão 100% satisfeitos com a velocidade de resposta e os resultados que eles trazem?',
    shortResponse: 'Que ótimo, {{primeiro_nome}}! E eles cuidam tanto da parte visual quanto das atualizações frequentes no WhatsApp?',
    consultativeResponse: 'Muito bom saber disso, {{primeiro_nome}}! Meu objetivo não é substituir o profissional ou a agência de vocês, mas sim somar caso exista alguma demanda pontual que eles não consigam atender com agilidade. Se surgir alguma necessidade específica, podemos ser um plano B.',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}! Fico feliz que a {{empresa}} já tenha esse suporte. Posso te deixar meu contato como uma opção de contingência/backup para quando precisarem de algo urgente?',
    callResponse: 'Excelente, {{primeiro_nome}}, ter um parceiro é fundamental. Me diz uma coisa: hoje quando você pede uma alteração ou página nova, eles te entregam em quantos dias?',
    nextStep: 'Posicionar-se como alternativa de backup/segunda opinião sem atacar o parceiro atual.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, caso sua equipe precise de uma segunda opinião técnica sobre qualquer ponto, pode me mandar uma mensagem.',
        objective: 'Posicionamento como consultor neutro',
        tone: 'consultivo',
        condition: '2 dias após objeção de agência',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 2,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: '{{primeiro_nome}}, tudo bem? Se eles precisarem de apoio para implementar aquela melhoria em {{observacao_especifica}}, posso ajudar.',
        objective: 'Disponibilidade colaborativa',
        tone: 'casual',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}! Como ficaram as entregas digitais da {{empresa}} neste último mês?',
        objective: 'Checagem de satisfação com concorrente',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi {{primeiro_nome}}, tudo bem? Passando apenas para saber se precisaram de alguma demanda extra de tecnologia.',
        objective: 'Oportunidade de demanda reprimida',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '100 dias',
        intervalHours: 2400,
        message: 'Olá, {{primeiro_nome}}. Continuo à disposição caso a {{empresa}} precise de um parceiro ágil para novos projetos.',
        objective: 'Manutenção de presença',
        tone: 'profissional',
        condition: '100 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 6,
        intervalRecommended: '180 dias',
        intervalHours: 4320,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como estão os projetos digitais da {{empresa}} para este semestre?',
        objective: 'Reativação semestral',
        tone: 'casual',
        condition: '180 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-8',
    number: 8,
    title: 'Já tenho site e ele funciona bem',
    category: 'necessidade',
    clientPhrase: '"Já temos site e ele atende a gente" / "Nosso site já funciona"',
    underlyingMeaning: 'O cliente acredita que ter um site institucional estático é suficiente e não percebe a perda de conversão mobile/WhatsApp.',
    whatNotToSay: '"Seu site é feio/antigo", "Seu site não presta", "Você não entende de internet".',
    diagnosticQuestion: 'Que ótimo que já têm presença online, {{primeiro_nome}}! Hoje a maioria dos seus clientes entra no site pelo celular ou computador? E quantos entram em contato direto pelo WhatsApp todo mês?',
    shortResponse: 'Muito legal, {{primeiro_nome}}! E hoje o site de vocês carrega em menos de 2 segundos no 4G?',
    consultativeResponse: 'Excelente ter uma base pronta, {{primeiro_nome}}! O que identifiquei não é que o site de vocês não funciona, mas sim que pequenas otimizações de velocidade e botões diretos de agendamento poderiam dobrar a taxa de contatos recebidos. Vale 2 minutos para ver um comparativo?',
    whatsappResponse: 'Muito bom, {{primeiro_nome}}! É um ótimo ponto de partida. Notei apenas um detalhe prático: {{observacao_especifica}}. Ajustar só isso já aumentaria os contatos no WhatsApp sem precisar refazer tudo. Posso te mandar o print?',
    callResponse: 'Perfeito, {{primeiro_nome}}. Ter o site no ar é o primeiro passo. Minha proposta é apenas potencializar o que vocês já têm para que mais visitantes virem conversas reais no WhatsApp. O que você acha de olhar um teste rápido de velocidade?',
    nextStep: 'Mostrar otimização pontual que potencializa o site existente sem descarte total.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o print que tirei mostra exatamente onde o cliente pode estar desistindo no celular. Quer ver?',
        objective: 'Oferecer diagnóstico visual leve',
        tone: 'casual',
        condition: '1 dia após "já temos site"',
        whenNotToUse: 'Se rejeitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Não precisamos mexer na estrutura inteira, apenas incluir o botão inteligente de atendimento.',
        objective: 'Minimizar esforço e medo de refação',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição caso queiram fazer um teste A/B no site da {{empresa}}.',
        objective: 'Proposta de teste A/B',
        tone: 'direto',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser otimizar a velocidade de carregamento, me avise!',
        objective: 'Porta aberta',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Sucesso contínuo com os canais da {{empresa}}! Um abraço.',
        objective: 'Encerramento',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como tem sido o volume de contatos pelo site da {{empresa}}.',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-9',
    number: 9,
    title: 'Não acredito que isso traga clientes / Ceticismo com digital',
    category: 'confianca',
    clientPhrase: '"Isso não traz clientes para o nosso ramo" / "Meu negócio é só por indicação"',
    underlyingMeaning: 'Já teve experiências ruins no passado (promessas de agências que não deram em nada) ou desconfia do meio digital.',
    whatNotToSay: '"Você está antiquado", "Quem não tá no Google vai falir", prometer rios de dinheiro.',
    diagnosticQuestion: 'Compreendo sua desconfiança, {{primeiro_nome}}. Vocês já chegaram a contratar alguém no passado que prometeu mundos e fundos e não entregou nada?',
    shortResponse: 'Super justo seu ceticismo, {{primeiro_nome}}. Indicação sempre foi e será o canal mais forte. Mas o que acontece quando o cliente indicado busca a {{empresa}} no Google antes de mandar mensagem?',
    consultativeResponse: 'Entendo perfeitamente, {{primeiro_nome}}. O mercado está cheio de promessas mágicas. Meu trabalho não é prometer vendas automáticas, mas sim garantir que quem já ouviu falar da {{empresa}} ou procura pelo seu serviço encontre uma apresentação profissional e consiga falar com você em 1 clique. Faz sentido essa diferença?',
    whatsappResponse: 'Faz todo sentido sua postura, {{primeiro_nome}}! O melhor cliente é sempre o que vem por indicação. A questão é: quando alguém indica a {{empresa}}, essa pessoa pesquisa seu nome antes de ligar. Se ela não achar uma página rápida, pode hesitar. Quer ver um exemplo prático?',
    callResponse: 'Compreendo perfeitamente, {{primeiro_nome}}, e concordo: indicação é ouro. O nosso projeto serve justamente para validar a indicação: quando o cliente recebe o seu contato, ele entra no site e vê que a {{empresa}} é referência séria no mercado.',
    nextStep: 'Enquadrar o projeto como validador de autoridade para clientes já indicados.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, você já procurou no Google por um profissional antes de contratar, só para ver se era de confiança? Com os seus clientes acontece igual.',
        objective: 'Analogia com a própria experiência do lead',
        tone: 'consultivo',
        condition: '1 dia após objeção de ceticismo',
        whenNotToUse: 'Se rejeitou',
      },
      {
        number: 2,
        intervalRecommended: '3 days',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? A ideia é ser uma vitrine de credibilidade que fortalece suas indicações.',
        objective: 'Reforçar conceito de credibilidade',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Se quiser ver sem compromisso como ficaria essa vitrine para a {{empresa}}, é só falar.',
        objective: 'Oferta sem risco',
        tone: 'direto',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Sucesso nos atendimentos por indicação aí na {{empresa}}!',
        objective: 'Apoio sem cobrança',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição caso decida estruturar uma presença digital sólida no futuro.',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como tem sido o fluxo de novos contatos na {{empresa}} neste trimestre?',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-10',
    number: 10,
    title: 'Manda por e-mail / Manda uma proposta em PDF',
    category: 'timing',
    clientPhrase: '"Me manda por e-mail para eu ver" / "Manda uma proposta formal"',
    underlyingMeaning: 'Quer se livrar da conversa no WhatsApp, ou realmente precisa de documento formal para aprovação.',
    whatNotToSay: '"Não mando por e-mail", "E-mail ninguém lê", mandar um PDF genérico de 30 páginas.',
    diagnosticQuestion: 'Claro, {{primeiro_nome}}! Envio sim. Para eu colocar os dados exatos e não mandar algo genérico: qual é o seu melhor e-mail e qual o ponto principal que você precisa que esteja detalhado na proposta?',
    shortResponse: 'Envio com certeza, {{primeiro_nome}}! Qual o seu e-mail?',
    consultativeResponse: 'Com certeza, {{primeiro_nome}}! Vou preparar um documento de 2 páginas bem direto com o escopo, cronograma e valores. Posso te enviar por e-mail e te dar um aviso rápido por aqui no WhatsApp assim que disparar?',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}! Qual é o melhor e-mail da {{empresa}}? Já monto um PDF resumido e te aviso por aqui assim que enviar para você não correr o risco de cair no spam.',
    callResponse: 'Com prazer, {{primeiro_nome}}! Me passa o e-mail que envio em 15 minutos. Te aviso no WhatsApp em seguida para confirmar se chegou.',
    nextStep: 'Pegar o e-mail, enviar proposta concisa e confirmar o recebimento via WhatsApp.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2–4 horas',
        intervalHours: 3,
        message: 'Oi {{primeiro_nome}}, proposta enviada para o seu e-mail! Consegue só me confirmar se chegou na sua caixa de entrada?',
        objective: 'Confirmação de recebimento no e-mail',
        tone: 'casual',
        condition: '2-4h após envio do e-mail',
        whenNotToUse: 'Se confirmou',
      },
      {
        number: 2,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: '{{primeiro_nome}}, tudo bem? Teve chance de dar uma olhada nas duas páginas da proposta?',
        objective: 'Checagem de leitura',
        tone: 'consultivo',
        condition: '1 dia após envio',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Olá, {{primeiro_nome}}! Ficou alguma dúvida sobre os termos ou escopo que enviei no e-mail?',
        objective: 'Tirar dúvidas do PDF',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Oi {{primeiro_nome}}, tudo bem? Caso queira que eu faça algum ajuste nos itens da proposta, é só me falar.',
        objective: 'Ajuste de escopo',
        tone: 'casual',
        condition: '6 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}. Vou manter a proposta ativa por mais 5 dias. Qualquer dúvida estou por aqui!',
        objective: 'Aviso de validade',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como ficou a avaliação daquela proposta da {{empresa}}?',
        objective: 'Reativação a 25 dias',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-11',
    number: 11,
    title: 'Qual é o preço? / Manda o preço logo',
    category: 'preco',
    clientPhrase: '"Quanto custa?" / "Manda o valor direto"',
    underlyingMeaning: 'Quer qualificar se tem condições de pagar antes de perder tempo conversando.',
    whatNotToSay: '"Depende de muita coisa...", se recusar a dar faixa de valor, mandar textão enrolando.',
    diagnosticQuestion: 'Com certeza, {{primeiro_nome}}! Projetos desse tipo costumam variar de {{preco_minimo}} a {{preco_maximo}}, dependendo do que a {{empresa}} precisa. Para eu te passar o valor exato: você precisa apenas de {{opcao_simples}} ou também quer {{opcao_completa}}?',
    shortResponse: 'Fica na faixa de {{preco}} completo. Para eu confirmar se esse é o valor exato: você já tem logotipo e fotos da {{empresa}}?',
    consultativeResponse: 'Transparência total, {{primeiro_nome}}: para o que você precisa na {{empresa}}, o valor fica exatamente em {{preco}}, sem mensalidades surpresa ou taxas escondidas. Já inclui {{beneficio_incluso}}. Fica dentro do que você esperava?',
    whatsappResponse: 'Direto ao ponto, {{primeiro_nome}}: o investimento completo fica em {{preco}}, com tudo pronto para rodar em {{prazo_entrega}} dias. Você aprova antes e paga depois da validação. O que acha?',
    callResponse: 'Com prazer, {{primeiro_nome}}! Para esse formato completo na {{empresa}}, fica em {{preco}}. O melhor é que você só faz o acerto final quando o projeto estiver aprovado por você. Fica bom assim?',
    nextStep: 'Dar o valor com âncora de segurança (aprovação antes) e fazer pergunta de fechamento.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, o que achou do valor de {{preco}} para a {{empresa}}? Fez sentido para você?',
        objective: 'Checar reação ao preço direto',
        tone: 'consultivo',
        condition: '1 dia após resposta de preço',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, se preferir podemos parcelar para ficar ainda mais leve. O que acha?',
        objective: 'Oferecer parcelamento',
        tone: 'casual',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Fique à vontade para me dizer se o valor ficou acima do que você tinha em mente.',
        objective: 'Diagnóstico de orçamento',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser dar andamento, a condição está mantida para a {{empresa}}.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou liberar essa vaga na agenda de produção. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Alguma novidade sobre o projeto da {{empresa}}?',
        objective: 'Reativação a 35 dias',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-12',
    number: 12,
    title: 'Não quero pagar adiantado / Medo de calote',
    category: 'confianca',
    clientPhrase: '"Não pago nada antes de ver pronto" / "Como sei que você vai entregar?"',
    underlyingMeaning: 'Trauma de prestadores que pegaram entrada e sumiram, ou desconfiança natural com compras online.',
    whatNotToSay: '"Eu sou honesto", "Você tem que confiar em mim", ficar ofendido com a desconfiança.',
    diagnosticQuestion: 'Total razão, {{primeiro_nome}}! Infelizmente existem muitos maus profissionais no mercado. Se você puder ver e aprovar o projeto antes do pagamento final, isso te daria 100% de tranquilidade?',
    shortResponse: 'Entendo perfeitamente, {{primeiro_nome}}! É exatamente por isso que nós apresentamos a demonstração e o protótipo aprovado antes de você fazer o acerto.',
    consultativeResponse: 'Sua preocupação é 100% legítima, {{primeiro_nome}}. Por isso trabalhamos com total transparência: nós desenvolvemos a estrutura, colocamos em link de homologação para você testar no seu celular, e você só efetua o pagamento após validar e aprovar o resultado. Assim o risco é todo nosso. Fica seguro para você?',
    whatsappResponse: 'Compreendo perfeitamente, {{primeiro_nome}}! Você não precisa arriscar nada: eu monto o projeto, você valida tudo no ar, e só depois acertamos. Fica bom assim para a {{empresa}}?',
    callResponse: 'Com certeza, {{primeiro_nome}}, ninguém gosta de pagar no escuro. Vamos fazer assim: eu coloco o projeto para rodar no ambiente de testes, você confere no detalhe, e só quando você me der nota 10 a gente formaliza o pagamento. Combinado?',
    nextStep: 'Eliminar o risco com homologação e aprovação pré-pagamento.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, essa garantia de validar antes de pagar te deixa tranquilo para iniciarmos?',
        objective: 'Confirmação de segurança',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se confirmou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Já posso subir o primeiro rascunho no ambiente de homologação para você ver.',
        objective: 'Proatividade de entrega',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição para tirar qualquer dúvida sobre nossos termos de entrega e garantia.',
        objective: 'Esclarecimento de garantias',
        tone: 'profissional',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser fazer o teste sem compromisso, é só avisar.',
        objective: 'Lembrete sem compromisso',
        tone: 'casual',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar o acompanhamento por aqui. Muito sucesso com a {{empresa}}!',
        objective: 'Encerramento',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como estão os projetos digitais da {{empresa}}.',
        objective: 'Reativação',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-13',
    number: 13,
    title: 'Preciso comparar com outros orçamentos',
    category: 'concorrencia',
    clientPhrase: '"Estou cotando com outros fornecedores" / "Preciso comparar"',
    underlyingMeaning: 'Quer ter certeza de que não está pagando caro e quer parâmetros de mercado.',
    whatNotToSay: '"Não precisa comparar com ninguém", "Os outros vão te enrolar", "Se você não fechar agora o preço sobre".',
    diagnosticQuestion: 'Muito prudente, {{primeiro_nome}}! É fundamental comparar. Quais critérios você costuma usar para comparar: só o preço final, a velocidade de entrega ou o suporte depois que estiver no ar?',
    shortResponse: 'Excelente iniciativa, {{primeiro_nome}}! Para te ajudar nessa comparação: preste atenção se eles incluem domínio, hospedagem e suporte pós-entrega.',
    consultativeResponse: 'Faz muito bem em cotar, {{primeiro_nome}}! Uma dica de ouro: ao comparar, verifique se a outra proposta exige mensalidades obrigatórias ou se o código e domínio ficam 100% no nome da {{empresa}}. Na nossa proposta você não fica preso a nenhuma taxa mensal. Posso te enviar um checklist do que checar nas outras propostas?',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}! Cotar é essencial. Para você comparar de igual para igual: nossa proposta entrega em {{prazo_entrega}} dias, sem mensalidades e com aprovação prévia. Te dou um toque na sexta para saber o que achou das comparações, pode ser?',
    callResponse: 'Com certeza, {{primeiro_nome}}, comparar é a decisão mais inteligente. O que a maioria dos clientes nota ao nos comparar com freelancers ou agências grandes é que nós entregamos com velocidade de dias, com suporte direto no WhatsApp e sem burocracia.',
    nextStep: 'Entregar critérios de diferenciação (sem mensalidades, velocidade, aprovação prévia).',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, conseguiu receber as outras cotações? Se quiser ajuda para analisar os escopos técnicos, estou à disposição.',
        objective: 'Apoio na análise comparativa',
        tone: 'consultivo',
        condition: '2 dias após "vou comparar"',
        whenNotToUse: 'Se já escolheu',
      },
      {
        number: 2,
        intervalRecommended: '4 dias',
        intervalHours: 96,
        message: '{{primeiro_nome}}, tudo bem? O que você achou dos prazos e condições dos outros orçamentos?',
        objective: 'Checagem de prazos da concorrência',
        tone: 'direto',
        condition: '4 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '8 dias',
        intervalHours: 192,
        message: 'Olá, {{primeiro_nome}}! Conseguimos manter a condição e garantir o início nesta semana para a {{empresa}}.',
        objective: 'Agilidade como diferencial',
        tone: 'profissional',
        condition: '8 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Chegou a fechar com algum fornecedor ou ainda está avaliando?',
        objective: 'Status da concorrência',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}. Vou congelar a proposta da {{empresa}} por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Caso o fornecedor contratado não tenha entregue como o esperado, conte conosco!',
        objective: 'Porta de resgate',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-14',
    number: 14,
    title: 'Não tenho tempo agora / Estou na correria',
    category: 'timing',
    clientPhrase: '"Estou sem tempo para ver isso" / "Muito corrido por aqui"',
    underlyingMeaning: 'Receio de que o projeto exija muitas reuniões, envio de textos e esforço do cliente.',
    whatNotToSay: '"É rapidinho, só 1 hora de reunião", "Quem quer arruma tempo".',
    diagnosticQuestion: 'Sei bem como é a rotina, {{primeiro_nome}}! Se eu te disser que você não vai precisar gastar mais do que 5 minutos no WhatsApp para aprovar tudo, isso facilitaria sua vida?',
    shortResponse: 'Compreendo perfeitamente, {{primeiro_nome}}! O projeto é justamente desenhado para não tomar nem 10 minutos do seu tempo.',
    consultativeResponse: 'Entendo perfeitamente a correria, {{primeiro_nome}}. É justamente por isso que nosso modelo é "chave na mão": nós redigimos os textos, organizamos a estrutura e te enviamos o link pronto no WhatsApp para você apenas dar um "ok". Você não precisa preencher formulários chatos ou fazer reuniões longas.',
    whatsappResponse: 'Super compreensível, {{primeiro_nome}}! Você não vai precisar gastar tempo com nada: eu preparo tudo e te mando só para você olhar no celular em 1 minuto. Posso adiantar por aqui?',
    callResponse: 'Totalmente compreensível, {{primeiro_nome}}, empresário não tem tempo a perder. Nosso trabalho é tirar o peso das suas costas. Eu monto a primeira versão completa e te mando um print direto.',
    nextStep: 'Assumir todo o trabalho operacional e pedir apenas micro-aprovação de 1 minuto.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, deixei tudo montado para você só dar uma olhada de 30 segundos no celular quando tiver uma folga.',
        objective: 'Alívio máximo de tempo',
        tone: 'casual',
        condition: '1 dia após objeção de tempo',
        whenNotToUse: 'Se pediu para não enviar',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Sem reuniões e sem complicação: só o link direto para aprovação.',
        objective: 'Reforçar ausência de reuniões',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Quando tiver uma brecha no calendário, me dá um toque por aqui!',
        objective: 'Aguardar momento livre',
        tone: 'profissional',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Oi {{primeiro_nome}}, tudo bem? Espero que a rotina na {{empresa}} esteja mais tranquila agora.',
        objective: 'Checagem de alívio de rotina',
        tone: 'casual',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}. Vou pausar meus contatos para não sobrecarregar seu WhatsApp. Um abraço!',
        objective: 'Pausa amigável',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber se as coisas acalmaram por aí na {{empresa}}.',
        objective: 'Reativação a 45 dias',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-15',
    number: 15,
    title: 'Conheço quem faça de graça / Meu sobrinho faz',
    category: 'concorrencia',
    clientPhrase: '"Meu sobrinho/conhecido faz de graça ou bem baratinho"',
    underlyingMeaning: 'Acha que criação de site é apenas estética simples e não entende os impactos de segurança, mobile e conversão de vendas.',
    whatNotToSay: '"Sobrinho só faz porcaria", rir ou ironizar o conhecido do cliente.',
    diagnosticQuestion: 'Que bom que você tem alguém de confiança na família, {{primeiro_nome}}! E ele tem disponibilidade para deixar pronto nesta semana com otimização profissional para o WhatsApp da {{empresa}}?',
    shortResponse: 'Excelente ter essa ajuda, {{primeiro_nome}}! Se ele puder te entregar rápido e com garantia, é uma boa opção.',
    consultativeResponse: 'É ótimo ter conhecidos no setor, {{primeiro_nome}}. A grande diferença prática é que quem faz como favor costuma demorar semanas ou meses para atualizar quando você precisa de urgência. Nós entregamos um projeto profissional em poucos dias, com código limpo e foco em gerar contatos de clientes. Se precisar de uma entrega rápida e garantida, estamos aqui.',
    whatsappResponse: 'Muito legal, {{primeiro_nome}}! Ajuda de conhecidos é sempre bem-vinda. Se por acaso ele estiver sem tempo ou você precisar de algo pronto para rodar já nesta semana, conta comigo!',
    callResponse: 'Com certeza, {{primeiro_nome}}, entendo. O único risco do favor de parentes é o prazo e o suporte quando o site sai do ar. Se você quiser resolver de forma definitiva e profissional sem depender de favores, conte conosco.',
    nextStep: 'Destacar o valor da agilidade comercial, compromisso de prazo e suporte profissional.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Oi {{primeiro_nome}}, seu conhecido conseguiu dar andamento ou a rotina dele está cheia?',
        objective: 'Checar se o conhecido travou',
        tone: 'casual',
        condition: '3 dias após menção de sobrinho/conhecido',
        whenNotToUse: 'Se o conhecido já entregou',
      },
      {
        number: 2,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: '{{primeiro_nome}}, tudo bem? Caso precise de um suporte complementar para colocar o site no ar, me avise!',
        objective: 'Oferta de suporte',
        tone: 'consultivo',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}! Como está o andamento da página da {{empresa}}?',
        objective: 'Acompanhamento',
        tone: 'profissional',
        condition: '20 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se quiser agilizar o projeto profissionalmente sem dores de cabeça, nossa proposta continua de pé.',
        objective: 'Resgate profissional',
        tone: 'direto',
        condition: '35 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Olá, {{primeiro_nome}}. Espero que o projeto tenha dado certo! Qualquer coisa, estou por aqui.',
        objective: 'Pausa amigável',
        tone: 'profissional',
        condition: '60 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '90 dias',
        intervalHours: 2160,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficaram os canais da {{empresa}} neste trimestre.',
        objective: 'Reativação a 90 dias',
        tone: 'casual',
        condition: '90 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-16',
    number: 16,
    title: 'Vou fazer sozinho / Vou usar criador automático / Wix / IA',
    category: 'tecnica',
    clientPhrase: '"Eu mesmo vou fazer no Wix / Canva / IA" / "Vou criar sozinho"',
    underlyingMeaning: 'Quer economizar dinheiro e acredita que ferramentas automáticas entregam o mesmo resultado de conversão e velocidade sem esforço.',
    whatNotToSay: '"Essas ferramentas são um lixo", "Você não sabe programar", "Vai ficar horrível".',
    diagnosticQuestion: 'Essas ferramentas hoje estão muito acessíveis mesmo, {{primeiro_nome}}! Você já tem facilidade com design, configuração de domínio DNS e integrações com o WhatsApp?',
    shortResponse: 'É uma boa opção para começar, {{primeiro_nome}}! O principal cuidado é a velocidade no celular para não espantar clientes.',
    consultativeResponse: 'Essas plataformas são ótimas para rascunhos, {{primeiro_nome}}. A questão é que costumam exigir muitas horas de aprendizado, carregam código pesado que deixa o site lento no 4G e cobram mensalidades caras em dólar todo mês. Nosso serviço entrega o código pronto, super leve, sem mensalidades na plataforma e economiza dezenas de horas suas. Vale a pena gastar seus fins de semana nisso?',
    whatsappResponse: 'Totalmente válido, {{primeiro_nome}}! O único detalhe é que essas ferramentas cobram mensalidade recorrente e tomam muito tempo para configurar. Por {{preco}} você recebe tudo pronto nesta semana, sem perder tempo e sem mensalidade. O que acha de poupar seu tempo?',
    callResponse: 'Com certeza, {{primeiro_nome}}, é uma alternativa. O que a maioria dos empresários me relata é que começam a mexer, perdem 3 ou 4 finais de semana e no fim o resultado não fica profissional. Se quiser economizar seu tempo precioso e focar em vender, nós entregamos chave na mão.',
    nextStep: 'Comparar o custo do tempo do empresário + mensalidades de ferramentas com a entrega chave na mão.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: 'Oi {{primeiro_nome}}, conseguiu testar a ferramenta? Deu certo a parte de configurar domínio e celular?',
        objective: 'Checar fricção técnica da ferramenta',
        tone: 'casual',
        condition: '3 dias após "vou fazer sozinho"',
        whenNotToUse: 'Se terminou o site',
      },
      {
        number: 2,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: '{{primeiro_nome}}, se bater alguma dúvida na integração com o WhatsApp ou formulários, me avise!',
        objective: 'Apoio técnico consultivo',
        tone: 'consultivo',
        condition: '7 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Olá, {{primeiro_nome}}! Se preferir não gastar mais tempo montando telas e quiser receber pronto em 48h, estou por aqui.',
        objective: 'Resgate de tempo',
        tone: 'direto',
        condition: '15 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Oi {{primeiro_nome}}, tudo bem? Conseguiu colocar a página no ar?',
        objective: 'Checagem de conclusão',
        tone: 'casual',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '50 dias',
        intervalHours: 1200,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição para auditar ou aprimorar o que você estruturou. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '50 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '80 dias',
        intervalHours: 1920,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou o site da {{empresa}}.',
        objective: 'Reativação a 80 dias',
        tone: 'casual',
        condition: '80 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-17',
    number: 17,
    title: 'Quero ver trabalhos anteriores / Portfólio / Casos reais',
    category: 'confianca',
    clientPhrase: '"Tem exemplos de trabalhos parecidos?" / "Me manda seus clientes"',
    underlyingMeaning: 'Quer prova de competência e segurança de que o trabalho tem padrão estético elevado.',
    whatNotToSay: 'Inventar marcas famosas, mandar links quebrados ou prints forjados.',
    diagnosticQuestion: 'Com muito prazer, {{primeiro_nome}}! O que é mais importante para você avaliar no portfólio: o design visual, a velocidade de navegação ou a facilidade de uso no celular?',
    shortResponse: 'Envio agora mesmo, {{primeiro_nome}}! Seguem demonstrações ativas que montei: {{links_demonstracoes}}.',
    consultativeResponse: 'Com certeza, {{primeiro_nome}}! Além dos projetos no ar, o que mais gosto de fazer é demonstrar ao vivo: preparei um conceito adaptado para a realidade da {{empresa}} em {{link_prototipo}}. Assim você avalia a qualidade aplicada diretamente ao seu nicho. O que achou?',
    whatsappResponse: 'Claro, {{primeiro_nome}}! Seguem modelos funcionais recentes: {{links_demonstracoes}}. E para a {{empresa}}, estruturei este conceito direto: {{link_prototipo}}. Consegue abrir?',
    callResponse: 'Com todo prazer, {{primeiro_nome}}! Te mandei no WhatsApp agora mesmo links navegáveis para você testar no seu celular. Repare na velocidade instantânea de abertura de cada página.',
    nextStep: 'Enviar links reais e o conceito personalizado da própria empresa do prospect.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu abrir os exemplos no celular? O que achou do acabamento?',
        objective: 'Checagem de impressão do portfólio',
        tone: 'casual',
        condition: '1 dia após envio de portfólio',
        whenNotToUse: 'Se elogiou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Aquele conceito que montei para a {{empresa}} segue o mesmo padrão de qualidade.',
        objective: 'Conectar portfólio à empresa do lead',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Ficou com alguma dúvida sobre como adaptamos o layout para as cores da {{empresa}}?',
        objective: 'Personalização visual',
        tone: 'direto',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser dar andamento ao seu projeto, estamos prontos.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}. Vou liberar o ambiente de testes por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '20 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '40 dias',
        intervalHours: 960,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Subimos novos projetos recentes no portfólio. Quer dar uma olhada?',
        objective: 'Reativação com novos projetos',
        tone: 'casual',
        condition: '40 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-18',
    number: 18,
    title: 'Pode fazer um desconto? / Faz mais barato?',
    category: 'preco',
    clientPhrase: '"Dá para dar um desconto?" / "Faz por metade?"',
    underlyingMeaning: 'Quer sentir que fez um bom negócio ou está testando sua margem de segurança.',
    whatNotToSay: '"Sim, faço por qualquer valor", "Não dou desconto de jeito nenhum e ponto final".',
    diagnosticQuestion: 'Compreendo, {{primeiro_nome}}! Para eu ver o que consigo ajustar: se fecharmos hoje, qual valor ficaria excelente para você?',
    shortResponse: 'Consigo manter esse preço especial de {{preco}} incluindo o suporte prioritário sem custo.',
    consultativeResponse: 'Entendo perfeitamente, {{primeiro_nome}}! Para mantermos a qualidade máxima e a entrega rápida, não costumamos reduzir o valor sem mexer no escopo. O que consigo fazer para te prestigiar é incluir {{bonus_incluso}} sem custo adicional ou facilitar o parcelamento. Fica justo assim?',
    whatsappResponse: 'Oi {{primeiro_nome}}! O valor de {{preco}} já está com uma margem super enxuta. Para te ajudar a fechar agora: consigo incluir a configuração completa do botão de agendamento de bônus ou parcelar em 3x. Qual opção te ajuda mais?',
    callResponse: 'Com certeza, {{primeiro_nome}}, entendo seu lado negociador. Para mantermos o padrão de excelência, o que posso fazer de melhor é te entregar o projeto pronto e validado com o suporte do primeiro mês 100% gratuito. Fechamos assim?',
    nextStep: 'Trocar concessões (adicionar bônus ou parcelamento em troca de fechamento imediato).',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, essa condição com o bônus incluído atende ao que você precisa para começarmos?',
        objective: 'Confirmação do acordo de bônus',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se aceitou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, consigo segurar essa condição com bônus até amanhã para a {{empresa}}. O que acha?',
        objective: 'Gatilho de validade de condição',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '6 dias',
        intervalHours: 144,
        message: 'Olá, {{primeiro_nome}}! Se preferir uma versão com escopo mais enxuto por {{preco_ajustado}}, também é super viável.',
        objective: 'Alternativa de escopo menor',
        tone: 'profissional',
        condition: '6 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando for o momento de iniciar o projeto da {{empresa}}, me avisa!',
        objective: 'Lembrete',
        tone: 'casual',
        condition: '12 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '20 dias',
        intervalHours: 480,
        message: 'Olá, {{primeiro_nome}}. Vou retirar essa condição especial do sistema por enquanto. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '20 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como estão os planos da {{empresa}}.',
        objective: 'Reativação a 35 dias',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-19',
    number: 19,
    title: 'Quanto tempo demora? / Preciso para ontem',
    category: 'timing',
    clientPhrase: '"Em quanto tempo fica pronto?" / "Preciso com urgência"',
    underlyingMeaning: 'Tem um evento, lançamento ou emergência e não pode esperar semanas.',
    whatNotToSay: '"Leva 2 meses", "Não tenho como fazer rápido", prometer entrega em 1h sem viabilidade.',
    diagnosticQuestion: 'Compreendo a urgência, {{primeiro_nome}}! Você tem uma data limite específica para colocar no ar?',
    shortResponse: 'Entregamos a primeira versão completa em {{prazo_entrega}} dias úteis para a sua validação.',
    consultativeResponse: 'Nosso processo foi estruturado para ser extremamente ágil: em até {{prazo_entrega}} dias úteis o projeto estará 100% pronto no ar. Se você tiver urgência máxima, conseguimos priorizar na fila de produção e te entregar uma prévia navegável em 48 horas. Atende à sua urgência?',
    whatsappResponse: 'Oi {{primeiro_nome}}! Conseguimos entregar em {{prazo_entrega}} dias úteis com tudo testado. Se você aprovar hoje, já reservo a equipe para dar o pontapé inicial agora mesmo!',
    callResponse: 'Perfeito, {{primeiro_nome}}! Entregamos em {{prazo_entrega}} dias. Se você tiver pressa, iniciando hoje conseguimos rodar a versão de testes muito antes.',
    nextStep: 'Fechar acordo imediato ancorado na garantia de velocidade.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, para garantirmos a entrega rápida até o fim desta semana, precisamos iniciar hoje. Podemos dar o start?',
        objective: 'Fechamento com urgência de cronograma',
        tone: 'direto',
        condition: '1 dia após objeção de urgência',
        whenNotToUse: 'Se já iniciou',
      },
      {
        number: 2,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: '{{primeiro_nome}}, tudo pronto do nosso lado para acelerar a produção da {{empresa}} assim que você der o ok!',
        objective: 'Disponibilidade de sprint rápida',
        tone: 'consultivo',
        condition: '2 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: 'Olá, {{primeiro_nome}}! Ainda precisa do projeto com entrega acelerada ou a data limite mudou?',
        objective: 'Checagem de nova data limite',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '10 dias',
        intervalHours: 240,
        message: 'Oi {{primeiro_nome}}, tudo bem? Fico à disposição quando quiser iniciar o cronograma.',
        objective: 'Lembrete',
        tone: 'profissional',
        condition: '10 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '18 dias',
        intervalHours: 432,
        message: 'Olá, {{primeiro_nome}}. Vou liberar a vaga expressa da agenda. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '18 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Quando surgir um novo projeto urgente na {{empresa}}, conte conosco!',
        objective: 'Reativação de projetos rápidos',
        tone: 'casual',
        condition: '35 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-20',
    number: 20,
    title: 'Quero começar no mês que vem / Me procura mais tarde',
    category: 'timing',
    clientPhrase: '"Me procura no mês que vem" / "Vamos deixar para o próximo trimestre"',
    underlyingMeaning: 'Quer adiar a decisão por conveniência, sobrecarga atual ou esperar virada de faturamento.',
    whatNotToSay: '"Não deixe para amanhã o que pode fazer hoje", pressionar agressivamente.',
    diagnosticQuestion: 'Perfeito, {{primeiro_nome}}! Já vou anotar aqui na agenda. Qual dia específico do próximo mês fica melhor para eu te mandar uma mensagem?',
    shortResponse: 'Combinado, {{primeiro_nome}}! Vou colocar na agenda para o dia 10 do próximo mês.',
    consultativeResponse: 'Excelente, {{primeiro_nome}}! Respeito 100% o seu timing. Só para eu deixar tudo engatilhado para você: se a gente deixar o layout pré-aprovado agora sem custo, no início do próximo mês nós apenas publicamos no ar sem perder tempo. O que acha dessa ideia?',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}! Anotei para te dar um alô no dia 05 do próximo mês. Se por acaso você quiser antecipar antes, é só me mandar uma mensagem por aqui. Ótimo mês de trabalho para vocês!',
    callResponse: 'Combinadíssimo, {{primeiro_nome}}. Vou registrar no meu sistema para te ligar na segunda semana do mês que vem. Te desejo excelentes negócios até lá!',
    nextStep: 'Agendar data exata no CRM e confirmar no WhatsApp.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Anotado com sucesso, {{primeiro_nome}}! Te chamo no próximo mês conforme combinamos. Bom trabalho por aí!',
        objective: 'Confirmação do agendamento',
        tone: 'profissional',
        condition: '1 dia após combinar recontato futuro',
        whenNotToUse: 'Se já confirmou',
      },
      {
        number: 2,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, passando só para deixar um abraço no meio do mês! Seguimos alinhados para o próximo mês.',
        objective: 'Toque leve de meio de mês',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}! Conforme combinamos no mês passado: como está a agenda da {{empresa}} para iniciarmos o projeto agora?',
        objective: 'Execução do recontato programado',
        tone: 'consultivo',
        condition: '30 dias (data combinada)',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '35 dias',
        intervalHours: 840,
        message: 'Oi {{primeiro_nome}}, tudo bem? Conseguiu checar o momento da {{empresa}} para tirarmos o site do papel?',
        objective: 'Checagem pós-data',
        tone: 'direto',
        condition: '35 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição quando o calendário da {{empresa}} estiver propício.',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '45 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como ficou o planejamento da {{empresa}}.',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-21',
    number: 21,
    title: 'Não quero mudar o que já está funcionando',
    category: 'necessidade',
    clientPhrase: '"Em time que está ganhando não se mexe" / "Sempre fizemos assim"',
    underlyingMeaning: 'Medo de instabilidade, quebrar fluxos consolidados ou criar dores de cabeça.',
    whatNotToSay: '"Quem pensa assim fica para trás", "Você está estagnado".',
    diagnosticQuestion: 'Totalmente sensato, {{primeiro_nome}}! Estabilidade é fundamental. E se a mudança for apenas uma melhoria complementar que não altera em nada o processo atual da equipe, apenas soma novos contatos?',
    shortResponse: 'Concordo plenamente, {{primeiro_nome}}! A ideia não é mudar sua operação, mas sim somar mais contatos qualificados no WhatsApp.',
    consultativeResponse: 'Faz todo sentido ter cautela, {{primeiro_nome}}. Nossa proposta não interfere no funcionamento interno da {{empresa}}: nós criamos um canal de atendimento mais rápido no WhatsApp que roda em paralelo. Se você não gostar, desativamos com 1 clique. Vale a pena experimentar sem risco?',
    whatsappResponse: 'Com certeza, {{primeiro_nome}}! O que funciona deve ser mantido. A proposta é apenas adicionar um atalho moderno para os clientes que chegam pelo celular. Sem mexer em nada do que já dá certo. Posso te mostrar em 1 minuto?',
    callResponse: 'Perfeito, {{primeiro_nome}}, concordo 100%. Nós não mexemos na sua estrutura atual, apenas criamos uma ponte direta para novos clientes que hoje procuram a {{empresa}} e não encontram um botão rápido.',
    nextStep: 'Apresentar a solução como um canal adicional/paralelo sem risco à operação existente.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '2 dias',
        intervalHours: 48,
        message: 'Oi {{primeiro_nome}}, o que acha de fazermos um teste paralelo de 7 dias sem alterar seu processo atual?',
        objective: 'Oferta de teste em paralelo',
        tone: 'consultivo',
        condition: '2 dias',
        whenNotToUse: 'Se rejeitou',
      },
      {
        number: 2,
        intervalRecommended: '5 dias',
        intervalHours: 120,
        message: '{{primeiro_nome}}, tudo bem? Qualquer dúvida sobre como integrar sem atrito na rotina, estou por aqui.',
        objective: 'Segurança operacional',
        tone: 'casual',
        condition: '5 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '12 dias',
        intervalHours: 288,
        message: 'Olá, {{primeiro_nome}}! Muito sucesso com as rotinas consolidadas da {{empresa}}.',
        objective: 'Apoio profissional',
        tone: 'profissional',
        condition: '12 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando quiser testar melhorias incrementais, conte conosco!',
        objective: 'Porta aberta',
        tone: 'casual',
        condition: '25 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar o contato por aqui. Um abraço para a equipe!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '45 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '70 dias',
        intervalHours: 1680,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como tem sido o volume de novos clientes na {{empresa}}.',
        objective: 'Reativação a 70 dias',
        tone: 'casual',
        condition: '70 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-22',
    number: 22,
    title: 'Preciso falar com minha esposa / marido',
    category: 'decisor',
    clientPhrase: '"Preciso conversar com minha esposa/esposo antes"',
    underlyingMeaning: 'Empresas familiares onde o cônjuge atua como conselheiro ou co-decisor financeiro.',
    whatNotToSay: '"Quem manda no negócio é você ou seu cônjuge?", desrespeitar a dinâmica familiar.',
    diagnosticQuestion: 'Perfeito, {{primeiro_nome}}! Decisões em família são as mais importantes. O que ela/ele costuma avaliar com mais atenção nesse tipo de investimento?',
    shortResponse: 'Com toda certeza, {{primeiro_nome}}! Alinhar em família é fundamental. Me diga o que ela/ele achou depois!',
    consultativeResponse: 'Com certeza, {{primeiro_nome}}, apoio total! Uma dica: envie o link da demonstração que preparei para que ela/ele veja como a {{empresa}} vai ficar moderna e profissional. Quer que eu te passe o link direto com uma mensagem pronta para você encaminhar?',
    whatsappResponse: 'Excelente, {{primeiro_nome}}! Família em primeiro lugar. Segue o link com a demonstração visual pronta para você mostrar para ela/ele no celular: {{link_demonstracao}}. Te dou um toque depois para saber o que acharam!',
    callResponse: 'Com certeza, {{primeiro_nome}}, alinhar com quem está ao nosso lado é essencial. Veja com calma com ela/ele e me diga se vocês gostaram da proposta. Fico no aguardo!',
    nextStep: 'Enviar link visual fácil de entender pelo celular para aprovação familiar.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, conseguiu mostrar o exemplo para sua esposa/esposo? O que ela/ele achou?',
        objective: 'Checagem do parecer familiar',
        tone: 'casual',
        condition: '1 dia após conversa com cônjuge',
        whenNotToUse: 'Se pediu mais tempo',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Se vocês tiveram alguma dúvida sobre as formas de pagamento, posso explicar com calma.',
        objective: 'Apoio a dúvidas financeiras familiares',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Chegaram a uma decisão em conjunto na {{empresa}}?',
        objective: 'Checagem de alinhamento',
        tone: 'direto',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '14 dias',
        intervalHours: 336,
        message: 'Oi {{primeiro_nome}}, tudo bem? Quando vocês quiserem dar esse passo juntos, contem comigo!',
        objective: 'Porta aberta',
        tone: 'casual',
        condition: '14 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '25 dias',
        intervalHours: 600,
        message: 'Olá, {{primeiro_nome}}. Vou pausar meus contatos por aqui. Um abraço para você e sua família!',
        objective: 'Pausa amigável',
        tone: 'profissional',
        condition: '25 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '45 dias',
        intervalHours: 1080,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como estão os negócios na {{empresa}} neste mês?',
        objective: 'Reativação a 45 dias',
        tone: 'casual',
        condition: '45 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-23',
    number: 23,
    title: 'Não confio em serviços pela internet',
    category: 'confianca',
    clientPhrase: '"Não gosto de fechar nada pela internet" / "Prefiro presencial"',
    underlyingMeaning: 'Necessidade de contato humano, formalidade contratual ou receio de perfis anônimos.',
    whatNotToSay: '"Presencial é coisa do passado", "Ninguém mais faz reunião presencial".',
    diagnosticQuestion: 'Compreendo perfeitamente, {{primeiro_nome}}! O contato humano faz toda a diferença. Se fizermos uma chamada de vídeo rápida de 10 minutos para você ver quem está por trás do projeto, te deixaria mais confortável?',
    shortResponse: 'Super justo, {{primeiro_nome}}! Podemos fazer uma chamada de vídeo rápida com câmera aberta para nos conhecermos.',
    consultativeResponse: 'Totalmente compreensível, {{primeiro_nome}}. Confiança é a base de qualquer parceria comercial. Podemos fazer uma chamada de vídeo no Google Meet ou WhatsApp para eu me apresentar, te mostrar meu ambiente de trabalho e tirar todas as suas dúvidas ao vivo. O que acha de amanhã às 14h?',
    whatsappResponse: 'Entendo perfeitamente, {{primeiro_nome}}! Faço questão de total transparência: envio meus dados cadastrais e podemos fazer uma chamada com câmera aberta de 10 minutos para você me conhecer. Fica mais seguro para você?',
    callResponse: 'Com certeza, {{primeiro_nome}}, nada substitui ver com quem estamos lidando. Vamos abrir uma chamada de vídeo rápida agora ou marcar para o horário que for mais tranquilo para você?',
    nextStep: 'Agendar chamada com vídeo/Google Meet ou fornecer dados de identificação claros.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, qual horário fica melhor para nossa chamada de vídeo: pela manhã ou à tarde?',
        objective: 'Agendamento de vídeo',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se já agendou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Segue meu perfil profissional e dados de contato para você conferir com calma.',
        objective: 'Envio de credenciais e dados',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Fico à disposição para quando quiser conversar por chamada ou vídeo.',
        objective: 'Disponibilidade contínua',
        tone: 'profissional',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Se preferir que eu te ligue no telefone fixo da {{empresa}}, é só me avisar!',
        objective: 'Opção de telefone fixo',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Vou pausar meus contatos por aqui. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Passando para saber como estão as atividades na {{empresa}}.',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-24',
    number: 24,
    title: 'Meu sócio não gostou / Rejeição interna',
    category: 'decisor',
    clientPhrase: '"Falei com meu sócio e ele não gostou / não aprovou"',
    underlyingMeaning: 'O sócio teve uma objeção específica que o interlocutor não soube rebater, ou achou caro/desnecessário.',
    whatNotToSay: '"Seu sócio não entende nada", "Tenta convencer ele de novo", desistir agressivamente.',
    diagnosticQuestion: 'Super compreendido, {{primeiro_nome}}! Qual foi o ponto específico que ele mais estranhou: o estilo visual, o preço ou a utilidade para o momento da {{empresa}}?',
    shortResponse: 'Entendido, {{primeiro_nome}}! O que ele achou que precisaria ser diferente para aprovar?',
    consultativeResponse: 'Faz todo sentido respeitar a visão do seu sócio, {{primeiro_nome}}. Muitas vezes o sócio estranha quando não vê a lógica por trás do projeto. Se você me disser qual foi a ressalva dele, posso fazer um ajuste no conceito em 24h sem custo para ele reavaliar. Qual foi o ponto que pegou?',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}, agradeço pela sinceridade! Se você puder me dizer qual foi a principal dúvida dele (preço, layout ou prazo), eu ajusto a proposta para tentar atender a visão dele. O que ele comentou?',
    callResponse: 'Entendido perfeitamente, {{primeiro_nome}}. Me diga uma coisa: o que ele gostaria de ver diferente para dar um sinal verde? Podemos adaptar 100%.',
    nextStep: 'Descobrir a causa da rejeição do sócio e oferecer reformulação focada na dor dele.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, se for o caso de fazermos uma chamada de 5 minutos com ele para explicar a parte técnica, estou à disposição.',
        objective: 'Oferta de chamada com o sócio',
        tone: 'consultivo',
        condition: '1 dia',
        whenNotToUse: 'Se rejeitou categoricamente',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, ajustei aquele ponto que seu sócio estranhou no link de teste. Quer dar uma olhada rápida?',
        objective: 'Apresentação do ajuste do sócio',
        tone: 'direto',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Caso vocês queiram reavaliar no próximo mês com outro formato, contem comigo.',
        objective: 'Porta aberta futura',
        tone: 'profissional',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Sucesso nos projetos da {{empresa}}!',
        objective: 'Apoio sem cobrança',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Vou encerrar o acompanhamento desta proposta. Um abraço!',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Alguma novidade na estratégia digital da {{empresa}}?',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
  {
    id: 'obj-25',
    number: 25,
    title: 'Só usamos redes sociais / Meu Instagram já vende',
    category: 'necessidade',
    clientPhrase: '"A gente só vende pelo Instagram" / "Não precisamos de site, só de redes sociais"',
    underlyingMeaning: 'Acredita que o Instagram substitui um site profissional, desconhecendo a perda de clientes do Google e a dependência do algoritmo.',
    whatNotToSay: '"Instagram vai acabar", "Você está sendo ingênuo", desdenhar o alcance do Instagram.',
    diagnosticQuestion: 'O Instagram é uma potência mesmo, {{primeiro_nome}}! Parabéns pelo trabalho na rede. O que vocês colocam hoje no link da bio quando o cliente quer agendar ou ver o catálogo completo?',
    shortResponse: 'Maravilha, {{primeiro_nome}}! E hoje o link da bio de vocês direciona para uma página rápida ou direto para um link cru?',
    consultativeResponse: 'O Instagram é fantástico para atração, {{primeiro_nome}}! Nosso projeto serve justamente para potencializar o seu perfil: quando o cliente clica no link da sua bio, em vez de abrir um link genérico, ele encontra um mini-site ultra rápido que converte o seguidor em conversa direta no WhatsApp. Isso costuma aumentar as vendas em até 40%. Quer ver um modelo de página de bio?',
    whatsappResponse: 'Perfeito, {{primeiro_nome}}! O Instagram é o melhor canal visual. Nossa estrutura funciona como a "Página de Bio Profissional" da {{empresa}}, multiplicando os cliques no seu WhatsApp. Quer dar uma olhada em como ficaria para o perfil de vocês?',
    callResponse: 'Excelente, {{primeiro_nome}}, redes sociais são indispensáveis. A ideia é criar o destino perfeito para quem clica no seu perfil: uma página que carrega em 1 segundo e leva o cliente para o seu WhatsApp sem dispersão.',
    nextStep: 'Enquadrar o projeto como a "Página de Bio Profissional" que potencializa o Instagram.',
    followUps: [
      {
        number: 1,
        intervalRecommended: '1 dia',
        intervalHours: 24,
        message: 'Oi {{primeiro_nome}}, montei um print de como ficaria a nova página de link da bio da {{empresa}}. Posso te mandar?',
        objective: 'Envio de modelo de link da bio',
        tone: 'casual',
        condition: '1 dia',
        whenNotToUse: 'Se recusou',
      },
      {
        number: 2,
        intervalRecommended: '3 dias',
        intervalHours: 72,
        message: '{{primeiro_nome}}, tudo bem? Esse formato garante que o seguidor não se perca e fale direto no WhatsApp de vocês.',
        objective: 'Reforçar conversão de seguidor em lead',
        tone: 'consultivo',
        condition: '3 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 3,
        intervalRecommended: '7 dias',
        intervalHours: 168,
        message: 'Olá, {{primeiro_nome}}! Conseguimos implementar a página de bio em 24h para a {{empresa}}.',
        objective: 'Oferta de entrega expressa de bio',
        tone: 'direto',
        condition: '7 dias',
        whenNotToUse: 'DNC',
      },
      {
        number: 4,
        intervalRecommended: '15 dias',
        intervalHours: 360,
        message: 'Oi {{primeiro_nome}}, tudo bem? Sucesso com as postagens e stories da {{empresa}}!',
        objective: 'Apoio nas redes',
        tone: 'casual',
        condition: '15 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 5,
        intervalRecommended: '30 dias',
        intervalHours: 720,
        message: 'Olá, {{primeiro_nome}}. Fico à disposição caso queiram otimizar as conversões do Instagram no futuro.',
        objective: 'Pausa',
        tone: 'profissional',
        condition: '30 dias',
        whenNotToUse: 'Se respondeu',
      },
      {
        number: 6,
        intervalRecommended: '60 dias',
        intervalHours: 1440,
        message: 'Oi, {{primeiro_nome}}, tudo bem? Como tem sido o retorno de clientes vindos das redes na {{empresa}}?',
        objective: 'Reativação a 60 dias',
        tone: 'casual',
        condition: '60 dias',
        whenNotToUse: 'DNC',
      },
    ],
  },
];
